# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/23_dims.ipynb.

# %% auto 0
__all__ = ['dimmed', 'dim1', 'dim2', 'dim3', 'dim4']

# %% ../nbs/23_dims.ipynb 6
#| export


# %% ../nbs/23_dims.ipynb 8
from typing import TypeAlias

# %% ../nbs/23_dims.ipynb 10
#| export


# %% ../nbs/23_dims.ipynb 12
from ptyp import Prototype

# %% ../nbs/23_dims.ipynb 14
from .iter import itertype
from .data import shaped
from .arrs import nparray

# %% ../nbs/23_dims.ipynb 16
@Prototype(list, nparray, shaped, itertype, hasattrs=('ndim', ))
class dimmed: 'np.ndarray with shape (i, )'

@Prototype(dimmed, attrs=dict(ndim=1))
class dim1: 'np.ndarray with shape (i, )'

@Prototype(dimmed, attrs=dict(ndim=2))
class dim2: 'np.ndarray with shape (i, j, )'

@Prototype(dimmed, attrs=dict(ndim=3))
class dim3: 'np.ndarray with shape (i, j, k, )'

@Prototype(dimmed, attrs=dict(ndim=4))
class dim4: 'np.ndarray with shape (i, j, k, l, )'
