# Generated by Django 4.2.3 on 2024-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SChSetup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "SChSetup",
                "verbose_name_plural": "SChSetups",
                "default_permissions": (
                    "can_administer",
                    "add",
                    "change",
                    "delete",
                    "list",
                ),
            },
        ),
    ]
