#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class methods:
    fluent_name = ...
    child_names = ...
    accelerated_non_iterative_time_marching = ...
    convergence_acceleration_for_stretched_meshes = ...
    discretization_scheme = ...
    expert = ...
    flux_type = ...
    frozen_flux = ...
    gradient_scheme = ...
    high_order_term_relaxation = ...
    multiphase_numerics = ...
    nb_gradient_boundary_option = ...
    nita_expert_controls = ...
    noniterative_time_advance = ...
    overset = ...
    p_v_coupling = ...
    phase_based_vof_discretization = ...
    reduced_rank_extrapolation = ...
    reduced_rank_extrapolation_options = ...
    residual_smoothing = ...
    unsteady_1st_order = ...
    unsteady_2nd_order = ...
    unsteady_2nd_order_bounded = ...
    unsteady_global_time = ...
    vof_numerics = ...
    warped_face_gradient_correction = ...
    pseudo_time_method = ...
    command_names = ...

    def set_solution_methods_to_default(self, ):
        """
        'set_solution_methods_to_default' command.
        """

