#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class report_definitions:
    fluent_name = ...
    child_names = ...
    mesh = ...
    surface = ...
    volume = ...
    force = ...
    lift = ...
    drag = ...
    moment = ...
    flux = ...
    injection = ...
    user_defined = ...
    aeromechanics = ...
    expression = ...
    custom = ...
    command_names = ...

    def compute(self, report_defs: List[str]):
        """
        'compute' command.
        
        Parameters
        ----------
            report_defs : typing.List[str]
                'report_defs' child.
        
        """

