# Generated by Django 4.2.7 on 2023-12-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evercycle_models', '0002_remove_organization_address_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_organizations', to='evercycle_models.organization'),
        ),
    ]
