# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/backup/backup_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
from truera.protobuf.backup import backup_info_pb2 as truera_dot_protobuf_dot_backup_dot_backup__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+truera/protobuf/backup/backup_service.proto\x12\rtruera.backup\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a(truera/protobuf/backup/backup_info.proto\"\x16\n\x14TriggerBackupRequest\"B\n\x15TriggerBackupResponse\x12)\n\x06\x62\x61\x63kup\x18\x01 \x01(\x0b\x32\x19.truera.backup.BackupInfo\"3\n\x15TriggerRestoreRequest\x12\x1a\n\x12\x62\x61\x63kup_folder_path\x18\x01 \x01(\t\"\x18\n\x16TriggerRestoreResponse\"\x14\n\x12ListBackupsRequest\"A\n\x13ListBackupsResponse\x12*\n\x07\x62\x61\x63kups\x18\x01 \x03(\x0b\x32\x19.truera.backup.BackupInfo\"\x1c\n\x1a\x43leanupStaleBackupsRequest\"Q\n\x1b\x43leanupStaleBackupsResponse\x12\x32\n\x0f\x63leanup_backups\x18\x01 \x03(\x0b\x32\x19.truera.backup.BackupInfo2\x95\x05\n\rBackupService\x12t\n\rTriggerBackup\x12#.truera.backup.TriggerBackupRequest\x1a$.truera.backup.TriggerBackupResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x1a\x10/backup/_trigger\x12z\n\x0eTriggerRestore\x12$.truera.backup.TriggerRestoreRequest\x1a%.truera.backup.TriggerRestoreResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x1a\x10/backup/_restore:\x01*\x12\x65\n\x0bListBackups\x12!.truera.backup.ListBackupsRequest\x1a\".truera.backup.ListBackupsResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\x07/backup\x12\xaa\x02\n\x13\x43leanupStaleBackups\x12).truera.backup.CleanupStaleBackupsRequest\x1a*.truera.backup.CleanupStaleBackupsResponse\"\xbb\x01\x92\x41\xa1\x01\x1a\x9e\x01This endpoint internally fetches list of all the stored backups and deletes the stale backups. Number of backups to be maintained is a configurable parameter.\x82\xd3\xe4\x93\x02\x10\x1a\x0e/backup/_cleanB]\n\x1a\x63om.truera.protobuf.backupB\x12\x42\x61\x63kupServiceProtoP\x01Z)truera.com/protobuf/backup/backup_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.backup.backup_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.truera.protobuf.backupB\022BackupServiceProtoP\001Z)truera.com/protobuf/backup/backup_service'
  _globals['_BACKUPSERVICE'].methods_by_name['TriggerBackup']._options = None
  _globals['_BACKUPSERVICE'].methods_by_name['TriggerBackup']._serialized_options = b'\202\323\344\223\002\022\032\020/backup/_trigger'
  _globals['_BACKUPSERVICE'].methods_by_name['TriggerRestore']._options = None
  _globals['_BACKUPSERVICE'].methods_by_name['TriggerRestore']._serialized_options = b'\202\323\344\223\002\025\032\020/backup/_restore:\001*'
  _globals['_BACKUPSERVICE'].methods_by_name['ListBackups']._options = None
  _globals['_BACKUPSERVICE'].methods_by_name['ListBackups']._serialized_options = b'\202\323\344\223\002\t\022\007/backup'
  _globals['_BACKUPSERVICE'].methods_by_name['CleanupStaleBackups']._options = None
  _globals['_BACKUPSERVICE'].methods_by_name['CleanupStaleBackups']._serialized_options = b'\222A\241\001\032\236\001This endpoint internally fetches list of all the stored backups and deletes the stale backups. Number of backups to be maintained is a configurable parameter.\202\323\344\223\002\020\032\016/backup/_clean'
  _globals['_TRIGGERBACKUPREQUEST']._serialized_start=182
  _globals['_TRIGGERBACKUPREQUEST']._serialized_end=204
  _globals['_TRIGGERBACKUPRESPONSE']._serialized_start=206
  _globals['_TRIGGERBACKUPRESPONSE']._serialized_end=272
  _globals['_TRIGGERRESTOREREQUEST']._serialized_start=274
  _globals['_TRIGGERRESTOREREQUEST']._serialized_end=325
  _globals['_TRIGGERRESTORERESPONSE']._serialized_start=327
  _globals['_TRIGGERRESTORERESPONSE']._serialized_end=351
  _globals['_LISTBACKUPSREQUEST']._serialized_start=353
  _globals['_LISTBACKUPSREQUEST']._serialized_end=373
  _globals['_LISTBACKUPSRESPONSE']._serialized_start=375
  _globals['_LISTBACKUPSRESPONSE']._serialized_end=440
  _globals['_CLEANUPSTALEBACKUPSREQUEST']._serialized_start=442
  _globals['_CLEANUPSTALEBACKUPSREQUEST']._serialized_end=470
  _globals['_CLEANUPSTALEBACKUPSRESPONSE']._serialized_start=472
  _globals['_CLEANUPSTALEBACKUPSRESPONSE']._serialized_end=553
  _globals['_BACKUPSERVICE']._serialized_start=556
  _globals['_BACKUPSERVICE']._serialized_end=1217
# @@protoc_insertion_point(module_scope)
