# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/backup/backup_info.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(truera/protobuf/backup/backup_info.proto\x12\rtruera.backup\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n\nBackupInfo\x12\x1a\n\x12\x62\x61\x63kup_folder_path\x18\x01 \x01(\t\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampBW\n\x1a\x63om.truera.protobuf.backupB\x0f\x42\x61\x63kupInfoProtoP\x01Z&truera.com/protobuf/backup/backup_infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.backup.backup_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.truera.protobuf.backupB\017BackupInfoProtoP\001Z&truera.com/protobuf/backup/backup_info'
  _globals['_BACKUPINFO']._serialized_start=92
  _globals['_BACKUPINFO']._serialized_end=180
# @@protoc_insertion_point(module_scope)
