# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/scheduled_ingestion_service/scheduled_ingestion_record.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from truera.protobuf.public.scheduled_ingestion_service import scheduled_ingestion_service_pb2 as truera_dot_protobuf_dot_public_dot_scheduled__ingestion__service_dot_scheduled__ingestion__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nStruera/protobuf/public/scheduled_ingestion_service/scheduled_ingestion_record.proto\x12\x1atruera.scheduled_ingestion\x1a\x1fgoogle/protobuf/timestamp.proto\x1aTtruera/protobuf/public/scheduled_ingestion_service/scheduled_ingestion_service.proto\"\xce\x01\n\x18ScheduledIngestionRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x45\n\x07request\x18\x02 \x01(\x0b\x32\x34.truera.scheduled_ingestion.ScheduleIngestionRequest\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x1a\n\x12\x64\x61ta_collection_id\x18\x04 \x01(\t\x12/\n\x0b\x63\x61nceled_on\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x9d\x01\n\'com.truera.protobuf.scheduled_ingestionB\x1dScheduledIngestionRecordProtoP\x01ZQtruera.com/protobuf/public/scheduled_ingestion_service/scheduled_ingestion_recordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.scheduled_ingestion_service.scheduled_ingestion_record_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.truera.protobuf.scheduled_ingestionB\035ScheduledIngestionRecordProtoP\001ZQtruera.com/protobuf/public/scheduled_ingestion_service/scheduled_ingestion_record'
  _globals['_SCHEDULEDINGESTIONRECORD']._serialized_start=235
  _globals['_SCHEDULEDINGESTIONRECORD']._serialized_end=441
# @@protoc_insertion_point(module_scope)
