# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from truera.protobuf.public.management import management_service_pb2 as truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2


class ManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/truera.ManagementService/Ping',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
                )
        self.ListAuth0UsersOfTenant = channel.unary_unary(
                '/truera.ManagementService/ListAuth0UsersOfTenant',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListAuth0UsersOfTenantRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListAuth0UsersOfTenantResponse.FromString,
                )
        self.SampleWorkflow = channel.unary_unary(
                '/truera.ManagementService/SampleWorkflow',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
                )
        self.CreateTenant = channel.unary_unary(
                '/truera.ManagementService/CreateTenant',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantResponse.FromString,
                )
        self.GetTenant = channel.unary_unary(
                '/truera.ManagementService/GetTenant',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantResponse.FromString,
                )
        self.ListTenants = channel.unary_unary(
                '/truera.ManagementService/ListTenants',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsResponse.FromString,
                )
        self.SearchTenant = channel.unary_unary(
                '/truera.ManagementService/SearchTenant',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SearchTenantRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsResponse.FromString,
                )
        self.CreateTenantDeployment = channel.unary_unary(
                '/truera.ManagementService/CreateTenantDeployment',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantDeploymentRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantDeploymentResponse.FromString,
                )
        self.GetTenantDeployment = channel.unary_unary(
                '/truera.ManagementService/GetTenantDeployment',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantDeploymentRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantDeploymentResponse.FromString,
                )
        self.UpdateTenantDeployment = channel.unary_unary(
                '/truera.ManagementService/UpdateTenantDeployment',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantDeploymentRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantDeploymentResponse.FromString,
                )
        self.DeleteTenantDeployment = channel.unary_unary(
                '/truera.ManagementService/DeleteTenantDeployment',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteTenantDeploymentRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteTenantDeploymentResponse.FromString,
                )
        self.AddUserToTenant = channel.unary_unary(
                '/truera.ManagementService/AddUserToTenant',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.AddUserToTenantRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.AddUserToTenantResponse.FromString,
                )
        self.TriggerPasswordResetForUser = channel.unary_unary(
                '/truera.ManagementService/TriggerPasswordResetForUser',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.TriggerPasswordResetForUserRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.TriggerPasswordResetForUserResponse.FromString,
                )
        self.DeleteUserFromTenant = channel.unary_unary(
                '/truera.ManagementService/DeleteUserFromTenant',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteUserFromTenantRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteUserFromTenantResponse.FromString,
                )


class ManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuth0UsersOfTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SampleWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTenants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTenantDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTenantDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenantDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerPasswordResetForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserFromTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.SerializeToString,
            ),
            'ListAuth0UsersOfTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuth0UsersOfTenant,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListAuth0UsersOfTenantRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListAuth0UsersOfTenantResponse.SerializeToString,
            ),
            'SampleWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleWorkflow,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.SerializeToString,
            ),
            'CreateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenant,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantResponse.SerializeToString,
            ),
            'GetTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenant,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantResponse.SerializeToString,
            ),
            'ListTenants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTenants,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsResponse.SerializeToString,
            ),
            'SearchTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTenant,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SearchTenantRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsResponse.SerializeToString,
            ),
            'CreateTenantDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenantDeployment,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantDeploymentRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantDeploymentResponse.SerializeToString,
            ),
            'GetTenantDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantDeployment,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantDeploymentRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantDeploymentResponse.SerializeToString,
            ),
            'UpdateTenantDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTenantDeployment,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantDeploymentRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantDeploymentResponse.SerializeToString,
            ),
            'DeleteTenantDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenantDeployment,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteTenantDeploymentRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteTenantDeploymentResponse.SerializeToString,
            ),
            'AddUserToTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserToTenant,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.AddUserToTenantRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.AddUserToTenantResponse.SerializeToString,
            ),
            'TriggerPasswordResetForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerPasswordResetForUser,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.TriggerPasswordResetForUserRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.TriggerPasswordResetForUserResponse.SerializeToString,
            ),
            'DeleteUserFromTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserFromTenant,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteUserFromTenantRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteUserFromTenantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'truera.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/Ping',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAuth0UsersOfTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/ListAuth0UsersOfTenant',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListAuth0UsersOfTenantRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListAuth0UsersOfTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SampleWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/SampleWorkflow',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/CreateTenant',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/GetTenant',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTenants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/ListTenants',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/SearchTenant',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SearchTenantRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ListTenantsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTenantDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/CreateTenantDeployment',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantDeploymentRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreateTenantDeploymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTenantDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/GetTenantDeployment',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantDeploymentRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantDeploymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTenantDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/UpdateTenantDeployment',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantDeploymentRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantDeploymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTenantDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/DeleteTenantDeployment',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteTenantDeploymentRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteTenantDeploymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserToTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/AddUserToTenant',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.AddUserToTenantRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.AddUserToTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerPasswordResetForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/TriggerPasswordResetForUser',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.TriggerPasswordResetForUserRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.TriggerPasswordResetForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUserFromTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.ManagementService/DeleteUserFromTenant',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteUserFromTenantRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.DeleteUserFromTenantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MultiTenantManagementServiceStub(object):
    """* New Service for mulittenant management *

    TODO: Migrate above service to SingleboxManagementService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingInternal = channel.unary_unary(
                '/truera.MultiTenantManagementService/PingInternal',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
                )
        self.TestConnectionToMultiTenantDeploymentRbac = channel.unary_unary(
                '/truera.MultiTenantManagementService/TestConnectionToMultiTenantDeploymentRbac',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
                )
        self.TestManagementDbConnection = channel.unary_unary(
                '/truera.MultiTenantManagementService/TestManagementDbConnection',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
                )
        self.SignUpNewTenantInternal = channel.unary_unary(
                '/truera.MultiTenantManagementService/SignUpNewTenantInternal',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SignUpNewTenantRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.FromString,
                )
        self.InviteUserToExistingTenant = channel.unary_unary(
                '/truera.MultiTenantManagementService/InviteUserToExistingTenant',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.InviteNewUserRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.FromString,
                )
        self.RetriggerEmailVerification = channel.unary_unary(
                '/truera.MultiTenantManagementService/RetriggerEmailVerification',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.RetriggerEmailVerificationRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.RetriggerEmailVerificationResponse.FromString,
                )
        self.ProvisionPreconfiguredTenant = channel.unary_unary(
                '/truera.MultiTenantManagementService/ProvisionPreconfiguredTenant',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SignUpNewTenantRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.FromString,
                )
        self.ManualUpdateAwsSubscriptionEntitlements = channel.unary_unary(
                '/truera.MultiTenantManagementService/ManualUpdateAwsSubscriptionEntitlements',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManualUpdateAwsSubscriptionEntitlementsRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManualUpdateAwsSubscriptionEntitlementsResponse.FromString,
                )


class MultiTenantManagementServiceServicer(object):
    """* New Service for mulittenant management *

    TODO: Migrate above service to SingleboxManagementService
    """

    def PingInternal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestConnectionToMultiTenantDeploymentRbac(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestManagementDbConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignUpNewTenantInternal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteUserToExistingTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetriggerEmailVerification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvisionPreconfiguredTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManualUpdateAwsSubscriptionEntitlements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiTenantManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingInternal': grpc.unary_unary_rpc_method_handler(
                    servicer.PingInternal,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.SerializeToString,
            ),
            'TestConnectionToMultiTenantDeploymentRbac': grpc.unary_unary_rpc_method_handler(
                    servicer.TestConnectionToMultiTenantDeploymentRbac,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.SerializeToString,
            ),
            'TestManagementDbConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.TestManagementDbConnection,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.SerializeToString,
            ),
            'SignUpNewTenantInternal': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUpNewTenantInternal,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SignUpNewTenantRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.SerializeToString,
            ),
            'InviteUserToExistingTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteUserToExistingTenant,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.InviteNewUserRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.SerializeToString,
            ),
            'RetriggerEmailVerification': grpc.unary_unary_rpc_method_handler(
                    servicer.RetriggerEmailVerification,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.RetriggerEmailVerificationRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.RetriggerEmailVerificationResponse.SerializeToString,
            ),
            'ProvisionPreconfiguredTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvisionPreconfiguredTenant,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SignUpNewTenantRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.SerializeToString,
            ),
            'ManualUpdateAwsSubscriptionEntitlements': grpc.unary_unary_rpc_method_handler(
                    servicer.ManualUpdateAwsSubscriptionEntitlements,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManualUpdateAwsSubscriptionEntitlementsRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManualUpdateAwsSubscriptionEntitlementsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'truera.MultiTenantManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MultiTenantManagementService(object):
    """* New Service for mulittenant management *

    TODO: Migrate above service to SingleboxManagementService
    """

    @staticmethod
    def PingInternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.MultiTenantManagementService/PingInternal',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestConnectionToMultiTenantDeploymentRbac(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.MultiTenantManagementService/TestConnectionToMultiTenantDeploymentRbac',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestManagementDbConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.MultiTenantManagementService/TestManagementDbConnection',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignUpNewTenantInternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.MultiTenantManagementService/SignUpNewTenantInternal',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SignUpNewTenantRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InviteUserToExistingTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.MultiTenantManagementService/InviteUserToExistingTenant',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.InviteNewUserRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetriggerEmailVerification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.MultiTenantManagementService/RetriggerEmailVerification',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.RetriggerEmailVerificationRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.RetriggerEmailVerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProvisionPreconfiguredTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.MultiTenantManagementService/ProvisionPreconfiguredTenant',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.SignUpNewTenantRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.CreatedUserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ManualUpdateAwsSubscriptionEntitlements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.MultiTenantManagementService/ManualUpdateAwsSubscriptionEntitlements',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManualUpdateAwsSubscriptionEntitlementsRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManualUpdateAwsSubscriptionEntitlementsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TenantConfigManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingInternal = channel.unary_unary(
                '/truera.TenantConfigManagementService/PingInternal',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
                )
        self.GetTenantConfig = channel.unary_unary(
                '/truera.TenantConfigManagementService/GetTenantConfig',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantConfigRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantConfigResponse.FromString,
                )
        self.GetAllTenantConfigs = channel.unary_unary(
                '/truera.TenantConfigManagementService/GetAllTenantConfigs',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetAllTenantConfigsRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetAllTenantConfigsResponse.FromString,
                )
        self.UpdateTenantConfig = channel.unary_unary(
                '/truera.TenantConfigManagementService/UpdateTenantConfig',
                request_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantConfigRequest.SerializeToString,
                response_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantConfigResponse.FromString,
                )


class TenantConfigManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingInternal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTenantConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTenantConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TenantConfigManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingInternal': grpc.unary_unary_rpc_method_handler(
                    servicer.PingInternal,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.SerializeToString,
            ),
            'GetTenantConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantConfig,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantConfigRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantConfigResponse.SerializeToString,
            ),
            'GetAllTenantConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTenantConfigs,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetAllTenantConfigsRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetAllTenantConfigsResponse.SerializeToString,
            ),
            'UpdateTenantConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTenantConfig,
                    request_deserializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantConfigRequest.FromString,
                    response_serializer=truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'truera.TenantConfigManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TenantConfigManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingInternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.TenantConfigManagementService/PingInternal',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.ManagementPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTenantConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.TenantConfigManagementService/GetTenantConfig',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantConfigRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetTenantConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllTenantConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.TenantConfigManagementService/GetAllTenantConfigs',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetAllTenantConfigsRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.GetAllTenantConfigsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTenantConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/truera.TenantConfigManagementService/UpdateTenantConfig',
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantConfigRequest.SerializeToString,
            truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2.UpdateTenantConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
