
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-07T05:28:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e23766ee4650f2434d4e8a20d54fc1bfd1663ead",
 "version": "1.2.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
