
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-03T13:17:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "20b8d03553b31ef2199f352b4b63474d69785e29",
 "version": "1.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
