# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyhdmap/proto/hdmap_lib/proto/object.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyhdmap.proto.hdmap_lib.proto import id_pb2 as pyhdmap_dot_proto_dot_hdmap__lib_dot_proto_dot_id__pb2
from pyhdmap.proto.hdmap_lib.proto import geometry_pb2 as pyhdmap_dot_proto_dot_hdmap__lib_dot_proto_dot_geometry__pb2
from pyhdmap.proto.hdmap_lib.proto import attribute_pb2 as pyhdmap_dot_proto_dot_hdmap__lib_dot_proto_dot_attribute__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*pyhdmap/proto/hdmap_lib/proto/object.proto\x12\thdmap_lib\x1a&pyhdmap/proto/hdmap_lib/proto/id.proto\x1a,pyhdmap/proto/hdmap_lib/proto/geometry.proto\x1a-pyhdmap/proto/hdmap_lib/proto/attribute.proto\"\xaa\x06\n\x06Object\x12\x19\n\x02id\x18\x01 \x01(\x0b\x32\r.hdmap_lib.Id\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.hdmap_lib.Object.Type\x12#\n\x07polygon\x18\x03 \x01(\x0b\x32\x12.hdmap_lib.Polygon\x12\x0e\n\x06height\x18\x04 \x01(\x01\x12\x0c\n\x04text\x18\x05 \x01(\t\x12/\n\ncross_type\x18\x06 \x01(\x0e\x32\x1b.hdmap_lib.Object.CrossType\x12(\n\nattributes\x18\x07 \x03(\x0b\x32\x14.hdmap_lib.Attribute\"\xdd\x03\n\x04Type\x12\x08\n\x04NONE\x10\x01\x12\r\n\tSIDE_WALK\x10\x02\x12\x11\n\rCHARGING_PILE\x10\x03\x12\x08\n\x04TEXT\x10\x04\x12\x0f\n\x0bGROUND_SIGN\x10\x05\x12\x0f\n\x0b\x42US_STATION\x10\x06\x12\x10\n\x0cTRAFFIC_SIGN\x10\x07\x12\x19\n\x15HEIGHT_LIMIT_OBSTACLE\x10\x08\x12\x0c\n\x08\x42UILDING\x10\t\x12\x15\n\x11\x44\x45\x43\x45LERATION_ZONE\x10\n\x12\x19\n\x15NON_SLIP_RAMP_MARKING\x10\x0b\x12\x12\n\x0e\x44IVERSION_LINE\x10\x0c\x12\x11\n\rLOCK_PAVILION\x10\r\x12\r\n\tREST_AREA\x10\x0e\x12\x16\n\x12WORKING_QUEUE_AREA\x10\x0f\x12\x11\n\rCHARGING_AREA\x10\x10\x12\x14\n\x10GRASS_GREEN_BELT\x10\x11\x12\x15\n\x11PEDESTRIAN_ISLAND\x10\x12\x12\x1a\n\x16\x45MERGENCY_PARKING_ZONE\x10\x13\x12\x12\n\x0e\x46ORBIDDEN_AREA\x10\x14\x12\x0e\n\nCLEAR_AREA\x10\x15\x12\x0e\n\nTRANSITION\x10\x16\x12\x0c\n\x08OBSTACLE\x10\x17\x12\x13\n\x0f\x42USH_GREEN_BELT\x10\x18\x12\x0f\n\x0b\x42RIDGE_EDGE\x10\x19\"a\n\tCrossType\x12\x15\n\x11VEHICLE_CAN_CROSS\x10\x01\x12\x15\n\x11\x42ICYCLE_CAN_CROSS\x10\x02\x12\x13\n\x0fHUMAN_CAN_CROSS\x10\x03\x12\x11\n\rCAN_NOT_CROSS\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyhdmap.proto.hdmap_lib.proto.object_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECT']._serialized_start=191
  _globals['_OBJECT']._serialized_end=1001
  _globals['_OBJECT_TYPE']._serialized_start=425
  _globals['_OBJECT_TYPE']._serialized_end=902
  _globals['_OBJECT_CROSSTYPE']._serialized_start=904
  _globals['_OBJECT_CROSSTYPE']._serialized_end=1001
# @@protoc_insertion_point(module_scope)
