#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class cumulative_plot_child:
    fluent_name = ...
    child_names = ...
    option = ...
    zones = ...
    split_direction = ...
    number_of_divisions = ...
    force_direction = ...
    moment_center = ...
    moment_axis = ...
    x_axis_quantity = ...
    compute_from_stats = ...
    name = ...
    axes = ...
    curves = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

