#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class plane_surface_child:
    fluent_name = ...
    child_names = ...
    name = ...
    method = ...
    x = ...
    y = ...
    z = ...
    point_vector = ...
    point_normal = ...
    surface_aligned_normal = ...
    p0 = ...
    p1 = ...
    p2 = ...
    bounded = ...
    sample_point = ...
    edges = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

