
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-05T12:40:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "85e02dd9d4c3b0e8b81d810b3ffd91fcd5cb8a7e",
 "version": "1.0.66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
