
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-05T12:21:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef25d00e50bb1885909041c7a75171ebc4cb6ed8",
 "version": "0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
