from enum import Enum

class HTTPMethods(str, Enum):
    '''Available HTTP methods.'''

    POST = 'POST'
    GET = 'GET'

class Board(Enum):
    A = "a"
    B = "b"
    C = "c"
    D = "d"
    E = "e"
    F = "f"
    G = "g"
    GIF = "gif"
    H = "h"
    HR = "hr"
    K = "k"
    M = "m"
    O = "o"
    P = "p"
    R = "r"
    S = "s"
    T = "t"
    U = "u"
    V = "v"
    VG = "vg"
    VM = "vm"
    VMG = "vmg"
    VR = "vr"
    VRPG = "vrpg"
    VST = "vst"
    W = "w"
    WG = "wg"

class Category(Enum):
    I = "i"
    IC = "ic"

class Special(Enum):
    R9K = "r9k"
    S4S = "s4s"
    VIP = "vip"
    QA = "qa"

class Other(Enum):
    CM = "cm"
    HM = "hm"
    LGBT = "lgbt"
    Y = "y"

class International(Enum):
    _3 = "3"
    ACO = "aco"
    ADV = "adv"
    AN = "an"
    BANT = "bant"
    BIZ = "biz"
    CGL = "cgl"
    CK = "ck"
    CO = "co"
    DIY = "diy"
    FA = "fa"
    FIT = "fit"
    GD = "gd"
    HC = "hc"
    HIS = "his"
    INT = "int"
    JP = "jp"
    LIT = "lit"
    MLP = "mlp"
    MU = "mu"
    N = "n"
    NEWS = "news"
    OUT = "out"
    PO = "po"
    POL = "pol"
    PW = "pw"
    QST = "qst"
    SCI = "sci"
    SOC = "soc"
    SP = "sp"
    TG = "tg"
    TOY = "toy"
    TRV = "trv"
    TV = "tv"
    VP = "vp"
    VT = "vt"
    WSG = "wsg"
    WSR = "wsr"
    X = "x"
    XS = "xs"