from typing import Any, Dict, List, Optional

class SevcoAPI:
    org_id: Optional[str]

    def __init__(self, profile_name: str) -> None: ...
    def set_org_id(self, org_id: str) -> None: ...
    def get_integration_configs(self) -> List[Dict[str, Any]]: ...
    def user_orgs(self) -> List[Dict[str, Any]]: ...
    def add_tags(
        self, org_id: str, asset_ids: List[str], tag_name: str, tag_value: Optional[str]
    ) -> None: ...
    def query_from_string(self, query_str: str) -> List[Dict[str, Any]]: ...
    def query_from_dict(self, query_dict: Dict) -> List[Dict[str, Any]]: ...

# class SevcoQuery:
# class SevcoVulnQuery:
