import interscript
import regex as re
interscript.stdlib.define_map("alalc-sin-Sinh-Latn-1997")
interscript.stdlib.add_map_alias("alalc-sin-Sinh-Latn-1997", "sinh_chars_1", "ා")
interscript.stdlib.add_map_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1", "[ාැෑිීුූෘෲෟෳෙේෛොෝෞ්]")
def _stage_main(s):
    s = re.compile("්(?=[කඛගඝඞ])", re.MULTILINE).sub("ṅ", s)
    s = re.compile("්(?=[චඡජඣඤ])", re.MULTILINE).sub("ñ", s)
    s = re.compile("්(?=[ටඨඩඪණ])", re.MULTILINE).sub("ṇ", s)
    s = re.compile("්(?=[තථදධන])", re.MULTILINE).sub("n", s)
    s = re.compile("ක(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("k", s)
    s = re.compile("ඛ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("ග(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ඝ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("ඞ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("ච(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("c", s)
    s = re.compile("ඡ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("ජ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("j", s)
    s = re.compile("ඣ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("ඤ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ට(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ඨ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("ඩ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("ඪ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ණ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ත(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("t", s)
    s = re.compile("ථ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("th", s)
    s = re.compile("ද(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("d", s)
    s = re.compile("ධ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("න(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("n", s)
    s = re.compile("ප(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("p", s)
    s = re.compile("ඵ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("බ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("b", s)
    s = re.compile("භ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("ම(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("m", s)
    s = re.compile("ය(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("y", s)
    s = re.compile("ර(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("r", s)
    s = re.compile("ල(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("l", s)
    s = re.compile("ළ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ḷ", s)
    s = re.compile("ව(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("v", s)
    s = re.compile("ශ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ś", s)
    s = re.compile("ෂ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ṣ", s)
    s = re.compile("ස(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("s", s)
    s = re.compile("හ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("h", s)
    s = re.compile("ඟ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ṅg", s)
    s = re.compile("ඦ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ñj", s)
    s = re.compile("ඬ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ṇḍ", s)
    s = re.compile("ඳ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("nd", s)
    s = re.compile("ඹ(?="+interscript.stdlib.get_alias_re("alalc-sin-Sinh-Latn-1997", "sinh_chars_1")+")", re.MULTILINE).sub("ṃb", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_1965642168950927639)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("alalc-sin-Sinh-Latn-1997", "main", _stage_main)
_PTREE_1965642168950927639 = {3461:{None:"a"},3462:{None:"ā"},3463:{None:"ă"},3464:{None:"â"},3465:{None:"i"},3466:{None:"ī"},3467:{None:"u"},3468:{None:"ū"},3469:{None:"ṛ"},3470:{None:"ṝ"},3471:{None:"ḷ"},3472:{None:"ḹ"},3473:{None:"e"},3474:{None:"ē"},3475:{None:"ai"},3476:{None:"o"},3477:{None:"ō"},3478:{None:"au"},3535:{None:"ā"},3536:{None:"ă"},3537:{None:"â"},3538:{None:"i"},3539:{None:"ī"},3540:{None:"u"},3542:{None:"ū"},3544:{None:"ṛ"},3570:{None:"ṝ"},3551:{None:"ḷ"},3571:{None:"ḹ"},3545:{None:"e"},3546:{None:"ē"},3547:{None:"ai"},3548:{None:"o"},3549:{None:"ō"},3550:{None:"au"},3482:{None:"ka"},3483:{None:"kha"},3484:{None:"ga"},3485:{None:"gha"},3486:{None:"ṅa"},3488:{None:"ca"},3489:{None:"cha"},3490:{None:"ja"},3491:{None:"jha"},3492:{None:"ña"},3495:{None:"ṭa"},3496:{None:"ṭha"},3497:{None:"ḍa"},3498:{None:"ḍha"},3499:{None:"ṇa"},3501:{None:"ta"},3502:{None:"tha"},3503:{None:"da"},3504:{None:"dha"},3505:{None:"na"},3508:{None:"pa"},3509:{None:"pha"},3510:{None:"ba"},3511:{None:"bha"},3512:{None:"ma"},3514:{None:"ya"},3515:{None:"ra"},3517:{None:"la"},3525:{None:"ḷa"},3520:{None:"va"},3521:{None:"śa"},3522:{None:"ṣa"},3523:{None:"sa"},3524:{None:"ha"},3459:{None:"ḥ"},3458:{None:"ṃ"},3558:{None:"0"},3559:{None:"1"},3560:{None:"2"},3561:{None:"3"},3562:{None:"4"},3563:{None:"5"},3564:{None:"6"},3565:{None:"7"},3566:{None:"8"},3567:{None:"9"},8205:{None:""},8204:{None:""},3530:{None:""},3487:{None:"ṅga"},3494:{None:"ñja"},3500:{None:"ṇḍa"},3507:{None:"nda"},3513:{None:"ṃba"}}
