import interscript
import regex as re
interscript.stdlib.define_map("bgnpcgn-per-Arab-Latn-1958")
def _stage_main(s):
    s = interscript.stdlib.parallel_regexp_gsub(s, *_PRE_2650466850392954534)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")(?<!"+interscript.stdlib.aliases["boundary"]+"[‘’'\\-])[a-￿]", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile("\\ Ol", re.MULTILINE).sub(" ol", s)
    return s

interscript.stdlib.add_map_stage("bgnpcgn-per-Arab-Latn-1958", "main", _stage_main)
_PRE_2650466850392954534 = ["(?P<_0>(?<!"+interscript.stdlib.aliases["boundary"]+")اللَّه)|(?P<_1>"+interscript.stdlib.aliases["space"]+"آبَاد)|(?P<_2>اللَّه)|(?P<_3>"+interscript.stdlib.aliases["boundary"]+"التّ?)|(?P<_4>"+interscript.stdlib.aliases["boundary"]+"الثّ?)|(?P<_5>"+interscript.stdlib.aliases["boundary"]+"الدّ?)|(?P<_6>"+interscript.stdlib.aliases["boundary"]+"الذّ?)|(?P<_7>"+interscript.stdlib.aliases["boundary"]+"الرّ?)|(?P<_8>"+interscript.stdlib.aliases["boundary"]+"الزّ?)|(?P<_9>"+interscript.stdlib.aliases["boundary"]+"السّ?)|(?P<_10>"+interscript.stdlib.aliases["boundary"]+"الشّ?)|(?P<_11>"+interscript.stdlib.aliases["boundary"]+"الصّ?)|(?P<_12>"+interscript.stdlib.aliases["boundary"]+"الضّ?)|(?P<_13>"+interscript.stdlib.aliases["boundary"]+"الطّ?)|(?P<_14>"+interscript.stdlib.aliases["boundary"]+"الظّ?)|(?P<_15>"+interscript.stdlib.aliases["boundary"]+"اللّ?)|(?P<_16>"+interscript.stdlib.aliases["boundary"]+"النّ?)|(?P<_17>"+interscript.stdlib.aliases["space"]+""+interscript.stdlib.aliases["boundary"]+"ال)|(?P<_18>َ(?=a[h\\|t]))|(?P<_19>َ[ي\\|ی]ْ)|(?P<_20>ِ[ي\\|ی]ْ)|(?P<_21>ِيّ)|(?P<_22>[ي\\|ی]ِ"+interscript.stdlib.aliases["boundary"]+")|(?P<_23>"+interscript.stdlib.aliases["boundary"]+"ال)|(?P<_24>َ(?=ة))|(?P<_25>َا)|(?P<_26>ىٰ)|(?P<_27>"+interscript.stdlib.aliases["boundary"]+"آ)|(?P<_28>ِ[ي\\|ی])|(?P<_29>ُو)|(?P<_30>َو)|(?P<_31>(?<=[ي\\|ه])[ٔ\\|ٴ])|(?P<_32>ِ"+interscript.stdlib.aliases["boundary"]+")|(?P<_33>بّ)|(?P<_34>تّ)|(?P<_35>ثّ)|(?P<_36>جّ)|(?P<_37>حّ)|(?P<_38>خّ)|(?P<_39>دّ)|(?P<_40>ذّ)|(?P<_41>رّ)|(?P<_42>زّ)|(?P<_43>سّ)|(?P<_44>شّ)|(?P<_45>صّ)|(?P<_46>ضّ)|(?P<_47>طّ)|(?P<_48>ظّ)|(?P<_49>غّ)|(?P<_50>فّ)|(?P<_51>قّ)|(?P<_52>كّ)|(?P<_53>لّ)|(?P<_54>مّ)|(?P<_55>نّ)|(?P<_56>هّ)|(?P<_57>وّ)|(?P<_58>يّ)|(?P<_59>"+interscript.stdlib.aliases["boundary"]+"ا)|(?P<_60>َ)|(?P<_61>ِ)|(?P<_62>ُ)|(?P<_63>آ)|(?P<_64>ْ)|(?P<_65>[ٔ\\|ٴ])|(?P<_66>ٙ)|(?P<_67>ة)|(?P<_68>ﷲ)|(?P<_69>ء)|(?P<_70>ئ)|(?P<_71>أ)|(?P<_72>إ)|(?P<_73>ا)|(?P<_74>ب)|(?P<_75>پ)|(?P<_76>ت)|(?P<_77>ث)|(?P<_78>ج)|(?P<_79>چ)|(?P<_80>ح)|(?P<_81>خ)|(?P<_82>د)|(?P<_83>ذ)|(?P<_84>ر)|(?P<_85>ز)|(?P<_86>ژ)|(?P<_87>س)|(?P<_88>ش)|(?P<_89>ص)|(?P<_90>ض)|(?P<_91>ط)|(?P<_92>ظ)|(?P<_93>ع)|(?P<_94>غ)|(?P<_95>ف)|(?P<_96>ق)|(?P<_97>ك)|(?P<_98>ک)|(?P<_99>گ)|(?P<_100>ل)|(?P<_101>م)|(?P<_102>ن)|(?P<_103>ه)|(?P<_104>و)|(?P<_105>ي)|(?P<_106>ى)|(?P<_107>ې)|(?P<_108>ۍ)", ["ollāh","ābād","Allāh","at t","as̄ s̄","ad d","az̄ z̄","ar r","az z","as s","ash sh","aş ş","aẕ ẕ","aţ ţ","az̧ z̧","al l","an n"," ol ","","ey","ey","īy","-ye","al ","","ā","á","ā","ī","ū","ow","-ye","-e","bb","tt","s̄s̄","jj","ḩḩ","kh","dd","z̄z̄","rr","zz","ss","sh","şş","ẕẕ","ţţ","z̧z̧","gh","ff","qq","kk","ll","mm","nn","hh","vv","yy","","a","e","o","’ā","","-e","ê","eh","Allāh","’","’","","","ā","b","p","t","s̄","j","ch","ḩ","kh","d","z̄","r","z","zh","s","sh","ş","ẕ","ţ","z̧","‘","gh","f","q","k","k","g","l","m","n","h","v","y","y","ē","êy"]]
