import interscript
import regex as re
interscript.load_map("var-kor")
interscript.load_map("var-kor-Hang-Hang-jamo")
interscript.stdlib.define_map("moct-kor-Hang-Latn-2000")
interscript.stdlib.add_map_alias("moct-kor-Hang-Latn-2000", "double_cons_jamo", "ᄁ")
interscript.stdlib.add_map_alias_re("moct-kor-Hang-Latn-2000", "double_cons_jamo", "[ᄁᄄᄈᄍᄊ]")
interscript.stdlib.add_map_alias("moct-kor-Hang-Latn-2000", "aspirated_cons_jamo", "ᄏ")
interscript.stdlib.add_map_alias_re("moct-kor-Hang-Latn-2000", "aspirated_cons_jamo", "[ᄏᄐᄑᄎ]")
def _stage_main(s):
    s = re.compile("(?<!(?:"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.aliases["space"]+"))"+interscript.stdlib.aliases["none"]+"(?="+interscript.stdlib.aliases["digit"]+")", re.MULTILINE).sub(interscript.stdlib.aliases["space"], s)
    s = re.compile("1", re.MULTILINE).sub("일", s)
    s = re.compile("2", re.MULTILINE).sub("이", s)
    s = re.compile("3", re.MULTILINE).sub("삼", s)
    s = re.compile("4", re.MULTILINE).sub("사", s)
    s = re.compile("5", re.MULTILINE).sub("오", s)
    s = re.compile("6", re.MULTILINE).sub("육", s)
    s = re.compile("7", re.MULTILINE).sub("칠", s)
    s = re.compile("8", re.MULTILINE).sub("팔", s)
    s = re.compile("9", re.MULTILINE).sub("구", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["line_start"]+")"+interscript.stdlib.aliases["none"]+"(?=[도시군구읍면리동가]"+interscript.stdlib.aliases["line_end"]+")", re.MULTILINE).sub("-", s)
    s = interscript.transliterate("var-kor-Hang-Hang-jamo", s, "main")
    s = re.compile(""+interscript.stdlib.aliases["line_start"]+"", re.MULTILINE).sub(interscript.stdlib.aliases["space"], s)
    s = re.compile(""+interscript.stdlib.aliases["line_end"]+"", re.MULTILINE).sub(interscript.stdlib.aliases["space"], s)
    s = re.compile("ᆩᄋ", re.MULTILINE).sub("ᆨᄁ", s)
    s = re.compile("ᆩ", re.MULTILINE).sub("ᆨ", s)
    s = re.compile("ᆪᄋ", re.MULTILINE).sub("ᆨᄉ", s)
    s = re.compile("ᆪ", re.MULTILINE).sub("ᆨ", s)
    s = re.compile("ᆬᄋ", re.MULTILINE).sub("ᆫᄌ", s)
    s = re.compile("ᆬ", re.MULTILINE).sub("ᆫ", s)
    s = re.compile("ᆭᄀ", re.MULTILINE).sub("ᆫᄏ", s)
    s = re.compile("ᆭᄃ", re.MULTILINE).sub("ᆫᄐ", s)
    s = re.compile("ᆭᄇ", re.MULTILINE).sub("ᆫᄑ", s)
    s = re.compile("ᆭᄌ", re.MULTILINE).sub("ᆫᄎ", s)
    s = re.compile("ᆭ", re.MULTILINE).sub("ᆫ", s)
    s = re.compile("ᆮ(?=[ᄀᄁᄂᄃᄄᄅᄆᄇᄈᄉᄊᄌᄍᄎᄏᄐᄑᄒ])", re.MULTILINE).sub("ᆺ", s)
    s = re.compile("ᆳᄋ", re.MULTILINE).sub("ᆯᄉ", s)
    s = re.compile("ᆳ", re.MULTILINE).sub("ᆯ", s)
    s = re.compile("ᆴᄋ", re.MULTILINE).sub("ᆯᄐ", s)
    s = re.compile("ᆴ", re.MULTILINE).sub("ᆯ", s)
    s = re.compile("ᆵᄋ", re.MULTILINE).sub("ᆯᄑ", s)
    s = re.compile("ᆵ(?=[ᄃᄄᄐ])", re.MULTILINE).sub("ᆯ", s)
    s = re.compile("ᆵ", re.MULTILINE).sub("ᄇ", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_2278131638105834473)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_630528285189878506)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄀ", re.MULTILINE).sub("g", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄂ", re.MULTILINE).sub("n", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄃ", re.MULTILINE).sub("d", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄅ", re.MULTILINE).sub("r", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄆ", re.MULTILINE).sub("m", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄇ", re.MULTILINE).sub("b", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄉ", re.MULTILINE).sub("s", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄋ", re.MULTILINE).sub("", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄌ", re.MULTILINE).sub("j", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄎ", re.MULTILINE).sub("ch", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄏ", re.MULTILINE).sub("k", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄐ", re.MULTILINE).sub("t", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄑ", re.MULTILINE).sub("p", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|\\-))ᄒ", re.MULTILINE).sub("h", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"))ᄁ", re.MULTILINE).sub("kk", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"))ᄄ", re.MULTILINE).sub("tt", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"))ᄈ", re.MULTILINE).sub("pp", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"))ᄊ", re.MULTILINE).sub("ss", s)
    s = re.compile("(?<=(?:"+interscript.stdlib.aliases["alpha"]+"|"+interscript.stdlib.aliases["digit"]+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"))ᄍ", re.MULTILINE).sub("jj", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_2373484365189070933)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄀ", re.MULTILINE).sub("g", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄂ", re.MULTILINE).sub("n", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄃ", re.MULTILINE).sub("d", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄅ(?=[ᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄅ", re.MULTILINE).sub("n", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄆ", re.MULTILINE).sub("m", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄇ", re.MULTILINE).sub("b", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄉ", re.MULTILINE).sub("s", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄋ", re.MULTILINE).sub("", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄌ", re.MULTILINE).sub("j", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄎ", re.MULTILINE).sub("ch", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄏ", re.MULTILINE).sub("k", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄐ", re.MULTILINE).sub("t", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄑ", re.MULTILINE).sub("p", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄒ", re.MULTILINE).sub("h", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄁ", re.MULTILINE).sub("kk", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄭ", re.MULTILINE).sub("kk", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄄ", re.MULTILINE).sub("tt", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄯ", re.MULTILINE).sub("tt", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄈ", re.MULTILINE).sub("pp", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄲ", re.MULTILINE).sub("pp", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄊ", re.MULTILINE).sub("ss", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄍ", re.MULTILINE).sub("jj", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["space"]+")ᄶ", re.MULTILINE).sub("jj", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_2467255722448575501)
    s = re.compile("ᆨ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("k", s)
    s = re.compile("ᆫ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("n", s)
    s = re.compile("ᆮ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("t", s)
    s = re.compile("ᆯ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("l", s)
    s = re.compile("ᆷ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("m", s)
    s = re.compile("ᆸ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("p", s)
    s = re.compile("ᆺ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("t", s)
    s = re.compile("ᆼ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("ng", s)
    s = re.compile("ᆽ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("t", s)
    s = re.compile("ᆾ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("t", s)
    s = re.compile("ᆿ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("k", s)
    s = re.compile("ᇀ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("t", s)
    s = re.compile("ᇁ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("p", s)
    s = re.compile("ᆰ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("k", s)
    s = re.compile("ᆲ(?=(?:"+interscript.stdlib.aliases["space"]+"|\\-))", re.MULTILINE).sub("p", s)
    s = re.compile(""+interscript.stdlib.aliases["line_start"]+""+interscript.stdlib.aliases["space"]+"", re.MULTILINE).sub(interscript.stdlib.aliases["none"], s)
    s = re.compile(""+interscript.stdlib.aliases["space"]+""+interscript.stdlib.aliases["line_end"]+"", re.MULTILINE).sub(interscript.stdlib.aliases["none"], s)
    s = interscript.functions.title_case(s, {})
    return s

interscript.stdlib.add_map_stage("moct-kor-Hang-Latn-2000", "main", _stage_main)
_PTREE_2278131638105834473 = {4534:{4352:{None:"ᆯᄏ"},4355:{None:"ᆯᄐ"},4359:{None:"ᆯᄑ"},4364:{None:"ᆯᄎ"},None:"ᆯ"},4537:{4363:{None:"ᄇᄉ"},None:"ᄇ"},4539:{4363:{None:"ᆺᄊ"},None:"ᆺ"},4541:{4363:{None:"ᆺᄌ"},None:"ᆺ"},4542:{4363:{None:"ᆺᄎ"},None:"ᆺ"},4543:{4363:{None:"ᆨᄏ"},None:"ᆨ"},4544:{4363:{None:"ᆺᄐ"},None:"ᆺ"},4545:{4363:{None:"ᆸᄑ"},None:"ᆸ"},4546:{4352:{None:"ᄏ"},4355:{None:"ᄐ"},4359:{None:"ᄑ"},4364:{None:"ᄎ"},None:""}}
_PTREE_630528285189878506 = {4526:{4363:{None:"d"}},4520:{4352:{None:"kg"},4354:{None:"ngn"},4355:{None:"kd"},4357:{None:"ngn"},4358:{None:"ngm"},4359:{None:"kb"},4361:{None:"ks"},4363:{None:"g"},4364:{None:"kj"},4366:{None:"kch"},4367:{None:"kk"},4368:{None:"kt"},4369:{None:"kp"},4370:{None:"kh"},4353:{None:"kkk"},4356:{None:"ktt"},4360:{None:"kpp"},4362:{None:"kss"},4365:{None:"kjj"}},4523:{4352:{None:"ng"},4354:{None:"nn"},4355:{None:"nd"},4357:{None:"ll"},4358:{None:"nm"},4359:{None:"nb"},4361:{None:"ns"},4363:{None:"n"},4364:{None:"nj"},4366:{None:"nch"},4367:{None:"nk"},4368:{None:"nt"},4369:{None:"np"},4370:{None:"nh"},4353:{None:"nkk"},4356:{None:"ntt"},4360:{None:"npp"},4362:{None:"nss"},4365:{None:"njj"}},4527:{4352:{None:"lg"},4354:{None:"ll"},4355:{None:"ld"},4357:{None:"ll"},4358:{None:"lm"},4359:{None:"lb"},4361:{None:"ls"},4363:{None:"r"},4364:{None:"lj"},4366:{None:"lch"},4367:{None:"lk"},4368:{None:"lt"},4369:{None:"lp"},4370:{None:"rh"},4353:{None:"lkk"},4356:{None:"ltt"},4360:{None:"lpp"},4362:{None:"lss"},4365:{None:"ljj"}},4535:{4352:{None:"mg"},4354:{None:"mn"},4355:{None:"md"},4357:{None:"mn"},4358:{None:"mm"},4359:{None:"mb"},4361:{None:"ms"},4363:{None:"m"},4364:{None:"mj"},4366:{None:"mch"},4367:{None:"mk"},4368:{None:"mt"},4369:{None:"mp"},4370:{None:"mh"},4353:{None:"mkk"},4356:{None:"mtt"},4360:{None:"mpp"},4362:{None:"mss"},4365:{None:"mjj"}},4536:{4352:{None:"pg"},4354:{None:"mn"},4355:{None:"pd"},4357:{None:"mn"},4358:{None:"mm"},4359:{None:"pb"},4361:{None:"ps"},4363:{None:"b"},4364:{None:"pj"},4366:{None:"pch"},4367:{None:"pk"},4368:{None:"pt"},4369:{None:"pp"},4370:{None:"ph"},4353:{None:"pkk"},4356:{None:"ptt"},4360:{None:"ppp"},4362:{None:"pss"},4365:{None:"pjj"}},4538:{4352:{None:"tg"},4354:{None:"nn"},4355:{None:"td"},4357:{None:"nn"},4358:{None:"nm"},4359:{None:"tb"},4361:{None:"ts"},4363:{None:"s"},4364:{None:"tj"},4366:{None:"tch"},4367:{None:"tk"},4368:{None:"tt"},4369:{None:"tp"},4370:{None:"th"},4353:{None:"tkk"},4356:{None:"ttt"},4360:{None:"tpp"},4362:{None:"tss"},4365:{None:"tjj"}},4540:{4352:{None:"ngg"},4354:{None:"ngn"},4355:{None:"ngd"},4357:{None:"ngn"},4358:{None:"ngm"},4359:{None:"ngb"},4361:{None:"ngs"},4363:{None:"ng"},4364:{None:"ngj"},4366:{None:"ngch"},4367:{None:"ngk"},4368:{None:"ngt"},4369:{None:"ngp"},4370:{None:"ngh"},4353:{None:"ngkk"},4356:{None:"ngtt"},4360:{None:"ngpp"},4362:{None:"ngss"},4365:{None:"ngjj"}}}
_PTREE_2373484365189070933 = {4528:{4352:{None:"lg"},4354:{None:"ngn"},4355:{None:"kd"},4357:{None:"ngn"},4358:{None:"ngm"},4359:{None:"kb"},4361:{None:"ks"},4363:{None:"lg"},4364:{None:"kj"},4366:{None:"kch"},4367:{None:"lk"},4368:{None:"kt"},4369:{None:"kp"},4370:{None:"lk"},4353:{None:"lkk"},4356:{None:"ktt"},4360:{None:"kpp"},4362:{None:"kss"},4365:{None:"kjj"}},4529:{4352:{None:"mg"},4354:{None:"mn"},4355:{None:"md"},4357:{None:"mn"},4358:{None:"lm"},4359:{None:"mb"},4361:{None:"ms"},4363:{None:"lm"},4364:{None:"mj"},4366:{None:"mch"},4367:{None:"mk"},4368:{None:"mt"},4369:{None:"mp"},4370:{None:"mh"},4353:{None:"mkk"},4356:{None:"mtt"},4360:{None:"mpp"},4362:{None:"mss"},4365:{None:"mjj"}},4530:{4352:{None:"pg"},4354:{None:"mn"},4355:{None:"pd"},4357:{None:"mn"},4358:{None:"mm"},4359:{None:"lb"},4361:{None:"ps"},4363:{None:"lb"},4364:{None:"pj"},4366:{None:"pch"},4367:{None:"pk"},4368:{None:"pt"},4369:{None:"lp"},4370:{None:"lp"},4353:{None:"pkk"},4356:{None:"ptt"},4360:{None:"lpp"},4362:{None:"pss"},4365:{None:"pjj"}}}
_PTREE_2467255722448575501 = {4449:{None:"a"},4451:{None:"ya"},4453:{None:"eo"},4455:{None:"yeo"},4457:{None:"o"},4461:{None:"yo"},4462:{None:"u"},4466:{None:"yu"},4467:{None:"eu"},4469:{None:"i"},4450:{None:"ae"},4452:{None:"yae"},4454:{None:"e"},4456:{None:"ye"},4460:{None:"oe"},4465:{None:"wi"},4468:{None:"ui"},4458:{None:"wa"},4463:{None:"wo"},4459:{None:"wae"},4464:{None:"we"}}
