import interscript
import regex as re
interscript.stdlib.define_map("mv-div-Thaa-Latn-1987")
def _stage_main(s):
    s = re.compile("އް(?=[ހ])", re.MULTILINE).sub("h", s)
    s = re.compile("އް(?=[ށ])", re.MULTILINE).sub("h", s)
    s = re.compile("އް(?=[ނ])", re.MULTILINE).sub("n", s)
    s = re.compile("އް(?=[ރ])", re.MULTILINE).sub("r", s)
    s = re.compile("އް(?=[ބ])", re.MULTILINE).sub("b", s)
    s = re.compile("އް(?=[ޅ])", re.MULTILINE).sub("h", s)
    s = re.compile("އް(?=[ކ])", re.MULTILINE).sub("k", s)
    s = re.compile("އް(?=[ވ])", re.MULTILINE).sub("v", s)
    s = re.compile("އް(?=[މ])", re.MULTILINE).sub("m", s)
    s = re.compile("އް(?=[ފ])", re.MULTILINE).sub("f", s)
    s = re.compile("އް(?=[ދ])", re.MULTILINE).sub("h", s)
    s = re.compile("އް(?=[ތ])", re.MULTILINE).sub("h", s)
    s = re.compile("އް(?=[ލ])", re.MULTILINE).sub("l", s)
    s = re.compile("އް(?=[ގ])", re.MULTILINE).sub("g", s)
    s = re.compile("އް(?=[ޏ])", re.MULTILINE).sub("h", s)
    s = re.compile("އް(?=[ސ])", re.MULTILINE).sub("s", s)
    s = re.compile("އް(?=[ޑ])", re.MULTILINE).sub("d", s)
    s = re.compile("އް(?=[ޖ])", re.MULTILINE).sub("j", s)
    s = re.compile("އް(?=[ޗ])", re.MULTILINE).sub("h", s)
    s = re.compile("އް(?=[ޒ])", re.MULTILINE).sub("z", s)
    s = re.compile("އް(?=[ޓ])", re.MULTILINE).sub("t", s)
    s = re.compile("އް(?=[ޕ])", re.MULTILINE).sub("p", s)
    s = re.compile("އް(?=[ޔ])", re.MULTILINE).sub("y", s)
    s = re.compile("ށް(?=[ހ])", re.MULTILINE).sub("h", s)
    s = re.compile("ށް(?=[ށ])", re.MULTILINE).sub("h", s)
    s = re.compile("ށް(?=[ނ])", re.MULTILINE).sub("n", s)
    s = re.compile("ށް(?=[ރ])", re.MULTILINE).sub("r", s)
    s = re.compile("ށް(?=[ބ])", re.MULTILINE).sub("b", s)
    s = re.compile("ށް(?=[ޅ])", re.MULTILINE).sub("h", s)
    s = re.compile("ށް(?=[ކ])", re.MULTILINE).sub("k", s)
    s = re.compile("ށް(?=[ވ])", re.MULTILINE).sub("v", s)
    s = re.compile("ށް(?=[މ])", re.MULTILINE).sub("m", s)
    s = re.compile("ށް(?=[ފ])", re.MULTILINE).sub("f", s)
    s = re.compile("ށް(?=[ދ])", re.MULTILINE).sub("h", s)
    s = re.compile("ށް(?=[ތ])", re.MULTILINE).sub("h", s)
    s = re.compile("ށް(?=[ލ])", re.MULTILINE).sub("l", s)
    s = re.compile("ށް(?=[ގ])", re.MULTILINE).sub("g", s)
    s = re.compile("ށް(?=[ޏ])", re.MULTILINE).sub("h", s)
    s = re.compile("ށް(?=[ސ])", re.MULTILINE).sub("s", s)
    s = re.compile("ށް(?=[ޑ])", re.MULTILINE).sub("d", s)
    s = re.compile("ށް(?=[ޖ])", re.MULTILINE).sub("j", s)
    s = re.compile("ށް(?=[ޗ])", re.MULTILINE).sub("h", s)
    s = re.compile("ށް(?=[ޒ])", re.MULTILINE).sub("z", s)
    s = re.compile("ށް(?=[ޓ])", re.MULTILINE).sub("t", s)
    s = re.compile("ށް(?=[ޕ])", re.MULTILINE).sub("p", s)
    s = re.compile("ށް(?=[ޔ])", re.MULTILINE).sub("y", s)
    s = re.compile("އް(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("h", s)
    s = re.compile("ށް(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("h", s)
    s = re.compile("ނ(?!=[ަާިީުޫެޭޮޯް])", re.MULTILINE).sub("n’", s)
    s = re.compile("ތ(?=ް)", re.MULTILINE).sub("iy", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_2693583207270223881)
    return s

interscript.stdlib.add_map_stage("mv-div-Thaa-Latn-1987", "main", _stage_main)
_PTREE_2693583207270223881 = {1958:{None:"a"},1959:{None:"aa"},1960:{None:"i"},1961:{None:"ee"},1962:{None:"u"},1963:{None:"oo"},1964:{None:"e"},1965:{None:"ey"},1966:{None:"o"},1967:{None:"oa"},1968:{None:""},1920:{None:"h"},1921:{None:"sh"},1922:{None:"n"},1923:{None:"r"},1924:{None:"b"},1925:{None:"lh"},1926:{None:"k"},1927:{None:""},1928:{None:"v"},1929:{None:"m"},1930:{None:"f"},1931:{None:"dh"},1932:{None:"th"},1933:{None:"l"},1934:{None:"g"},1935:{None:"gn"},1936:{None:"s"},1937:{None:"d"},1942:{None:"j"},1943:{None:"ch"},1938:{None:"z"},1939:{None:"t"},1941:{None:"p"},1940:{None:"y"}}
