import interscript
import regex as re
interscript.stdlib.define_map("alalc-hin-Deva-Latn-1997")
interscript.stdlib.add_map_alias("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster", "ा")
interscript.stdlib.add_map_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster", "[ािीुूृॄॅेैॉोौ\\ ्]")
def _stage_main(s):
    s = re.compile("(क=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("k", s)
    s = re.compile("(क़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("q", s)
    s = re.compile("(ख=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("(ख़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("(ग=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("g", s)
    s = re.compile("(ग़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("(घ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("(ङ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("(च=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("c", s)
    s = re.compile("(छ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("(ज=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("j", s)
    s = re.compile("(ज़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("j", s)
    s = re.compile("(झ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("(ञ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("(ट=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("(ट़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("t̤", s)
    s = re.compile("(ठ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("(ड=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("(ड़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ṛ", s)
    s = re.compile("(ड़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ṛ", s)
    s = re.compile("(ढ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("(ढ़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ṛh", s)
    s = re.compile("(ण=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("(त=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("t", s)
    s = re.compile("(थ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("th", s)
    s = re.compile("(द=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("d", s)
    s = re.compile("(ध=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("(न=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("n", s)
    s = re.compile("(प=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("p", s)
    s = re.compile("(फ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("(फ़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("(ब=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("b", s)
    s = re.compile("(भ=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("(म=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("m", s)
    s = re.compile("(य=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("y", s)
    s = re.compile("(र=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("r", s)
    s = re.compile("(ल=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("l", s)
    s = re.compile("(व=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("v", s)
    s = re.compile("(श=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("ś", s)
    s = re.compile("(ष=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("sh", s)
    s = re.compile("(स=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("s", s)
    s = re.compile("(स़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("s̤", s)
    s = re.compile("(ह=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("h", s)
    s = re.compile("(ह़=?)(?="+interscript.stdlib.get_alias_re("alalc-hin-Deva-Latn-1997", "hin_cons_or_conscluster")+")", re.MULTILINE).sub("h", s)
    s = re.compile("ं(?=[कक़खख़गग़घङ])", re.MULTILINE).sub("ṅ", s)
    s = re.compile("ं(?=[चछजज़झञ])", re.MULTILINE).sub("ñ", s)
    s = re.compile("ं(?=[टट़ठडड़ढढ़ण])", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ं(?=[तथदधन])", re.MULTILINE).sub("n", s)
    s = re.compile("(?<=)ँ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("m̐", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_2824714754145040188)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("alalc-hin-Deva-Latn-1997", "main", _stage_main)
_PTREE_2824714754145040188 = {2309:{None:"a",2376:{None:"ăi"}},2310:{None:"ā"},2311:{None:"i"},2312:{None:"ī"},2313:{None:"u"},2314:{None:"ū"},2315:{None:"ṛ"},2400:{None:"ṝ"},2316:{None:"ḷ"},2419:{None:"ĕ"},2319:{None:"e"},2418:{None:"ê"},2320:{None:"ai"},2322:{None:"ŏ"},2323:{None:"o"},2321:{None:"ô"},2324:{None:"ău"},2325:{None:"ka"},2392:{None:"qa"},2326:{None:"kha"},2393:{None:"kha"},2327:{None:"ga"},2394:{None:"gha"},2328:{None:"gha"},2329:{None:"ṅa"},2330:{None:"ca"},2331:{None:"cha"},2332:{None:"ja"},2395:{None:"ja"},2333:{None:"jha"},2334:{None:"ña"},2335:{None:"ṭa",2364:{None:"t̤a"}},2336:{None:"ṭha"},2337:{None:"ḍa",2364:{None:"ṛa"}},2396:{None:"ṛa"},2338:{None:"ḍha"},2397:{None:"ṛha"},2339:{None:"ṇa"},2340:{None:"ta"},2341:{None:"tha"},2342:{None:"da"},2343:{None:"dha"},2344:{None:"na"},2346:{None:"pa"},2347:{None:"pha"},2398:{None:"pha"},2348:{None:"ba"},2349:{None:"bha"},2350:{None:"ma"},2351:{None:"ya"},2352:{None:"ra"},2354:{None:"la"},2357:{None:"va"},2358:{None:"śa"},2359:{None:"sha"},2360:{None:"sa",2364:{None:"s̤a"}},2361:{None:"ha",2364:{None:"ha"}},2306:{None:"ṃ"},2307:{32:{None:"ḥ"}},2305:{None:"n̐"},2365:{None:"’"},2366:{None:"ā"},2377:{None:"ô"},2367:{None:"i"},2368:{None:"ī"},2369:{None:"u"},2370:{None:"ū"},2371:{None:"ṛ"},2372:{None:"ṝ"},2375:{None:"e"},2378:{None:"ŏ"},2380:{None:"ău"},2376:{None:"ai"},2379:{None:"o"},2381:{None:""},2364:{None:""},2406:{None:"0"},2407:{None:"1"},2408:{None:"2"},2409:{None:"3"},2410:{None:"4"},2411:{None:"5"},2412:{None:"6"},2413:{None:"7"},2414:{None:"8"},2415:{None:"9"}}
