import interscript
import regex as re
interscript.stdlib.define_map("odni-ara-Arab-Latn-2015")
def _stage_main(s):
    s = interscript.stdlib.parallel_regexp_gsub(s, *_PRE_2241721791750062965)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")(?<!"+interscript.stdlib.aliases["boundary"]+"[‘’'])[a-￿]", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile("\\ Al\\ ", re.MULTILINE).sub(" al ", s)
    return s

interscript.stdlib.add_map_stage("odni-ara-Arab-Latn-2015", "main", _stage_main)
_PRE_2241721791750062965 = ["(?P<_0>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_1>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_2>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_3>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_4>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_5>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_6>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_7>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_8>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_9>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_10>"+interscript.stdlib.aliases["non_word_boundary"]+"ُ?اللَّه)|(?P<_11>ِي(?=(?:َ|u064f)))|(?P<_12>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ][؀-ۿ])ة)|(?P<_13>"+interscript.stdlib.aliases["boundary"]+"اللَّه)|(?P<_14>(?<="+interscript.stdlib.aliases["boundary"]+"ال[؀-ۿ][؀-ۿ])ة)|(?P<_15>ِيَّ)|(?P<_16>"+interscript.stdlib.aliases["non_word_boundary"]+"ُ?ال)|(?P<_17>َ(?=a[ht]))|(?P<_18>َوْ)|(?P<_19>َيْ)|(?P<_20>"+interscript.stdlib.aliases["boundary"]+"ال)|(?P<_21>َ(?=ة))|(?P<_22>ِي)|(?P<_23>ُو)|(?P<_24>َا)|(?P<_25>َى)|(?P<_26>ة"+interscript.stdlib.aliases["line_end"]+")|(?P<_27>بّ)|(?P<_28>تّ)|(?P<_29>ثّ)|(?P<_30>جّ)|(?P<_31>حّ)|(?P<_32>خّ)|(?P<_33>دّ)|(?P<_34>ذّ)|(?P<_35>رّ)|(?P<_36>زّ)|(?P<_37>سّ)|(?P<_38>شّ)|(?P<_39>صّ)|(?P<_40>ضّ)|(?P<_41>طّ)|(?P<_42>ظّ)|(?P<_43>غّ)|(?P<_44>فّ)|(?P<_45>قّ)|(?P<_46>كّ)|(?P<_47>لّ)|(?P<_48>مّ)|(?P<_49>نّ)|(?P<_50>هّ)|(?P<_51>وّ)|(?P<_52>يّ)|(?P<_53>"+interscript.stdlib.aliases["boundary"]+"ا)|(?P<_54>َ)|(?P<_55>ِ)|(?P<_56>ُ)|(?P<_57>ْ)|(?P<_58>آ)|(?P<_59>ة)|(?P<_60>ئ)|(?P<_61>ء)|(?P<_62>أ)|(?P<_63>ا)|(?P<_64>ب)|(?P<_65>ت)|(?P<_66>ث)|(?P<_67>ج)|(?P<_68>ح)|(?P<_69>خ)|(?P<_70>د)|(?P<_71>ذ)|(?P<_72>ر)|(?P<_73>ز)|(?P<_74>س)|(?P<_75>ش)|(?P<_76>ص)|(?P<_77>ض)|(?P<_78>ط)|(?P<_79>ظ)|(?P<_80>ع)|(?P<_81>غ)|(?P<_82>ف)|(?P<_83>ق)|(?P<_84>ك)|(?P<_85>ل)|(?P<_86>م)|(?P<_87>ن)|(?P<_88>ه)|(?P<_89>و)|(?P<_90>ي)", ["ah","ah","ah","ah","ah","ah","ah","ah","ah","ah","allah","iy","ah","Allah","ah","iy"," al ","","aw","ay","al ","","i","u","a","á","ah","bb","tt","th","jj","hh","kh","dd","dh","rr","zz","ss","sh","ṣṣ","ḍḍ","ṭṭ","ẓẓ","gh","ff","qq","kk","ll","mm","nn","hh","ww","yy","","a","i","u","","a","at","’","’","","a","b","t","th","j","h","kh","d","dh","r","z","s","sh","ṣ","ḍ","ṭ","ẓ","’","gh","f","q","k","l","m","n","h","w","y"]]
