import interscript
import regex as re
interscript.stdlib.define_map("un-asm-Beng-Latn-1972")
interscript.stdlib.add_map_alias("un-asm-Beng-Latn-1972", "beng_chars_1", "া")
interscript.stdlib.add_map_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1", "[ািীুূৃেৈোৌ্]")
def _stage_main(s):
    s = re.compile("ক(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("k", s)
    s = re.compile("খ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("গ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ঘ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("ঙ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("চ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("ছ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("chh", s)
    s = re.compile("জ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("j", s)
    s = re.compile("ঝ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("ঞ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ট(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ঠ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("ড(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("ঢ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ণ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ত(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("t", s)
    s = re.compile("থ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("th", s)
    s = re.compile("দ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("d", s)
    s = re.compile("ধ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("ন(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("n", s)
    s = re.compile("প(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("p", s)
    s = re.compile("ফ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("ব(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("b", s)
    s = re.compile("ভ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("ম(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("m", s)
    s = re.compile("য(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("j̱", s)
    s = re.compile("ৰ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("r", s)
    s = re.compile("ল(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("l", s)
    s = re.compile("ৱ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("v", s)
    s = re.compile("শ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("sh", s)
    s = re.compile("ষ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṣh", s)
    s = re.compile("স(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("s", s)
    s = re.compile("হ(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("h", s)
    s = re.compile("ড়(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṙ", s)
    s = re.compile("ঢ়(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṙh", s)
    s = re.compile("য়(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("y", s)
    s = re.compile("ড়(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṙ", s)
    s = re.compile("ঢ়(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("ṙh", s)
    s = re.compile("য়(?="+interscript.stdlib.get_alias_re("un-asm-Beng-Latn-1972", "beng_chars_1")+")", re.MULTILINE).sub("y", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_2025784967445479243)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("un-asm-Beng-Latn-1972", "main", _stage_main)
_PTREE_2025784967445479243 = {2437:{None:"a"},2438:{None:"ā"},2439:{None:"i"},2440:{None:"ī"},2441:{None:"u"},2442:{None:"ū"},2443:{None:"ṛ"},2447:{None:"e"},2448:{None:"ai"},2451:{None:"o"},2452:{None:"au"},2494:{None:"ā"},2495:{None:"i"},2496:{None:"ī"},2497:{None:"u"},2498:{None:"ū"},2499:{None:"ṛ"},2503:{None:"e"},2504:{None:"ai"},2507:{None:"o"},2508:{None:"au"},2434:{None:"ṁ"},2433:{None:"m̐"},2435:{None:"ḥ"},2509:{None:""},2453:{None:"ka"},2454:{None:"kha"},2455:{None:"ga"},2456:{None:"gha"},2457:{None:"ṅa"},2458:{None:"cha"},2459:{None:"chha"},2460:{None:"ja"},2461:{None:"jha"},2462:{None:"ña"},2463:{None:"ṭa"},2464:{None:"ṭha"},2465:{None:"ḍa",2492:{None:"ṙa"}},2466:{None:"ḍha",2492:{None:"ya"}},2467:{None:"ṇa"},2468:{None:"ta"},2469:{None:"tha"},2470:{None:"da"},2471:{None:"dha"},2472:{None:"na"},2474:{None:"pa"},2475:{None:"pha"},2476:{None:"ba"},2477:{None:"bha"},2478:{None:"ma"},2479:{None:"j̱a",2492:{None:"ya"}},2544:{None:"ra"},2482:{None:"la"},2545:{None:"va"},2486:{None:"sha"},2487:{None:"ṣha"},2488:{None:"sa"},2489:{None:"ha"},2510:{None:"t"},2524:{None:"ṙa"},2525:{None:"ṙha"},2527:{None:"ya"}}
