= Interscript: Interoperable Script Conversion Systems for Python

== Purpose

This repository contains code for the Interscript Python runtime ("Interscript-Python").

This software allows performing script conversions by using the
https://github.com/interscript/maps[default set of Interscript maps]
hosted at GitHub.

Interscript is a project for interoperable script conversion systems
and provides executable runtimes for multiple platforms.
Full documentation available https://github.com/interscript/interscript/[here].

== Integration

This section provides instructions on how to utilize Interscript-Python
with your application.

Interscript-Python can be used as a Python library

=== Configuration

[source,shell]
----
$ pip install interscript
----

== Usage

[source,javascript]
-----
import interscript
interscript.load_map('bgnpcgn-ukr-Cyrl-Latn-2019')
print(interscript.transliterate('bgnpcgn-ukr-Cyrl-Latn-2019', input()))
-----

== Development

Ensure you have used a bootstrap repository https://github.com/interscript/interscript
and not just cloned this repo yourself, otherwise `./setup.sh` script won\'t work.

`./setup.sh` script is used to build the maps from the `maps` repository using our Ruby
Interscript implementation. Those maps are compiled to respective `.py` files inside
`src/interscript/maps/` directory and are not included in this repository.

=== Running tests

[source,shell]
---
$ pip install regex pytest
$ ./build.sh
$ pip install -e .
$ pytest
---

=== Building package

[source,shell]
---
$ pip install regex pytest
$ ./build.sh
$ python -m build
---

=== Publishing package

Edit pyproject.toml to contain a new version number, create a commit
and add a git tag with that number.

== Copyright and license

This is a Ribose project. Copyright Ribose.
