# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_bool.ipynb.

# %% auto 0
__all__ = ['npbool', 'boolic', 'bool01', 'iterbool', 'bools']

# %% ../nbs/02_bool.ipynb 6
#| export


# %% ../nbs/02_bool.ipynb 8
from typing import TypeAlias

# %% ../nbs/02_bool.ipynb 10
#| export


# %% ../nbs/02_bool.ipynb 12
from ptyp import Prototype
from matr import npbool as npb

# %% ../nbs/02_bool.ipynb 14
from .iter import itertype

# %% ../nbs/02_bool.ipynb 16
@Prototype(npb)
class npbool: '''np.bool'''

@Prototype(bool, npb)
class boolic: '''bool, np.bool_'''

@Prototype(bool, npb, 0, 1)
class bool01: '''bool, np.bool_, 0, 1'''

@Prototype(itertype, attrs=dict(dtype=bool01))
class iterbool: '''iterable of `bool`'''

@Prototype(list, tuple, iterbool, attrs=dict(dtype=bool01))
class bools: '''list of bool01'''
