# Generated by Django 4.2.7 on 2023-12-04 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('location_name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('updated_by', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('tax_id', models.CharField(max_length=50)),
                ('updated_by', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
                ('logo_image', models.BinaryField(blank=True, null=True)),
                ('address_0', models.TextField(db_column='address')),
                ('contact', models.TextField()),
                ('organization_type', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evercycle_models.address')),
                ('main_contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evercycle_models.contact')),
                ('parent_org', models.ForeignKey(db_column='parent_org', on_delete=django.db.models.deletion.DO_NOTHING, to='evercycle_models.organization')),
            ],
            options={
                'db_table': 'organization',
            },
        ),
    ]
