# Generated by Django 4.2.7 on 2024-01-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evercycle_models', '0005_rename_warehouse_workflow_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorSecurity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'processor_security',
            },
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='data_erasure_id',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='warehouse_security',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='audit_report_sla',
            field=models.CharField(choices=[('2', '< 48 hours'), ('5', '< 5 business days'), ('14', '< 2 weeks'), ('30', '< 30 days')]),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='payment_methods',
            field=models.CharField(choices=[('ach', 'ACH'), ('wire', 'Wire'), ('check', 'Check')]),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='payment_terms',
            field=models.CharField(choices=[('5', '5 business days'), ('14', '2 weeks'), ('30', '30 days')]),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='report_services',
            field=models.CharField(choices=[('serialized', 'Provide serialized receipt confirmation'), ('device', 'Report locked devices before data erasure for unlocking opportunity')]),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='device_location_type_conus_choice',
            field=models.CharField(blank=True, choices=[('ak', 'Alaska'), ('hw', 'Hawaii')], null=True),
        ),
        migrations.CreateModel(
            name='DataErasure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('website_url', models.CharField(max_length=50)),
                ('certificate_example', models.BinaryField(blank=True, null=True)),
                ('policy', models.BinaryField(blank=True, null=True)),
                ('certifications', models.ManyToManyField(to='evercycle_models.certification')),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='data_erasure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evercycle_models.dataerasure'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='processor_security',
            field=models.ManyToManyField(to='evercycle_models.processorsecurity'),
        ),
    ]
