# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/streaming/streaming_data_point.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from truera.protobuf.public import qoi_pb2 as truera_dot_protobuf_dot_public_dot_qoi__pb2
from truera.protobuf.public import truera_custom_options_pb2 as truera_dot_protobuf_dot_public_dot_truera__custom__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;truera/protobuf/public/streaming/streaming_data_point.proto\x12\x10truera.streaming\x1a\x1cgoogle/protobuf/struct.proto\x1a truera/protobuf/public/qoi.proto\x1a\x32truera/protobuf/public/truera_custom_options.proto\"\xf1\x05\n\x12StreamingDataPoint\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x61ta_collection_id\x18\x02 \x01(\t\x12\x10\n\x08split_id\x18\x0b \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12.\n\nscore_type\x18\n \x01(\x0e\x32\x1a.truera.QuantityOfInterest\x12\n\n\x02id\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12<\n\x04\x64\x61ta\x18\x06 \x03(\x0b\x32..truera.streaming.StreamingDataPoint.DataEntry\x12>\n\x05label\x18\x07 \x03(\x0b\x32/.truera.streaming.StreamingDataPoint.LabelEntry\x12>\n\x05\x65xtra\x18\x08 \x03(\x0b\x32/.truera.streaming.StreamingDataPoint.ExtraEntry\x12H\n\nprediction\x18\t \x03(\x0b\x32\x34.truera.streaming.StreamingDataPoint.PredictionEntry\x12\x14\n\x0coptions_hash\x18\x0c \x01(\t\x1a\x43\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x1a\x44\n\nLabelEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x1a\x44\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x1aI\n\x0fPredictionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x42y\n\x1d\x63om.truera.protobuf.streamingB\x17StreamingDataPointProtoP\x01Z9truera.com/protobuf/public/streaming/streaming_data_point\x90\x82\x19\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.streaming.streaming_data_point_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.truera.protobuf.streamingB\027StreamingDataPointProtoP\001Z9truera.com/protobuf/public/streaming/streaming_data_point\220\202\031\001'
  _globals['_STREAMINGDATAPOINT_DATAENTRY']._options = None
  _globals['_STREAMINGDATAPOINT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_STREAMINGDATAPOINT_LABELENTRY']._options = None
  _globals['_STREAMINGDATAPOINT_LABELENTRY']._serialized_options = b'8\001'
  _globals['_STREAMINGDATAPOINT_EXTRAENTRY']._options = None
  _globals['_STREAMINGDATAPOINT_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_STREAMINGDATAPOINT_PREDICTIONENTRY']._options = None
  _globals['_STREAMINGDATAPOINT_PREDICTIONENTRY']._serialized_options = b'8\001'
  _globals['_STREAMINGDATAPOINT']._serialized_start=198
  _globals['_STREAMINGDATAPOINT']._serialized_end=951
  _globals['_STREAMINGDATAPOINT_DATAENTRY']._serialized_start=669
  _globals['_STREAMINGDATAPOINT_DATAENTRY']._serialized_end=736
  _globals['_STREAMINGDATAPOINT_LABELENTRY']._serialized_start=738
  _globals['_STREAMINGDATAPOINT_LABELENTRY']._serialized_end=806
  _globals['_STREAMINGDATAPOINT_EXTRAENTRY']._serialized_start=808
  _globals['_STREAMINGDATAPOINT_EXTRAENTRY']._serialized_end=876
  _globals['_STREAMINGDATAPOINT_PREDICTIONENTRY']._serialized_start=878
  _globals['_STREAMINGDATAPOINT_PREDICTIONENTRY']._serialized_end=951
# @@protoc_insertion_point(module_scope)
