# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyhdmap/proto/hdmap_lib/proto/road_link.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyhdmap.proto.hdmap_lib.proto import id_pb2 as pyhdmap_dot_proto_dot_hdmap__lib_dot_proto_dot_id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-pyhdmap/proto/hdmap_lib/proto/road_link.proto\x12\thdmap_lib\x1a&pyhdmap/proto/hdmap_lib/proto/id.proto\"\x87\x02\n\x08RoadLink\x12\x1f\n\x08junction\x18\x01 \x01(\x0b\x32\r.hdmap_lib.Id\x12 \n\tfrom_road\x18\x02 \x01(\x0b\x32\r.hdmap_lib.Id\x12\x1e\n\x07to_road\x18\x03 \x01(\x0b\x32\r.hdmap_lib.Id\x12/\n\tturn_type\x18\x04 \x01(\x0e\x32\x1c.hdmap_lib.RoadLink.TurnType\"g\n\x08TurnType\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0c\n\x08STRAIGHT\x10\x02\x12\r\n\tLEFT_TURN\x10\x03\x12\x0f\n\x0bLEFT_U_TURN\x10\x04\x12\x0e\n\nRIGHT_TURN\x10\x05\x12\x10\n\x0cRIGHT_U_TURN\x10\x06')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyhdmap.proto.hdmap_lib.proto.road_link_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROADLINK']._serialized_start=101
  _globals['_ROADLINK']._serialized_end=364
  _globals['_ROADLINK_TURNTYPE']._serialized_start=261
  _globals['_ROADLINK_TURNTYPE']._serialized_end=364
# @@protoc_insertion_point(module_scope)
