
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-05T19:45:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3750bc2315111eab86069a5a0778cfa3f84e96b7",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
