#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class picture:
    fluent_name = ...
    child_names = ...
    color_mode = ...
    driver_options = ...
    invert_background = ...
    landscape = ...
    x_resolution = ...
    y_resolution = ...
    dpi = ...
    use_window_resolution = ...
    standard_resolution = ...
    jpeg_hardcopy_quality = ...
    command_names = ...

    def preview(self, ):
        """
        Display a preview image of a hardcopy.
        """

    def save_picture(self, file_name: str):
        """
        'save_picture' command.
        
        Parameters
        ----------
            file_name : str
                'file_name' child.
        
        """

    def list_color_mode(self, ):
        """
        'list_color_mode' command.
        """

