# Generated by Django 4.2.7 on 2023-12-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evercycle_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address_0',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact',
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_org',
            field=models.ForeignKey(blank=True, db_column='parent_org', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evercycle_models.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
