#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class clustering_settings:
    fluent_name = ...
    child_names = ...
    enable_mesh_interface_clustering = ...
    split_angle = ...
    clustering_algorithm = ...
    faces_per_cluster = ...
    command_names = ...

    def print_thread_clusters(self, ):
        """
        Prints the following for all boundary threads: thread-id, number of faces, faces per surface cluster, and the number of surface clusters.
        """

