#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class controls:
    fluent_name = ...
    child_names = ...
    solution_based_initialization = ...
    auto_adjust = ...
    advancement = ...
    under_relaxation = ...
    amg = ...
    stabilization = ...
    command_names = ...

    def default(self, ):
        """
        Set controls to default.
        """

