#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class dissipation:
    fluent_name = ...
    child_names = ...
    damping_factor = ...
    damping_relaxation = ...
    damping_order = ...
    suppression = ...
    command_names = ...

    def default(self, ):
        """
        Set residual minimization scheme controls to default.
        """

