#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class pressure_outlet_child:
    fluent_name = ...
    child_names = ...
    name = ...
    phase = ...
    momentum = ...
    turbulence = ...
    thermal = ...
    radiation = ...
    species = ...
    dpm = ...
    multiphase = ...
    potential = ...
    structure = ...
    uds = ...
    icing = ...
    geometry = ...
    query_names = ...

    def adjacent_cell_zone(self, ):
        """
        Get adjacent cell zone for this face zone.
        """

    def shadow_face_zone(self, ):
        """
        Get shadow zone for this wall zone.
        """

