#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class solution_animations_child:
    fluent_name = ...
    child_names = ...
    name = ...
    animate_on = ...
    frequency = ...
    flow_time_frequency = ...
    frequency_of = ...
    appended_time_freq_of = ...
    storage_type = ...
    storage_dir = ...
    window_id = ...
    view = ...
    use_raytracing = ...
    name_append_time = ...
    appended_time_decimal_precision = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

