from truera.utils.data_constants import NORMALIZED_LABEL_COLUMN_NAME

COMPARISON_TYPE_INDIVIDUAL = "indiv"
COMPARISON_TYPE_COMPLEMENT = "complement"
COMPARISON_TYPE_SEGMENT = "segment"
COMPARISON_TYPE_ALL = "all"

SWAP_FILTER_TYPE_SWAPIN = 'swapin'
SWAP_FILTER_TYPE_SWAPOUT = 'swapall'
SWAP_FILTER_TYPE_NONE = 'none'

GROUND_TRUTH_FILTER_TYPE_CORRECT = 'correct'
GROUND_TRUTH_FILTER_TYPE_INCORRECT = 'incorrect'
GROUND_TRUTH_FILTER_TYPE_ALL = 'all'

PLOT_TYPE_VIOLIN = 'violin'
PLOT_TYPE_HISTOGRAM = 'histogram'

DATASET_ID_FICO = 'fico'
DATASET_ID_FICOV2 = 'ficov2'
DATASET_ID_FICO_PYSPARK = 'fico_pyspark'
DATASET_ID_LENDINGCLUB = 'lendingclub'
DATASET_ID_LENDINGCLUB_TRANSFORM = 'lendingclub_transform'
VALID_DATASET_IDS = [DATASET_ID_FICO, DATASET_ID_LENDINGCLUB]

LABEL_COLUMN_NAME = NORMALIZED_LABEL_COLUMN_NAME

# For overfitting
DENSITY_DIAGNOSTICS = "density_diagnostics"

# config files
CLIENTS_CONFIG_FILE = "clients.yaml"
AIQ_CONFIG_FILE = "aiq_config.yaml"
PYTHON_LOG_CONFIG_FILE = "logging-config.ini"
AUTH_CONFIG_FILE = "auth_config.yaml"