#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class dpm:
    fluent_name = ...
    child_names = ...
    discrete_phase_bc_type = ...
    dem_collision_partner = ...
    reinj_inj = ...
    dpm_bc_norm_coeff = ...
    dpm_bc_tang_coeff = ...
    dpm_bc_frictn_coeff = ...
    discrete_phase_bc_function = ...
    dpm_film_splash_nsamp = ...
    dpm_crit_temp_option = ...
    dpm_critical_temp_factor = ...
    dpm_calibratable_temp = ...
    dpm_impingement_splashing_model = ...
    dpm_upper_deposition_limit_offset = ...
    dpm_deposition_delta_t = ...
    dpm_laplace_number_constant = ...
    dpm_partial_evaporation_ratio = ...
    ra_roughness = ...
    rz_roughness = ...
    rq_roughness = ...
    rsm_roughness = ...
    enable_generic_erosion_model = ...
    generic_impact_angle_function = ...
    generic_diameter_function = ...
    generic_velocity_exponent_function = ...
    enable_finnie_erosion_model = ...
    dpm_bc_erosion_finnie_k = ...
    dpm_bc_erosion_finnie_vel_exp = ...
    dpm_bc_erosion_finnie_max_erosion_angle = ...
    dpm_bc_erosion_mclaury = ...
    dpm_bc_erosion_mclaury_a = ...
    dpm_bc_erosion_mclaury_vel_exp = ...
    dpm_bc_erosion_mclaury_transition_angle = ...
    dpm_bc_erosion_mclaury_b = ...
    dpm_bc_erosion_mclaury_c = ...
    dpm_bc_erosion_mclaury_w = ...
    dpm_bc_erosion_mclaury_x = ...
    dpm_bc_erosion_mclaury_y = ...
    dpm_bc_erosion_oka = ...
    dpm_bc_erosion_oka_e90 = ...
    dpm_bc_erosion_oka_hv = ...
    dpm_bc_erosion_oka_n1 = ...
    dpm_bc_erosion_oka_n2 = ...
    dpm_bc_erosion_oka_k2 = ...
    dpm_bc_erosion_oka_k3 = ...
    dpm_bc_erosion_oka_dref = ...
    dpm_bc_erosion_oka_vref = ...
    dpm_bc_erosion_dnv = ...
    dpm_bc_erosion_dnv_k = ...
    dpm_bc_erosion_dnv_n = ...
    dpm_bc_erosion_dnv_ductile = ...
    dpm_bc_erosion_shear = ...
    dpm_bc_erosion_shear_v = ...
    dpm_bc_erosion_shear_c = ...
    dpm_bc_erosion_shear_packing_limit = ...
    dpm_bc_erosion_shielding = ...
    dpm_wall_heat_exchange = ...
    dpm_film_condensation = ...
    dpm_film_bl_model = ...
    dpm_particle_stripping = ...
    dpm_critical_shear_stress = ...
    dpm_film_separation_model = ...
    dpm_critical_we_number = ...
    dpm_film_separation_angle = ...
    dpm_allow_lwf_to_vof = ...
    dpm_allow_vof_to_lwf = ...
    dpm_initialize_lwf = ...
    dpm_initial_height = ...
    film_velocity = ...
    dpm_initial_temperature = ...
    dpm_initial_injection = ...
    film_parcel_surface_area_density = ...
    minimum_number_of_parcels_per_face = ...
    in_situ_data_reduction = ...
    data_reduction = ...
    set_as_eulerian_film_wall = ...
    film_condition_type = ...
    film_height = ...
    flux_momentum = ...
    relative_initial_film_velocity = ...
    include_film_momentum_pressure = ...
    film_temperature = ...
    film_passive_scalar = ...
    enable_film_source_terms = ...
    film_mass_source = ...
    momentum_source = ...
    film_heat_source = ...
    film_passive_scalar_source = ...
    enable_film_phase_change = ...
    phase_change_model = ...
    film_condensation_constant = ...
    film_vaporization_constant = ...
    film_condensation_rate = ...
    film_vaporization_rate = ...
    enable_flow_momentum_coupling = ...
    enable_dpm_wall_splash = ...
    allow_film_boundary_separation = ...
    impingement_model = ...
    number_of_splashed_particles = ...
    critical_temperature_factor = ...
    wall_roughness_length_ra = ...
    wall_roughness_length_rz = ...
    upper_deposition_limit_offset = ...
    deposition_delta_t = ...
    laplace_number_constant = ...
    partial_evaporation_ratio = ...
    enable_film_contact_angle_force = ...
    film_contact_angle_mean = ...
    film_contact_angle_rstd = ...
    film_contact_angle_beta = ...
    film_vof_coupling_high = ...
    film_vof_trans_high = ...
    film_vof_trans_high_relax = ...
    film_vof_coupling_low = ...
    film_vof_trans_low = ...
    film_vof_trans_low_relax = ...
    command_names = ...

    def dpm_do_initialize_lwf_now(self, ):
        """
        Apply All settings and initialize film on selected wall(s) Now?.
        """

