#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class interpolated_data:
    fluent_name = ...
    child_names = ...
    zone = ...
    y_axis_function = ...
    x_axis_function = ...
    axes = ...
    curves = ...
    command_names = ...

    def plot(self, ):
        """
        Plot interpolated data.
        """

