#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class moment_child:
    fluent_name = ...
    child_names = ...
    name = ...
    report_type = ...
    mom_center = ...
    mom_axis = ...
    reference_frame = ...
    zones = ...
    per_zone = ...
    average_over = ...
    retain_instantaneous_values = ...
    report_output_type = ...
    physics = ...
    geometry = ...
    command_names = ...

    def create_output_parameter(self, ):
        """
        'create_output_parameter' command.
        """

