#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class ntgk_model_settings:
    fluent_name = ...
    child_names = ...
    initial_dod = ...
    ref_capacity = ...
    data_type = ...
    poly_u_function = ...
    poly_y_function = ...
    poly_t_dependence = ...
    u_table = ...
    y_table = ...
    internal_resistance_table = ...
    limit_current_enabled = ...
    provide_utable_enabled = ...
    limit_current_table = ...
    monitor_names = ...
    command_names = ...

    def raw_data(self, import_files_enabled: bool, number_of_files: int, files: List[str], capacify_fade_enabled: bool):
        """
        Specify U and Y parameters using raw data.
        
        Parameters
        ----------
            import_files_enabled : bool
                Import raw data in the NTGK model.
            number_of_files : int
                Total number of discharging files.
            files : typing.List[str]
                Discharging file names in the NTGK model.
            capacify_fade_enabled : bool
                Enable capacity fade model in the NTGK model.
        
        """

