#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class phase_child:
    fluent_name = ...
    child_names = ...
    zonal_models = ...
    zonal_flow = ...
    zonal_flow_spec = ...
    general = ...
    conical = ...
    reference_frame = ...
    mesh_motion = ...
    porous_zone = ...
    fan_zone = ...
    embedded_les = ...
    reaction = ...
    source_terms = ...
    fixed_values = ...
    multiphase = ...
    disabled = ...
    query_names = ...

    def adjacent_cell_zone(self, ):
        """
        Get adjacent cell zone for this face zone.
        """

    def shadow_face_zone(self, ):
        """
        Get shadow zone for this wall zone.
        """

