#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class plane_surface_child:
    fluent_name = ...
    child_names = ...
    name = ...
    method = ...
    x = ...
    y = ...
    z = ...
    point = ...
    normal_computation_method = ...
    surface_aligned_normal = ...
    normal = ...
    p0 = ...
    p1 = ...
    p2 = ...
    bounded = ...
    sample_points = ...
    edges = ...
    command_names = ...

    def display(self, ):
        """
        Specify the attribute of display command.
        """

