# Generated by Django 5.0.1 on 2024-03-04 15:03

import django.db.models.deletion
import globlocks.blocks.block_fields.rangeslider.rangeslider
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0092_formsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts', wagtail.fields.StreamField([('alert', wagtail.blocks.StructBlock([('settings', wagtail.blocks.StructBlock([('custom_template', wagtail.blocks.ChoiceBlock(choices=[('0', 'Lint'), ('1', 'Toast')], classname=None, label='Template', translatable=False)), ('duration', globlocks.blocks.block_fields.rangeslider.rangeslider.RangeSliderBlock(default=10, help_text='The alert will disappear after this many seconds.', label='Duration', max_value=60, min_value=0, stepping=1, unit='s')), ('dismissible', wagtail.blocks.BooleanBlock(default=True, help_text='Can the alert be dismissed by the user?', label='Dismissible')), ('alert_type', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], help_text='The type/theme of alert to display.', label='Type')), ('active', wagtail.blocks.BooleanBlock(default=True, label='Active', required=False)), ('active_from', wagtail.blocks.DateTimeBlock(label='Active From', required=False)), ('active_to', wagtail.blocks.DateTimeBlock(label='Active To', required=False))])), ('title', wagtail.blocks.CharBlock(label='Title', required=False)), ('body', wagtail.blocks.RichTextBlock(label='Body', required=True))]))], blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Alert Settings',
                'verbose_name_plural': 'Alert Settings',
            },
        ),
    ]
