#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class contour_child:
    fluent_name = ...
    child_names = ...
    name = ...
    field = ...
    filled = ...
    boundary_values = ...
    contour_lines = ...
    node_values = ...
    surfaces_list = ...
    range_option = ...
    coloring = ...
    color_map = ...
    draw_mesh = ...
    mesh_object = ...
    display_state_name = ...
    physics = ...
    geometry = ...
    surfaces = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

