#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class data_sampling:
    fluent_name = ...
    child_names = ...
    data_sampling = ...
    sampling_interval = ...
    statistics_shear_stress = ...
    statistics_heat_flux = ...
    wall_statistics = ...
    force_statistics = ...
    time_statistics_dpm = ...
    species_list = ...
    statistics_mixture_fraction = ...
    statistics_reaction_progress = ...
    save_cff_unsteady_statistics = ...
    command_names = ...

    def setup_unsteady_statistics(self, udf_cf_names: List[str]):
        """
        'setup_unsteady_statistics' command.
        
        Parameters
        ----------
            udf_cf_names : typing.List[str]
                'udf_cf_names' child.
        
        """

