#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class particle_tracks_child:
    fluent_name = ...
    child_names = ...
    name = ...
    uid = ...
    options = ...
    filter_settings = ...
    range = ...
    style_attribute = ...
    vector_settings = ...
    plot = ...
    track_single_particle_stream = ...
    skip = ...
    coarsen = ...
    field = ...
    injections_list = ...
    free_stream_particles = ...
    wall_film_particles = ...
    track_pdf_particles = ...
    color_map = ...
    draw_mesh = ...
    mesh_object = ...
    display_state_name = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

