from truera.client.nn.backend import NNBackend as NNB
from truera.client.nn.wrappers.tf import import_tf

tf = import_tf(version=1)


class Backend(NNB[tf.Tensor, tf.Graph]):
    Model = tf.Graph
    Tensor = tf.Tensor

    # yapf: disable
    class Inputs(Tensor): ...
    class Batchable(Inputs): ...
    class Parameter(Inputs): ... # non-batchable model args
    class Embeddings(Batchable): ...
    class Masks(Batchable): ...
    class Words(Batchable): ...
    class Outputs(Tensor): ...
    class Logits(Outputs): ...
    class Probits(Outputs): ...
    # yapf: enable
