# Generated by Django 4.2.7 on 2024-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evercycle_models', '0013_boxstatus_tracking_tracker_boxtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='label',
            field=models.TextField(max_length=100),
        ),
    ]
