import interscript
import regex as re
interscript.stdlib.define_map("alalc-tel-Telu-Latn-1997")
interscript.stdlib.add_map_alias("alalc-tel-Telu-Latn-1997", "telu_chars_1", "ా")
interscript.stdlib.add_map_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1", "[ాిీుూృెేైొోౌ౬]")
def _stage_main(s):
    s = re.compile("క(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("k", s)
    s = re.compile("ఖ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("గ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ఘ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("ఙ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("చ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("c", s)
    s = re.compile("ౘ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ĉ", s)
    s = re.compile("ఛ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("జ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("j", s)
    s = re.compile("ౙ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ĵ", s)
    s = re.compile("ఝ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("ఞ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ట(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ఠ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("డ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("ఢ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ణ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("త(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("t", s)
    s = re.compile("థ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("th", s)
    s = re.compile("ద(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("d", s)
    s = re.compile("ధ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("న(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("n", s)
    s = re.compile("ప(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("p", s)
    s = re.compile("ఫ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("బ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("b", s)
    s = re.compile("భ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("మ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("m", s)
    s = re.compile("య(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("y", s)
    s = re.compile("ర(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("r", s)
    s = re.compile("ఱ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ṛ", s)
    s = re.compile("ల(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("l", s)
    s = re.compile("ళ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ḷ", s)
    s = re.compile("వ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("v", s)
    s = re.compile("శ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ś", s)
    s = re.compile("ష(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("ṣ", s)
    s = re.compile("స(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("s", s)
    s = re.compile("హ(?="+interscript.stdlib.get_alias_re("alalc-tel-Telu-Latn-1997", "telu_chars_1")+")", re.MULTILINE).sub("h", s)
    s = re.compile("ం(?=[కఖగఘఙ])", re.MULTILINE).sub("ṅ", s)
    s = re.compile("ం(?=[చౘఛజౙఝఞ])", re.MULTILINE).sub("ñ", s)
    s = re.compile("ం(?=[టఠడఢణ])", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ం(?=[తథదధన])", re.MULTILINE).sub("n", s)
    s = re.compile("ం(?=[పఫబభమ])", re.MULTILINE).sub("m", s)
    s = re.compile("ఁ(?=[కఖగఘఙచౘఛజౙఝఞటఠడఢణతథదధన])", re.MULTILINE).sub("n̐", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_3166905283592856809)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("alalc-tel-Telu-Latn-1997", "main", _stage_main)
_PTREE_3166905283592856809 = {3077:{None:"a"},3078:{None:"ā"},3079:{None:"i"},3080:{None:"ī"},3081:{None:"u"},3082:{None:"ū"},3083:{None:"ṛ"},3168:{None:"ṝ"},3084:{None:"ḻ"},3086:{None:"e"},3087:{None:"ē"},3088:{None:"ai"},3090:{None:"o"},3091:{None:"ō"},3092:{None:"au"},3093:{None:"ka"},3094:{None:"kha"},3095:{None:"ga"},3096:{None:"gha"},3097:{None:"ṅa"},3098:{None:"ca"},3160:{None:"ĉa"},3099:{None:"cha"},3100:{None:"ja"},3161:{None:"ĵa"},3101:{None:"jha"},3102:{None:"ña"},3103:{None:"ṭa"},3104:{None:"ṭha"},3105:{None:"ḍa"},3106:{None:"ḍha"},3107:{None:"ṇa"},3108:{None:"ta"},3109:{None:"tha"},3110:{None:"da"},3111:{None:"dha"},3112:{None:"na"},3114:{None:"pa"},3115:{None:"pha"},3116:{None:"ba"},3117:{None:"bha"},3118:{None:"ma"},3119:{None:"ya"},3120:{None:"ra"},3121:{None:"ṛa"},3122:{None:"la"},3123:{None:"ḷa"},3125:{None:"va"},3126:{None:"śa"},3127:{None:"ṣa"},3128:{None:"sa"},3129:{None:"ha"},2433:{None:"m̐"},3073:{None:"m̐"},3075:{None:"ḥ"},3074:{None:"ṃ"},3134:{None:"ā"},3135:{None:"i"},3136:{None:"ī"},3137:{None:"u"},3138:{None:"ū"},3139:{None:"ṛ"},3142:{None:"e"},3143:{None:"ē"},3144:{None:"ai"},3146:{None:"o"},3147:{None:"ŏ"},3148:{None:"au"},2509:{None:""},3149:{None:""},3157:{9:{None:""}},3158:{9:{None:""}},2381:{None:""},2364:{None:""},8205:{None:""},8204:{None:""},3174:{None:"0"},3175:{None:"1"},3176:{None:"2"},3177:{None:"3"},3178:{None:"4"},3179:{None:"5"},3180:{None:"6"},3181:{None:"7"},3182:{None:"8"},3183:{None:"9"}}
