import interscript
import regex as re
interscript.stdlib.define_map("alalc-guj-Gujr-Latn-1997")
interscript.stdlib.add_map_alias("alalc-guj-Gujr-Latn-1997", "characters_set1", "ા")
interscript.stdlib.add_map_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1", "[ાિીુૂૃૅેૈૉોૌ્]")
def _stage_main(s):
    s = re.compile("ં(?=[કખગઘઙ])", re.MULTILINE).sub("ṅ", s)
    s = re.compile("ં(?=[ચછજઝઞ])", re.MULTILINE).sub("ñ", s)
    s = re.compile("ં(?=[ટઠડઢણ])", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ં(?=[તથદધન])", re.MULTILINE).sub("n", s)
    s = re.compile("ં(?=[પફબભમ])", re.MULTILINE).sub("m", s)
    s = re.compile("ક(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("k", s)
    s = re.compile("ખ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("ગ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ઘ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("ઙ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("ચ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("c", s)
    s = re.compile("છ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("જ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("j", s)
    s = re.compile("ઝ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("ઞ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ટ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ઠ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("ડ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("ઢ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ણ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ત(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("t", s)
    s = re.compile("થ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("th", s)
    s = re.compile("દ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("d", s)
    s = re.compile("ધ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("ન(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("n", s)
    s = re.compile("પ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("p", s)
    s = re.compile("ફ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("બ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("b", s)
    s = re.compile("ભ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("મ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("m", s)
    s = re.compile("ય(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("y", s)
    s = re.compile("ર(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("r", s)
    s = re.compile("લ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("l", s)
    s = re.compile("ળ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ḷ", s)
    s = re.compile("વ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("v", s)
    s = re.compile("શ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("ś", s)
    s = re.compile("ષ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("sh", s)
    s = re.compile("સ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("s", s)
    s = re.compile("હ(?="+interscript.stdlib.get_alias_re("alalc-guj-Gujr-Latn-1997", "characters_set1")+")", re.MULTILINE).sub("h", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_4279637028525777987)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("alalc-guj-Gujr-Latn-1997", "main", _stage_main)
_PTREE_4279637028525777987 = {2693:{None:"a"},2694:{None:"ā"},2695:{None:"i"},2696:{None:"ī"},2697:{None:"u"},2698:{None:"ū"},2699:{None:"ṛ"},2701:{None:"e"},2703:{None:"ȇ"},2704:{None:"ai"},2705:{None:"o"},2707:{None:"ȏ"},2708:{None:"au"},2709:{None:"ka"},2710:{None:"kha"},2711:{None:"ga"},2712:{None:"gha"},2713:{None:"ṅa"},2714:{None:"ca"},2715:{None:"cha"},2716:{None:"ja"},2717:{None:"jha"},2718:{None:"ña"},2719:{None:"ṭa"},2720:{None:"ṭha"},2721:{None:"ḍa"},2722:{None:"ḍha"},2723:{None:"ṇa"},2724:{None:"ta"},2725:{None:"tha"},2726:{None:"da"},2727:{None:"dha"},2728:{None:"na"},2730:{None:"pa"},2731:{None:"pha"},2732:{None:"ba"},2733:{None:"bha"},2734:{None:"ma"},2735:{None:"ya"},2736:{None:"ra"},2738:{None:"la"},2739:{None:"ḷa"},2741:{None:"va"},2742:{None:"śa"},2743:{None:"sha"},2744:{None:"sa"},2745:{None:"ha"},2691:{None:"ḥ"},2690:{None:"ṃ"},2749:{None:"’"},2750:{None:"ā"},2751:{None:"i"},2752:{None:"ī"},2753:{None:"u"},2754:{None:"ū"},2755:{None:"ṛ"},2757:{None:"e"},2759:{None:"ȇ"},2760:{None:"ai"},2761:{None:"o"},2763:{None:"ȏ"},2764:{None:"au"},2790:{None:"0"},2791:{None:"1"},2792:{None:"2"},2793:{None:"3"},2794:{None:"4"},2795:{None:"5"},2796:{None:"6"},2797:{None:"7"},2798:{None:"8"},2799:{None:"9"},2765:{None:""},2748:{None:""},2404:{None:"."},2509:{None:""},8205:{None:""}}
