import interscript
import regex as re
interscript.stdlib.define_map("alalc-mal-Mlym-Latn-1997")
interscript.stdlib.add_map_alias("alalc-mal-Mlym-Latn-1997", "mlym_chars_1", "ാ")
interscript.stdlib.add_map_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1", "[ാിീുൂ്ൃൄെേൈൊോൌൢൣ്]")
def _stage_main(s):
    s = re.compile("්(?=[കഖഗഘങ])", re.MULTILINE).sub("ṅ", s)
    s = re.compile("්(?=[ചഛജഝഞ])", re.MULTILINE).sub("ñ", s)
    s = re.compile("්(?=[ടഠഡഢണ])", re.MULTILINE).sub("ṇ", s)
    s = re.compile("්(?=[തഥദധന])", re.MULTILINE).sub("n", s)
    s = re.compile("ക(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("k", s)
    s = re.compile("ഖ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("ഗ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ഘ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("ങ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("ച(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("c", s)
    s = re.compile("ഛ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("ജ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("j", s)
    s = re.compile("ഝ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("ഞ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ട(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ഠ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("ഡ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("d̂", s)
    s = re.compile("ഢ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ണ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ത(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("t", s)
    s = re.compile("ഥ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("th", s)
    s = re.compile("ദ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("d", s)
    s = re.compile("ധ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("ന(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("n", s)
    s = re.compile("പ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("p", s)
    s = re.compile("ഫ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("ബ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("b", s)
    s = re.compile("ഭ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("മ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("m", s)
    s = re.compile("യ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("y", s)
    s = re.compile("ര(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("r", s)
    s = re.compile("റ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ṟ", s)
    s = re.compile("ല(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("l", s)
    s = re.compile("ള(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ḷ", s)
    s = re.compile("ഴ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ḻ", s)
    s = re.compile("വ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("v", s)
    s = re.compile("ശ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ś", s)
    s = re.compile("ഷ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ṣ", s)
    s = re.compile("സ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("s", s)
    s = re.compile("ഩ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("ṉ", s)
    s = re.compile("ഹ(?="+interscript.stdlib.get_alias_re("alalc-mal-Mlym-Latn-1997", "mlym_chars_1")+")", re.MULTILINE).sub("h", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_253016221987963614)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("alalc-mal-Mlym-Latn-1997", "main", _stage_main)
_PTREE_253016221987963614 = {3333:{None:"a"},3334:{None:"ā"},3335:{None:"i"},3336:{None:"ī"},3337:{None:"u",3405:{None:"ū"}},3338:{None:"ū"},3339:{None:"ṛ"},3424:{None:"ṝ"},3340:{None:"ḷ"},3425:{None:"ḹ"},3342:{None:"e"},3343:{None:"ē"},3344:{None:"ai"},3346:{None:"o"},3347:{None:"ō"},3348:{None:"au"},3349:{None:"ka"},3350:{None:"kha"},3351:{None:"ga"},3352:{None:"gha"},3353:{None:"ṅa"},3354:{None:"ca"},3355:{None:"cha"},3356:{None:"ja"},3357:{None:"jha"},3358:{None:"ña"},3359:{None:"ṭa"},3360:{None:"ṭha"},3361:{None:"d̂a"},3362:{None:"ḍha"},3363:{None:"ṇa"},3364:{None:"ta"},3365:{None:"tha"},3366:{None:"da"},3367:{None:"dha"},3368:{None:"na"},3370:{None:"pa"},3371:{None:"pha"},3372:{None:"ba"},3373:{None:"bha"},3374:{None:"ma"},3375:{None:"ya"},3376:{None:"ra"},3377:{None:"ṟa",3405:{3377:{None:"ṯṯa"}}},3378:{None:"la"},3379:{None:"ḷa"},3380:{None:"ḻa"},3381:{None:"va"},3382:{None:"śa"},3383:{None:"ṣa"},3384:{None:"sa"},3369:{None:"ṉa"},3385:{None:"ha"},3331:{None:"ḥ"},3330:{None:"ṃ"},3389:{None:":’"},3390:{None:"ā"},3391:{None:"i"},3392:{None:"ī"},3393:{None:"u"},3394:{None:"ū"},3405:{None:"ŭ"},3395:{None:"ṛ"},3396:{None:"ṝ"},3426:{None:"ḷ"},3427:{None:"ḹ"},3398:{None:"e"},3399:{None:"ē"},3400:{None:"ai"},3402:{None:"o"},3403:{None:"ō"},3404:{None:"au"},2381:{None:""},2364:{None:""},3415:{None:""},8205:{None:""},8204:{None:""},3430:{None:"0"},3431:{None:"1"},3432:{None:"2"},3433:{None:"3"},3434:{None:"4"},3435:{None:"5"},3436:{None:"6"},3437:{None:"7"},3438:{None:"8"},3439:{None:"9"},3440:{None:"10"},3441:{None:"100"},3442:{None:"1000"},3455:{None:"k"},3450:{None:"ṇ"},3451:{None:"n"},3453:{None:"l"},3454:{None:"ḷ"},3452:{None:"r"},3386:{None:"ṯa"}}
