import interscript
import regex as re
interscript.stdlib.define_map("bgnpcgn-rus-Cyrl-Latn-1947")
interscript.stdlib.add_map_alias("bgnpcgn-rus-Cyrl-Latn-1947", "rus_extvowel", "А")
interscript.stdlib.add_map_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_extvowel", "[АаЕеЁёИиОоУуЫыЭэЮюЯяЙйЪъЬь]")
interscript.stdlib.add_map_alias("bgnpcgn-rus-Cyrl-Latn-1947", "rus_vowel", "А")
interscript.stdlib.add_map_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_vowel", "[АаЕеЁёИиОоУуЫыЭэЮюЯя]")
interscript.stdlib.add_map_alias("bgnpcgn-rus-Cyrl-Latn-1947", "rus_limvowel", "А")
interscript.stdlib.add_map_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_limvowel", "[АаУуЫыЭэ]")
interscript.stdlib.add_map_alias("bgnpcgn-rus-Cyrl-Latn-1947", "rus_cons", "Б")
interscript.stdlib.add_map_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_cons", "[БбВвГгДдЖжЗзКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ]")
interscript.stdlib.add_map_alias("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper", "A")
interscript.stdlib.add_map_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper", "(?:[A-Z]|[Ë])")
interscript.stdlib.add_map_alias("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar", "Ye")
interscript.stdlib.add_map_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar", "(?:Ye|Yë|Sh|Ch|Shch|Ya|Zh|Yu|Ts)")
def _stage_main(s):
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_extvowel")+")Ё", re.MULTILINE).sub("Yë", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_extvowel")+")ё", re.MULTILINE).sub("yë", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_extvowel")+")Е", re.MULTILINE).sub("YЕ", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")Е", re.MULTILINE).sub("Yе", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_extvowel")+")е", re.MULTILINE).sub("yе", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")е", re.MULTILINE).sub("yе", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_extvowel")+")Ё", re.MULTILINE).sub("Yë", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")Ё", re.MULTILINE).sub("Yë", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_extvowel")+")ё", re.MULTILINE).sub("yë", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")ё", re.MULTILINE).sub("yë", s)
    s = re.compile("Й(?="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_limvowel")+")", re.MULTILINE).sub("Y·", s)
    s = re.compile("й(?="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_limvowel")+")", re.MULTILINE).sub("y·", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_vowel")+")Ы(?="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_limvowel")+")", re.MULTILINE).sub("·Y·", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_vowel")+")ы(?="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_limvowel")+")", re.MULTILINE).sub("·y·", s)
    s = re.compile("Ы(?="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_limvowel")+")", re.MULTILINE).sub("Ы·", s)
    s = re.compile("ы(?="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_limvowel")+")", re.MULTILINE).sub("ы·", s)
    s = re.compile("(?<=[Оо])Ы", re.MULTILINE).sub("·Y", s)
    s = re.compile("(?<=[Оо])ы", re.MULTILINE).sub("·y", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")Ё", re.MULTILINE).sub("Yë", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")ё", re.MULTILINE).sub("yë", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_cons")+")Э", re.MULTILINE).sub("·E", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_cons")+")э", re.MULTILINE).sub("·e", s)
    s = re.compile("(?<=[Тт])"+interscript.stdlib.aliases["none"]+"(?=[Сс])", re.MULTILINE).sub("·", s)
    s = re.compile("(?<=[Шш])"+interscript.stdlib.aliases["none"]+"(?=[Чч])", re.MULTILINE).sub("·", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_3466712999575725692)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper")+")"+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar")+"", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper")+"·)"+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar")+"", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile(""+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar")+"(?=·"+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper")+")", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile(""+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar")+"(?="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper")+")", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper")+")"+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar")+"", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper")+"·)"+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar")+"", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile(""+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar")+"(?=·"+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper")+")", re.MULTILINE).sub(interscript.stdlib.upper, s)
    s = re.compile(""+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_multichar")+"(?="+interscript.stdlib.get_alias_re("bgnpcgn-rus-Cyrl-Latn-1947", "rus_latupper")+")", re.MULTILINE).sub(interscript.stdlib.upper, s)
    return s

interscript.stdlib.add_map_stage("bgnpcgn-rus-Cyrl-Latn-1947", "main", _stage_main)
_PTREE_3466712999575725692 = {1040:{None:"A"},1041:{None:"B"},1042:{None:"V"},1043:{None:"G"},1044:{None:"D"},1045:{None:"E"},1025:{None:"Ë"},1046:{None:"Zh"},1047:{None:"Z"},1048:{None:"I"},1049:{None:"Y"},1050:{None:"K"},1051:{None:"L"},1052:{None:"M"},1053:{None:"N"},1054:{None:"O"},1055:{None:"P"},1056:{None:"R"},1057:{None:"S"},1058:{None:"T"},1059:{None:"U"},1060:{None:"F"},1061:{None:"Kh"},1062:{None:"Ts"},1063:{None:"Ch"},1064:{None:"Sh"},1065:{None:"Shch"},1066:{None:"\""},1067:{None:"Y"},1068:{None:"’"},1069:{None:"E"},1070:{None:"Yu"},1071:{None:"Ya"},1072:{None:"a"},1073:{None:"b"},1074:{None:"v"},1075:{None:"g"},1076:{None:"d"},1077:{None:"e"},1105:{None:"ë"},1078:{None:"zh"},1079:{None:"z"},1080:{None:"i"},1081:{None:"y"},1082:{None:"k"},1083:{None:"l"},1084:{None:"m"},1085:{None:"n"},1086:{None:"o"},1087:{None:"p"},1088:{None:"r"},1089:{None:"s"},1090:{None:"t"},1091:{None:"u"},1092:{None:"f"},1093:{None:"kh"},1094:{None:"ts"},1095:{None:"ch"},1096:{None:"sh"},1097:{None:"shch"},1098:{None:"\""},1099:{None:"y"},1100:{None:"’"},1101:{None:"e"},1102:{None:"yu"},1103:{None:"ya"}}
