import interscript
import regex as re
interscript.stdlib.define_map("un-hin-Deva-Latn-2016")
interscript.stdlib.add_map_alias("un-hin-Deva-Latn-2016", "deva_characters_1", "ा")
interscript.stdlib.add_map_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1", "[ािीुूृॄॅेैॉोौ\\ ्]")
def _stage_main(s):
    s = re.compile("क=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("k", s)
    s = re.compile("क(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("k", s)
    s = re.compile("ख=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("ख(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("kh", s)
    s = re.compile("ग=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ग(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("g", s)
    s = re.compile("घ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("घ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("gh", s)
    s = re.compile("ङ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("ङ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("च=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("च(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ch", s)
    s = re.compile("छ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("chh", s)
    s = re.compile("छ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("chh", s)
    s = re.compile("ज=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("j", s)
    s = re.compile("ज(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("j", s)
    s = re.compile("झ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("झ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("jh", s)
    s = re.compile("ञ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ञ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ट=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ट(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ठ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("ठ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("ड=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("ड(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("ढ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ढ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ण=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ण(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("त=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("t", s)
    s = re.compile("त(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("t", s)
    s = re.compile("थ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("th", s)
    s = re.compile("थ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("th", s)
    s = re.compile("द=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("d", s)
    s = re.compile("द(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("d", s)
    s = re.compile("ध=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("ध(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("dh", s)
    s = re.compile("न=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("n", s)
    s = re.compile("न(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("n", s)
    s = re.compile("प=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("p", s)
    s = re.compile("प(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("p", s)
    s = re.compile("फ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("फ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ph", s)
    s = re.compile("ब=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("b", s)
    s = re.compile("ब(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("b", s)
    s = re.compile("भ=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("भ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("bh", s)
    s = re.compile("म=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("m", s)
    s = re.compile("म(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("m", s)
    s = re.compile("य=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("y", s)
    s = re.compile("य(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("y", s)
    s = re.compile("र=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("r", s)
    s = re.compile("र(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("r", s)
    s = re.compile("ल=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("l", s)
    s = re.compile("ल(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("l", s)
    s = re.compile("व=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("v", s)
    s = re.compile("व(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("v", s)
    s = re.compile("श=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("sh", s)
    s = re.compile("श(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("sh", s)
    s = re.compile("ष=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ṣh", s)
    s = re.compile("ष(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ṣh", s)
    s = re.compile("स=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("s", s)
    s = re.compile("स(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("s", s)
    s = re.compile("क़=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("q", s)
    s = re.compile("क़(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("q", s)
    s = re.compile("ख़=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ḳh", s)
    s = re.compile("ख़(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ḳh", s)
    s = re.compile("ग़=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ग़(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("g", s)
    s = re.compile("ज़=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("z", s)
    s = re.compile("ज़(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("z", s)
    s = re.compile("ड़=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ṙ", s)
    s = re.compile("ड़(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ṙ", s)
    s = re.compile("ढ़=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("ṙh", s)
    s = re.compile("ढ़(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ṙh", s)
    s = re.compile("फ़=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("f", s)
    s = re.compile("फ़(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("f", s)
    s = re.compile("ह=?(?="+interscript.stdlib.get_alias_re("un-hin-Deva-Latn-2016", "deva_characters_1")+")", re.MULTILINE).sub("h", s)
    s = re.compile("ह(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("h", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_3967966993204122822)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("un-hin-Deva-Latn-2016", "main", _stage_main)
_PTREE_3967966993204122822 = {2309:{None:"a"},2310:{None:"ā"},2311:{None:"i"},2312:{None:"ī"},2313:{None:"u"},2314:{None:"ū"},2315:{None:"ṛ"},2400:{None:"ṝ"},2316:{None:"l̤"},2319:{None:"e"},2320:{None:"ai"},2323:{None:"o"},2324:{None:"au"},2366:{None:"ā"},2377:{None:"ā̆ "},2367:{None:"i"},2368:{None:"ī"},2369:{None:"u"},2370:{None:"ū"},2371:{None:"ṛ"},2375:{None:"e"},2376:{None:"ai"},2379:{None:"o"},2380:{None:"au"},2325:{None:"ka",2364:{None:"qa",2381:{None:"q"}},2381:{None:"k"}},2326:{None:"kha",2364:{None:"ḳha",2381:{None:"ḳh"}},2381:{None:"kh"}},2327:{None:"ga",2364:{None:"ġa",2381:{None:"ġ"}},2381:{None:"g"}},2328:{None:"gha",2381:{None:"gh"}},2329:{None:"ṅa",2381:{None:"ṅ"}},2330:{None:"cha",2381:{None:"ch"}},2331:{None:"chha",2381:{None:"chh"}},2332:{None:"ja",2364:{None:"za",2381:{None:"z"}},2381:{None:"j"}},2333:{None:"jha",2381:{None:"jh"}},2334:{None:"ña",2381:{None:"ñ"}},2335:{None:"ṭa",2381:{None:"ṭ"}},2336:{None:"ṭha",2381:{None:"ṭh"}},2337:{None:"ḍa",2364:{None:"ṙa",2381:{None:"ṙ"}},2381:{None:"ḍ"}},2338:{None:"ḍha",2364:{None:"ṙha",2381:{None:"ṙh"}},2381:{None:"ḍh"}},2339:{None:"ṇa",2381:{None:"ṇ"}},2340:{None:"ta",2381:{None:"t"}},2341:{None:"tha",2381:{None:"th"}},2342:{None:"da",2381:{None:"d"}},2343:{None:"dha",2381:{None:"dh"}},2344:{None:"na",2381:{None:"n"}},2346:{None:"pa",2381:{None:"p"}},2347:{None:"pha",2364:{None:"fa",2381:{None:"f"}},2381:{None:"ph"}},2348:{None:"ba",2381:{None:"b"}},2349:{None:"bha",2381:{None:"bh"}},2350:{None:"ma",2381:{None:"m"}},2351:{None:"ya",2381:{None:"y"}},2352:{None:"ra",2381:{None:"r"}},2354:{None:"la",2381:{None:"l"}},2357:{None:"va",2381:{None:"v"}},2358:{None:"sha",2381:{None:"sh"}},2359:{None:"ṣha",2381:{None:"ṣh"}},2360:{None:"sa",2381:{None:"s"}},2361:{None:"ha"},2306:{None:"ṁ"},2305:{None:"m̐"},2381:{None:""},2307:{None:"ḥ"}}
