import interscript
import regex as re
interscript.stdlib.define_map("un-pan-Guru-Latn-1972")
def _stage_main(s):
    s = re.compile("(?<!ੱ)ਕ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("k", s)
    s = re.compile("(?<!ੱ)ਖ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("kh", s)
    s = re.compile("(?<!ੱ)[ਖ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ḳh", s)
    s = re.compile("(?<!ੱ)ਗ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("g", s)
    s = re.compile("(?<!ੱ)[ਗ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("g̣", s)
    s = re.compile("(?<!ੱ)ਘ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("gh", s)
    s = re.compile("(?<!ੱ)ਙ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṅ", s)
    s = re.compile("(?<!ੱ)ਚ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ch", s)
    s = re.compile("(?<!ੱ)ਛ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("chh", s)
    s = re.compile("(?<!ੱ)[ਜ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("z", s)
    s = re.compile("(?<!ੱ)ਜ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("j", s)
    s = re.compile("(?<!ੱ)ਝ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("jh", s)
    s = re.compile("(?<!ੱ)ਞ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ñ", s)
    s = re.compile("(?<!ੱ)ਟ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṭ", s)
    s = re.compile("(?<!ੱ)ਠ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṭh", s)
    s = re.compile("(?<!ੱ)ਡ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ḍ", s)
    s = re.compile("(?<!ੱ)ਢ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ḍh", s)
    s = re.compile("(?<!ੱ)ਣ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṇ", s)
    s = re.compile("(?<!ੱ)ਤ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("t", s)
    s = re.compile("(?<!ੱ)ਥ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("th", s)
    s = re.compile("(?<!ੱ)ਦ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("d", s)
    s = re.compile("(?<!ੱ)ਧ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("dh", s)
    s = re.compile("(?<!ੱ)ਨ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("n", s)
    s = re.compile("(?<!ੱ)ਪ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("p", s)
    s = re.compile("(?<!ੱ)ਫ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ph", s)
    s = re.compile("(?<!ੱ)[ਫ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("f", s)
    s = re.compile("(?<!ੱ)ਬ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("b", s)
    s = re.compile("(?<!ੱ)ਭ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("bh", s)
    s = re.compile("(?<!ੱ)ਮ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("m", s)
    s = re.compile("(?<!ੱ)ਯ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("y", s)
    s = re.compile("(?<!ੱ)ਰ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("r", s)
    s = re.compile("(?<!ੱ)ਲ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("l", s)
    s = re.compile("(?<!ੱ)[ਲੵ](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("l", s)
    s = re.compile("(?<!ੱ)[ਲ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("l", s)
    s = re.compile("(?<!ੱ)ਵ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("v", s)
    s = re.compile("(?<!ੱ)ੜ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṙ", s)
    s = re.compile("(?<!ੱ)ਸ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("s", s)
    s = re.compile("(?<!ੱ)ਸ਼(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("sh", s)
    s = re.compile("(?<!ੱ)ਹ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("h", s)
    s = re.compile("(?<=ੱ)ਕ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("kk", s)
    s = re.compile("(?<=ੱ)ਖ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("kkh", s)
    s = re.compile("(?<=ੱ)[ਖ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ḳḳh", s)
    s = re.compile("(?<=ੱ)ਗ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("gg", s)
    s = re.compile("(?<=ੱ)[ਗ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("gg̣", s)
    s = re.compile("(?<=ੱ)ਘ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ggh", s)
    s = re.compile("(?<=ੱ)ਙ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṅṅ", s)
    s = re.compile("(?<=ੱ)ਚ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("cch", s)
    s = re.compile("(?<=ੱ)ਛ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("cchh", s)
    s = re.compile("(?<=ੱ)[ਜ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("zz", s)
    s = re.compile("(?<=ੱ)ਜ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("jj", s)
    s = re.compile("(?<=ੱ)ਝ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("jjh", s)
    s = re.compile("(?<=ੱ)ਞ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ññ", s)
    s = re.compile("(?<=ੱ)ਟ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṭṭ", s)
    s = re.compile("(?<=ੱ)ਠ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṭṭh", s)
    s = re.compile("(?<=ੱ)ਡ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ḍḍ", s)
    s = re.compile("(?<=ੱ)ਢ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ḍḍh", s)
    s = re.compile("(?<=ੱ)ਣ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṇṇ", s)
    s = re.compile("(?<=ੱ)ਤ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("tt", s)
    s = re.compile("(?<=ੱ)ਥ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("tth", s)
    s = re.compile("(?<=ੱ)ਦ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("dd", s)
    s = re.compile("(?<=ੱ)ਧ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ddh", s)
    s = re.compile("(?<=ੱ)ਨ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("nn", s)
    s = re.compile("(?<=ੱ)ਪ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("pp", s)
    s = re.compile("(?<=ੱ)ਫ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("pph", s)
    s = re.compile("(?<=ੱ)[ਫ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ff", s)
    s = re.compile("(?<=ੱ)ਬ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("bb", s)
    s = re.compile("(?<=ੱ)ਭ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("bbh", s)
    s = re.compile("(?<=ੱ)ਮ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("mm", s)
    s = re.compile("(?<=ੱ)ਯ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("yy", s)
    s = re.compile("(?<=ੱ)ਰ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("rr", s)
    s = re.compile("(?<=ੱ)ਲ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ll", s)
    s = re.compile("(?<=ੱ)[ਲੵ](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ll", s)
    s = re.compile("(?<=ੱ)[ਲ਼](?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ll", s)
    s = re.compile("(?<=ੱ)ਵ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("vv", s)
    s = re.compile("(?<=ੱ)ੜ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ṙṙ", s)
    s = re.compile("(?<=ੱ)ਸ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ss", s)
    s = re.compile("(?<=ੱ)ਸ਼(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("ssh", s)
    s = re.compile("(?<=ੱ)ਹ(?=[ਾਿੀੁੂੇੈੋੌ੍])", re.MULTILINE).sub("hh", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_893437370504496593)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("un-pan-Guru-Latn-1972", "main", _stage_main)
_PTREE_893437370504496593 = {2565:{None:"a"},2566:{None:"ā"},2567:{None:"i"},2568:{None:"ī"},2569:{None:"u"},2570:{None:"ū"},2575:{None:"e"},2576:{None:"ai"},2579:{None:"o"},2580:{None:"au"},2622:{None:"ā"},2623:{None:"i"},2624:{None:"ī"},2625:{None:"u"},2626:{None:"ū"},2631:{None:"e"},2632:{None:"ai"},2635:{None:"o"},2636:{None:"au"},2581:{None:"ka"},2582:{None:"kha",2620:{None:"ḳha"}},2583:{None:"ga",2620:{None:"g̣a"}},2584:{None:"gha"},2585:{None:"ṅa"},2586:{None:"cha"},2587:{None:"chha"},2588:{2620:{None:"za"},None:"ja"},2589:{None:"jha"},2590:{None:"ña"},2591:{None:"ṭa"},2592:{None:"ṭha"},2593:{None:"ḍa"},2594:{None:"ḍha"},2595:{None:"ṇa"},2596:{None:"ta"},2597:{None:"tha"},2598:{None:"da"},2599:{None:"dha"},2600:{None:"na"},2602:{None:"pa"},2603:{None:"pha",2620:{None:"fa"}},2604:{None:"ba"},2605:{None:"bha"},2606:{None:"ma"},2607:{None:"ya"},2608:{None:"ra"},2610:{None:"la",2677:{None:"la"},2620:{None:"la"}},2613:{None:"va"},2652:{None:"ṙa"},2616:{None:"s"},2614:{None:"sha"},2617:{None:"h"},2562:{None:"ṁ"},2672:{None:"ṁ"},2673:{2581:{None:"kka",2637:{None:"kk"}},2582:{None:"kkha",2620:{None:"ḳḳha",2637:{None:"ḳḳh"}},2637:{None:"kkh"}},2583:{None:"gga",2620:{None:"gg̣a",2637:{None:"gg̣"}},2637:{None:"gg"}},2584:{None:"ggha",2637:{None:"ggh"}},2585:{None:"ṅṅa",2637:{None:"ṅṅ"}},2586:{None:"ccha",2637:{None:"cch"}},2587:{None:"cchha",2637:{None:"cchh"}},2588:{2620:{None:"zza",2637:{None:"zz"}},None:"jja",2637:{None:"jj"}},2589:{None:"jjha",2637:{None:"jjh"}},2590:{None:"ñña",2637:{None:"ññ"}},2591:{None:"ṭṭa",2637:{None:"ṭṭ"}},2592:{None:"ṭṭha",2637:{None:"ṭṭh"}},2593:{None:"ḍḍa",2637:{None:"ḍḍ"}},2594:{None:"ḍḍha",2637:{None:"ḍḍh"}},2595:{None:"ṇṇa",2637:{None:"ṇṇ"}},2596:{None:"tta",2637:{None:"tt"}},2597:{None:"ttha",2637:{None:"tth"}},2598:{None:"dda",2637:{None:"dd"}},2599:{None:"ddha",2637:{None:"ddh"}},2600:{None:"nna",2637:{None:"nn"}},2602:{None:"ppa",2637:{None:"pp"}},2603:{None:"ppha",2620:{None:"ffa",2637:{None:"ff"}},2637:{None:"pph"}},2604:{None:"bba",2637:{None:"bb"}},2605:{None:"bbha",2637:{None:"bbh"}},2606:{None:"mma",2637:{None:"mm"}},2607:{None:"yya",2637:{None:"yy"}},2608:{None:"rra",2637:{None:"rr"}},2610:{None:"lla",2677:{None:"lla",2637:{None:"ll"}},2620:{None:"lla",2637:{None:"ll"}},2637:{None:"ll"}},2613:{None:"vva",2637:{None:"vv"}},2652:{None:"ṙṙa",2637:{None:"ṙṙ"}},2616:{None:"ss",2637:{None:"ss"}},2614:{None:"ssha",2637:{None:"ssh"}},2617:{None:"hh",2637:{None:"hh"}},None:""},2637:{2617:{None:"-h"},2613:{None:"-v"},2608:{None:"-r"},2607:{None:"-y"},None:""},2620:{None:""},2662:{None:"0"},2663:{None:"1"},2664:{None:"2"},2665:{None:"3"},2666:{None:"4"},2667:{None:"5"},2668:{None:"6"},2669:{None:"7"},2670:{None:"8"},2671:{None:"9"}}
