import interscript
import regex as re
interscript.stdlib.define_map("var-kor")
interscript.stdlib.add_map_alias("var-kor", "hangul", "가")
interscript.stdlib.add_map_alias_re("var-kor", "hangul", "[가-힯]")
interscript.stdlib.add_map_alias("var-kor", "jamo_leading_cons", "ᄀ")
interscript.stdlib.add_map_alias_re("var-kor", "jamo_leading_cons", "(?:[ᄀ-ᅞ]|[ꥠ-ꥼ])")
interscript.stdlib.add_map_alias("var-kor", "jamo_vowel", "ᅡ")
interscript.stdlib.add_map_alias_re("var-kor", "jamo_vowel", "(?:[ᅡ-ᆧ]|[ힰ-ퟆ])")
interscript.stdlib.add_map_alias("var-kor", "jamo_trailing_cons", "ᆨ")
interscript.stdlib.add_map_alias_re("var-kor", "jamo_trailing_cons", "(?:[ᆨ-ᇿ]|[ퟋ-ퟻ])")
interscript.stdlib.add_map_alias("var-kor", "jamo", interscript.stdlib.get_alias("var-kor", "jamo_leading_cons"))
interscript.stdlib.add_map_alias_re("var-kor", "jamo", "(?:"+interscript.stdlib.get_alias_re("var-kor", "jamo_leading_cons")+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_vowel")+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo_trailing_cons")+")")
interscript.stdlib.add_map_alias("var-kor", "hangul_or_jamo", interscript.stdlib.get_alias("var-kor", "hangul"))
interscript.stdlib.add_map_alias_re("var-kor", "hangul_or_jamo", "(?:"+interscript.stdlib.get_alias_re("var-kor", "hangul")+"|"+interscript.stdlib.get_alias_re("var-kor", "jamo")+")")
interscript.stdlib.add_map_alias("var-kor", "double_cons_jamo", "ᄁ")
interscript.stdlib.add_map_alias_re("var-kor", "double_cons_jamo", "[ᄁᄄᄈᄍᄊ]")
interscript.stdlib.add_map_alias("var-kor", "aspirated_cons_jamo", "ᄏ")
interscript.stdlib.add_map_alias_re("var-kor", "aspirated_cons_jamo", "[ᄏᄐᄑᄎ]")
