"""
Globals
"""

GARLAND_TOOLS_ENDPOINT = 'https://www.garlandtools.org/'
GARLAND_LANGUAGE_TOKEN = "GARLAND_TOOLS_LANGUAGE"

GARLAND_TOOLS_ACHIEVEMENT_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'achievement/GARLAND_TOOLS_LANGUAGE/2/'
GARLAND_TOOLS_ACHIEVEMENTS_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/achievement.json'

GARLAND_TOOLS_DATA_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'core/GARLAND_TOOLS_LANGUAGE/3/data.json'

GARLAND_TOOLS_LEVELLING_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'equip/GARLAND_TOOLS_LANGUAGE/2/leveling-'
GARLAND_TOOLS_ENDGAME_GEAR_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'equip/GARLAND_TOOLS_LANGUAGE/2/end-'

GARLAND_TOOLS_FATE_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'fate/GARLAND_TOOLS_LANGUAGE/2/'
GARLAND_TOOLS_FATES_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/fate.json'

GARLAND_TOOLS_FISHING_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/fishing.json'

GARLAND_TOOLS_ICON_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}files/icons/'

GARLAND_TOOLS_INSTANCE_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'instance/GARLAND_TOOLS_LANGUAGE/2/'
GARLAND_TOOLS_INSTANCES_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/instance.json'

GARLAND_TOOLS_ITEM_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/item/GARLAND_TOOLS_LANGUAGE/3/'

GARLAND_TOOLS_LEVE_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'leve/GARLAND_TOOLS_LANGUAGE/3/'
GARLAND_TOOLS_LEVES_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/leve.json'

GARLAND_TOOLS_MAP_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}files/maps/'

GARLAND_TOOLS_MOB_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'mob/GARLAND_TOOLS_LANGUAGE/2/'
GARLAND_TOOLS_MOBS_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/mob.json'

GARLAND_TOOLS_NODE_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'node/GARLAND_TOOLS_LANGUAGE/2/'
GARLAND_TOOLS_NODES_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/node.json'

GARLAND_TOOLS_NPC_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'npc/GARLAND_TOOLS_LANGUAGE/2/'
GARLAND_TOOLS_NPCS_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/npc.json'

GARLAND_TOOLS_QUEST_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'quest/GARLAND_TOOLS_LANGUAGE/2/'
GARLAND_TOOLS_QUESTS_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/quest.json'

GARLAND_TOOLS_SEARCH_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}api/search.php'

GARLAND_TOOLS_STATUS_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'Status/GARLAND_TOOLS_LANGUAGE/2/'
GARLAND_TOOLS_STATUSES_ENDPOINT = f'{GARLAND_TOOLS_ENDPOINT}db/doc/' \
    + 'browse/GARLAND_TOOLS_LANGUAGE/2/status.json'
