#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class iso_clip_child:
    fluent_name = ...
    child_names = ...
    name = ...
    field = ...
    surfaces = ...
    min = ...
    max = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

