#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class point_surface_child:
    fluent_name = ...
    child_names = ...
    name = ...
    reference_frame = ...
    point = ...
    snap_method = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

