#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class single_valued_expression_child:
    fluent_name = ...
    child_names = ...
    name = ...
    average_over = ...
    retain_instantaneous_values = ...
    definition = ...
    list_valid_report_names = ...
    command_names = ...

    def create_output_parameter(self, ):
        """
        'create_output_parameter' command.
        """

