#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class transform_surface_child:
    fluent_name = ...
    child_names = ...
    name = ...
    surface = ...
    center_of_rotation = ...
    angle_of_rotation = ...
    translation_distance = ...
    iso_distance = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

