import interscript
import regex as re
interscript.load_map("var-kor-Hang-Hang-jamo")
interscript.stdlib.define_map("var-kor-Hang-Latn-mr-1939")
interscript.stdlib.add_map_alias("var-kor-Hang-Latn-mr-1939", "kor_beforeterm", "A")
interscript.stdlib.add_map_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm", "(?:[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ])")
interscript.stdlib.add_map_alias("var-kor-Hang-Latn-mr-1939", "kor_maybedash", "-")
interscript.stdlib.add_map_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash", "(\\-?)")
def _stage_main(s):
    s = interscript.transliterate("var-kor-Hang-Hang-jamo", s, "main")
    s = re.compile(""+interscript.stdlib.aliases["line_start"]+"", re.MULTILINE).sub(" ", s)
    s = re.compile(""+interscript.stdlib.aliases["line_end"]+"", re.MULTILINE).sub(" ", s)
    s = re.compile("ᆩ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆨ"+"\\1"+"ᄁ", s)
    s = re.compile("ᆩ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆨ"+"\\1", s)
    s = re.compile("ᆪ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆨ"+"\\1"+"ᄉ", s)
    s = re.compile("ᆪ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆨ"+"\\1", s)
    s = re.compile("ᆬ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆫ"+"\\1"+"ᄌ", s)
    s = re.compile("ᆬ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆫ"+"\\1", s)
    s = re.compile("ᆭ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("ᆫ"+"\\1"+"ᄏ", s)
    s = re.compile("ᆭ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("ᆫ"+"\\1"+"ᄐ", s)
    s = re.compile("ᆭ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("ᆫ"+"\\1"+"ᄑ", s)
    s = re.compile("ᆭ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("ᆫ"+"\\1"+"ᄎ", s)
    s = re.compile("ᆭ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆫ"+"\\1", s)
    s = re.compile("ᆮ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"(?=[ᄀᄁᄂᄃᄄᄅᄆᄇᄈᄉᄊᄌᄍᄎᄏᄐᄑᄒ])", re.MULTILINE).sub("ᆺ"+"\\1", s)
    s = re.compile("ᆳ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆯ"+"\\1"+"ᄉ", s)
    s = re.compile("ᆳ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆯ"+"\\1", s)
    s = re.compile("ᆴ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆯ"+"\\1"+"ᄐ", s)
    s = re.compile("ᆴ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆯ"+"\\1", s)
    s = re.compile("ᆵ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆯ"+"\\1"+"ᄑ", s)
    s = re.compile("ᆵ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"(?=[ᄃᄄᄐ])", re.MULTILINE).sub("ᆯ"+"\\1", s)
    s = re.compile("ᆵ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᄇ"+"\\1", s)
    s = re.compile("ᆶ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("ᆯ"+"\\1"+"ᄏ", s)
    s = re.compile("ᆶ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("ᆯ"+"\\1"+"ᄐ", s)
    s = re.compile("ᆶ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("ᆯ"+"\\1"+"ᄑ", s)
    s = re.compile("ᆶ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("ᆯ"+"\\1"+"ᄎ", s)
    s = re.compile("ᆶ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆯ"+"\\1", s)
    s = re.compile("ᆹ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᄇ"+"\\1"+"ᄉ", s)
    s = re.compile("ᆹ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᄇ"+"\\1", s)
    s = re.compile("ᆻ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆺ"+"\\1"+"ᄊ", s)
    s = re.compile("ᆻ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆺ"+"\\1", s)
    s = re.compile("ᆽ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆺ"+"\\1"+"ᄌ", s)
    s = re.compile("ᆽ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆺ"+"\\1", s)
    s = re.compile("ᆾ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆺ"+"\\1"+"ᄎ", s)
    s = re.compile("ᆾ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆺ"+"\\1", s)
    s = re.compile("ᆿ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆨ"+"\\1"+"ᄏ", s)
    s = re.compile("ᆿ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆨ"+"\\1", s)
    s = re.compile("ᇀ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆺ"+"\\1"+"ᄐ", s)
    s = re.compile("ᇀ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆺ"+"\\1", s)
    s = re.compile("ᇁ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ᆸ"+"\\1"+"ᄑ", s)
    s = re.compile("ᇁ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("ᆸ"+"\\1", s)
    s = re.compile("ᇂ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("\\1"+"ᄏ", s)
    s = re.compile("ᇂ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("\\1"+"ᄐ", s)
    s = re.compile("ᇂ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("\\1"+"ᄑ", s)
    s = re.compile("ᇂ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("\\1"+"ᄎ", s)
    s = re.compile("ᇂ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"", re.MULTILINE).sub("\\1", s)
    s = re.compile("ᆮ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("\\1"+"d", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("k"+"\\1"+"k", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("ng"+"\\1"+"n", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("k"+"\\1"+"ch", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("k"+"\\1"+"t", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("ng"+"\\1"+"n", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("ng"+"\\1"+"m", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("k"+"\\1"+"p", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("k"+"\\1"+"s", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("\\1"+"g", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("k"+"\\1"+"ch", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("k"+"\\1"+"ch’", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("k"+"\\1"+"k’", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("k"+"\\1"+"ch’", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("k"+"\\1"+"t’", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("k"+"\\1"+"p’", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("k"+"\\1"+"h", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("k"+"\\1"+"k", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("k"+"\\1"+"tt", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("k"+"\\1"+"pp", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("k"+"\\1"+"ss", s)
    s = re.compile("ᆨ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("k"+"\\1"+"tch", s)
    s = re.compile("ᆫᄀ", re.MULTILINE).sub("n’g", s)
    s = re.compile("ᆫ(\\-)ᄀ", re.MULTILINE).sub("n"+"\\1"+"g", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("n"+"\\1"+"n", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("n"+"\\1"+"j", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("n"+"\\1"+"d", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("l"+"\\1"+"l", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("n"+"\\1"+"m", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("n"+"\\1"+"b", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("n"+"\\1"+"s", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("n"+"\\1", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("n"+"\\1"+"j", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("n"+"\\1"+"ch’", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("n"+"\\1"+"k’", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("n"+"\\1"+"ch’", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("n"+"\\1"+"t’", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("n"+"\\1"+"p’", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("n"+"\\1"+"h", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("n"+"\\1"+"kk", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("n"+"\\1"+"tt", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("n"+"\\1"+"pp", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("n"+"\\1"+"ss", s)
    s = re.compile("ᆫ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("n"+"\\1"+"tch", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("l"+"\\1"+"g", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("l"+"\\1"+"l", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("l"+"\\1"+"ch", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("l"+"\\1"+"t", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("l"+"\\1"+"l", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("l"+"\\1"+"m", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("l"+"\\1"+"b", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("l"+"\\1"+"s", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("\\1"+"r", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("l"+"\\1"+"ch", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("l"+"\\1"+"ch’", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("l"+"\\1"+"k’", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("l"+"\\1"+"ch’", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("l"+"\\1"+"t’", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("l"+"\\1"+"p’", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("r"+"\\1"+"h", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("l"+"\\1"+"kk", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("l"+"\\1"+"tt", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("l"+"\\1"+"pp", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("l"+"\\1"+"ss", s)
    s = re.compile("ᆯ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("l"+"\\1"+"tch", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("m"+"\\1"+"g", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("m"+"\\1"+"n", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("m"+"\\1"+"j", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("m"+"\\1"+"d", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("m"+"\\1"+"n", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("m"+"\\1"+"m", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("m"+"\\1"+"b", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("m"+"\\1"+"s", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("m"+"\\1", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("m"+"\\1"+"j", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("m"+"\\1"+"ch’", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("m"+"\\1"+"k’", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("m"+"\\1"+"ch’", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("m"+"\\1"+"t’", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("m"+"\\1"+"p’", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("m"+"\\1"+"h", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("m"+"\\1"+"kk", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("m"+"\\1"+"tt", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("m"+"\\1"+"pp", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("m"+"\\1"+"ss", s)
    s = re.compile("ᆷ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("m"+"\\1"+"tch", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("p"+"\\1"+"k", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("m"+"\\1"+"n", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("p"+"\\1"+"ch", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("p"+"\\1"+"t", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("m"+"\\1"+"n", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("m"+"\\1"+"m", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("p"+"\\1"+"p", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("p"+"\\1"+"s", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("p"+"\\1", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("p"+"\\1"+"ch", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("p"+"\\1"+"ch’", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("p"+"\\1"+"k’", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("p"+"\\1"+"ch’", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("p"+"\\1"+"t’", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("p"+"\\1"+"p’", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("p"+"\\1"+"h", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("p"+"\\1"+"kk", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("p"+"\\1"+"tt", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("p"+"\\1"+"p", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("p"+"\\1"+"ss", s)
    s = re.compile("ᆸ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("p"+"\\1"+"tch", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("t"+"\\1"+"k", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("n"+"\\1"+"n", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("t"+"\\1"+"ch", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("t"+"\\1"+"t", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("n"+"\\1"+"n", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("n"+"\\1"+"m", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("t"+"\\1"+"p", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("s"+"\\1"+"s", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("s"+"\\1", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("t"+"\\1"+"ch", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("t"+"\\1"+"ch’", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("t"+"\\1"+"k’", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("t"+"\\1"+"ch’", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("t"+"\\1"+"t’", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("t"+"\\1"+"p’", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("t"+"\\1"+"h", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("t"+"\\1"+"kk", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("t"+"\\1"+"t", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("t"+"\\1"+"pp", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("s"+"\\1"+"s", s)
    s = re.compile("ᆺ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("t"+"\\1"+"ch", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("ng"+"\\1"+"g", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("ng"+"\\1"+"n", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("ng"+"\\1"+"j", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("ng"+"\\1"+"d", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("ng"+"\\1"+"n", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("ng"+"\\1"+"m", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("ng"+"\\1"+"b", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("ng"+"\\1"+"s", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("ng"+"\\1", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("ng"+"\\1"+"j", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("ng"+"\\1"+"ch’", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("ng"+"\\1"+"k’", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("ng"+"\\1"+"ch’", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("ng"+"\\1"+"t’", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("ng"+"\\1"+"p’", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("ng"+"\\1"+"h", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("ng"+"\\1"+"kk", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("ng"+"\\1"+"tt", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("ng"+"\\1"+"pp", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("ng"+"\\1"+"ss", s)
    s = re.compile("ᆼ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("ng"+"\\1"+"tch", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("\\1"+"g", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("\\1"+"n", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("\\1"+"j", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("\\1"+"d", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("\\1"+"r", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("\\1"+"m", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("\\1"+"b", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("\\1"+"s", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("\\1", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("\\1"+"j", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("\\1"+"ch’", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("\\1"+"k’", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("\\1"+"ch’", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("\\1"+"t’", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("\\1"+"p’", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("\\1"+"h", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("\\1"+"kk", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("\\1"+"tt", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("\\1"+"pp", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("\\1"+"ss", s)
    s = re.compile("(?<="+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_beforeterm")+")"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("\\1"+"tch", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("l"+"\\1"+"g", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("ng"+"\\1"+"n", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("k"+"\\1"+"t", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("ng"+"\\1"+"n", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("ng"+"\\1"+"m", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("k"+"\\1"+"p", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("k"+"\\1"+"s", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("l"+"\\1"+"g", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("k"+"\\1"+"ch", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("k"+"\\1"+"ch’", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("l"+"\\1"+"k’", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("k"+"\\1"+"ch’", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("k"+"\\1"+"t’", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("k"+"\\1"+"p’", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("lk"+"\\1"+"h", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("l"+"\\1"+"kk", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("k"+"\\1"+"tt", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("k"+"\\1"+"pp", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("k"+"\\1"+"ss", s)
    s = re.compile("ᆰ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("k"+"\\1"+"tch", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("m"+"\\1"+"g", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("m"+"\\1"+"n", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("m"+"\\1"+"d", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("m"+"\\1"+"n", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("l"+"\\1"+"m", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("m"+"\\1"+"b", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("m"+"\\1"+"s", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("l"+"\\1"+"m", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("m"+"\\1"+"j", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("m"+"\\1"+"ch’", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("m"+"\\1"+"k’", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("m"+"\\1"+"ch’", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("m"+"\\1"+"t’", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("m"+"\\1"+"p’", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("m"+"\\1"+"h", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("m"+"\\1"+"kk", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("m"+"\\1"+"tt", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("m"+"\\1"+"pp", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("m"+"\\1"+"ss", s)
    s = re.compile("ᆱ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("m"+"\\1"+"tch", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄀ", re.MULTILINE).sub("pk", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄂ", re.MULTILINE).sub("mn", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄃ", re.MULTILINE).sub("p"+"\\1"+"t", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄅ", re.MULTILINE).sub("m"+"\\1"+"n", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄆ", re.MULTILINE).sub("m"+"\\1"+"m", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄇ", re.MULTILINE).sub("l"+"\\1"+"b", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄉ", re.MULTILINE).sub("p"+"\\1"+"s", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄋ", re.MULTILINE).sub("l"+"\\1"+"b", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄌ", re.MULTILINE).sub("p"+"\\1"+"ch", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄎ", re.MULTILINE).sub("p"+"\\1"+"ch’", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄏ", re.MULTILINE).sub("p"+"\\1"+"k’", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("p"+"\\1"+"ch’", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄐ", re.MULTILINE).sub("p"+"\\1"+"t’", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄑ", re.MULTILINE).sub("l"+"\\1"+"p’", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄒ", re.MULTILINE).sub("lp"+"\\1"+"h", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄁ", re.MULTILINE).sub("p"+"\\1"+"kk", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄄ", re.MULTILINE).sub("p"+"\\1"+"tt", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄈ", re.MULTILINE).sub("l"+"\\1"+"pp", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄊ", re.MULTILINE).sub("p"+"\\1"+"ss", s)
    s = re.compile("ᆲ"+interscript.stdlib.get_alias_re("var-kor-Hang-Latn-mr-1939", "kor_maybedash")+"ᄍ", re.MULTILINE).sub("p"+"\\1"+"tch", s)
    s = re.compile("(?<=\\ )ᄀ", re.MULTILINE).sub("k", s)
    s = re.compile("(?<=\\ )ᄂ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("", s)
    s = re.compile("(?<=\\ )ᄂ", re.MULTILINE).sub("n", s)
    s = re.compile("(?<=\\ )ᄃ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("ch", s)
    s = re.compile("(?<=\\ )ᄃ", re.MULTILINE).sub("t", s)
    s = re.compile("(?<=\\ )ᄅ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("", s)
    s = re.compile("(?<=\\ )ᄅ", re.MULTILINE).sub("n", s)
    s = re.compile("(?<=\\ )ᄆ", re.MULTILINE).sub("m", s)
    s = re.compile("(?<=\\ )ᄇ", re.MULTILINE).sub("p", s)
    s = re.compile("(?<=\\ )ᄉ(?=ᅱ)", re.MULTILINE).sub("sh", s)
    s = re.compile("(?<=\\ )ᄉ", re.MULTILINE).sub("s", s)
    s = re.compile("(?<=\\ )ᄋ", re.MULTILINE).sub("", s)
    s = re.compile("(?<=\\ )ᄌ", re.MULTILINE).sub("ch", s)
    s = re.compile("(?<=\\ )ᄎ", re.MULTILINE).sub("ch’", s)
    s = re.compile("(?<=\\ )ᄏ", re.MULTILINE).sub("k’", s)
    s = re.compile("(?<=\\ )ᄐ(?=[ᅵᅣᅤᅧᅨᅭᅲ])", re.MULTILINE).sub("ch’", s)
    s = re.compile("(?<=\\ )ᄐ", re.MULTILINE).sub("t’", s)
    s = re.compile("(?<=\\ )ᄑ", re.MULTILINE).sub("p’", s)
    s = re.compile("(?<=\\ )ᄒ", re.MULTILINE).sub("h", s)
    s = re.compile("(?<=\\ )ᄁ", re.MULTILINE).sub("kk", s)
    s = re.compile("(?<=\\ )ᄭ", re.MULTILINE).sub("kk", s)
    s = re.compile("(?<=\\ )ᄄ", re.MULTILINE).sub("tt", s)
    s = re.compile("(?<=\\ )ᄯ", re.MULTILINE).sub("tt", s)
    s = re.compile("(?<=\\ )ᄈ", re.MULTILINE).sub("pp", s)
    s = re.compile("(?<=\\ )ᄲ", re.MULTILINE).sub("pp", s)
    s = re.compile("(?<=\\ )ᄊ", re.MULTILINE).sub("ss", s)
    s = re.compile("(?<=\\ )ᄍ", re.MULTILINE).sub("tch", s)
    s = re.compile("(?<=\\ )ᄶ", re.MULTILINE).sub("tch", s)
    s = re.compile("ᅡ", re.MULTILINE).sub("a", s)
    s = re.compile("ᅣ", re.MULTILINE).sub("ya", s)
    s = re.compile("ᅥ", re.MULTILINE).sub("ŏ", s)
    s = re.compile("ᅧ", re.MULTILINE).sub("yŏ", s)
    s = re.compile("ᅩ", re.MULTILINE).sub("o", s)
    s = re.compile("ᅭ", re.MULTILINE).sub("yo", s)
    s = re.compile("ᅮ", re.MULTILINE).sub("u", s)
    s = re.compile("ᅲ", re.MULTILINE).sub("yu", s)
    s = re.compile("ᅳ", re.MULTILINE).sub("ŭ", s)
    s = re.compile("ᅵ", re.MULTILINE).sub("i", s)
    s = re.compile("ᅢ", re.MULTILINE).sub("ae", s)
    s = re.compile("ᅤ", re.MULTILINE).sub("yae", s)
    s = re.compile("ᅦ", re.MULTILINE).sub("e", s)
    s = re.compile("ᅨ", re.MULTILINE).sub("ye", s)
    s = re.compile("ᅬ", re.MULTILINE).sub("oe", s)
    s = re.compile("ᅱ", re.MULTILINE).sub("wi", s)
    s = re.compile("ᅴ", re.MULTILINE).sub("ŭi", s)
    s = re.compile("ᅪ", re.MULTILINE).sub("wa", s)
    s = re.compile("ᅯ", re.MULTILINE).sub("wŏ", s)
    s = re.compile("ᅫ", re.MULTILINE).sub("wae", s)
    s = re.compile("ᅰ", re.MULTILINE).sub("we", s)
    s = re.compile("ᆨ(?=[\\ \\-])", re.MULTILINE).sub("k", s)
    s = re.compile("ᆫ(?=[\\ \\-])", re.MULTILINE).sub("n", s)
    s = re.compile("ᆮ(?=[\\ \\-])", re.MULTILINE).sub("t", s)
    s = re.compile("ᆯ(?=[\\ \\-])", re.MULTILINE).sub("l", s)
    s = re.compile("ᆷ(?=[\\ \\-])", re.MULTILINE).sub("m", s)
    s = re.compile("ᆸ(?=[\\ \\-])", re.MULTILINE).sub("p", s)
    s = re.compile("ᆺ(?=[\\ \\-])", re.MULTILINE).sub("t", s)
    s = re.compile("ᆼ(?=[\\ \\-])", re.MULTILINE).sub("ng", s)
    s = re.compile("ᆽ(?=[\\ \\-])", re.MULTILINE).sub("t", s)
    s = re.compile("ᆾ(?=[\\ \\-])", re.MULTILINE).sub("t", s)
    s = re.compile("ᆿ(?=[\\ \\-])", re.MULTILINE).sub("k", s)
    s = re.compile("ᇀ(?=[\\ \\-])", re.MULTILINE).sub("t", s)
    s = re.compile("ᇁ(?=[\\ \\-])", re.MULTILINE).sub("p", s)
    s = re.compile("ᆰ(?=[\\ \\-])", re.MULTILINE).sub("k", s)
    s = re.compile("ᆲ(?=[\\ \\-])", re.MULTILINE).sub("p", s)
    s = re.compile("((?:ch|ch’|j|s|ss))y", re.MULTILINE).sub("\\1", s)
    s = re.compile("swi", re.MULTILINE).sub("shwi", s)
    s = re.compile(""+interscript.stdlib.aliases["line_start"]+"\\ ", re.MULTILINE).sub("", s)
    s = re.compile("\\ "+interscript.stdlib.aliases["line_end"]+"", re.MULTILINE).sub("", s)
    s = interscript.functions.decompose(s, {})
    return s

interscript.stdlib.add_map_stage("var-kor-Hang-Latn-mr-1939", "main", _stage_main)
