#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class aeromechanics_child:
    fluent_name = ...
    child_names = ...
    name = ...
    report_type = ...
    zones = ...
    per_zone = ...
    nodal_diameters = ...
    average_over = ...
    integrate_over = ...
    normalization = ...
    realcomponent = ...
    command_names = ...

    def create_output_parameter(self, ):
        """
        'create_output_parameter' command.
        """

