#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class rake_surface_child:
    fluent_name = ...
    child_names = ...
    name = ...
    p0 = ...
    p1 = ...
    number_of_points = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

