# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/common/options_with_hash.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truera.protobuf.public import common_pb2 as truera_dot_protobuf_dot_public_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5truera/protobuf/public/common/options_with_hash.proto\x12\x06truera\x1a#truera/protobuf/public/common.proto\"\xb1\x01\n\x0fOptionsWithHash\x12\x14\n\x0coptions_hash\x18\x01 \x01(\t\x12\x37\n\x12prediction_options\x18\x02 \x01(\x0b\x32\x19.truera.PredictionOptionsH\x00\x12\x44\n\x19\x66\x65\x61ture_influence_options\x18\x03 \x01(\x0b\x32\x1f.truera.FeatureInfluenceOptionsH\x00\x42\t\n\x07optionsBb\n\x13\x63om.truera.protobufB\x14OptionsWithHashProtoP\x01Z3truera.com/protobuf/public/common/options_with_hashb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.common.options_with_hash_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.truera.protobufB\024OptionsWithHashProtoP\001Z3truera.com/protobuf/public/common/options_with_hash'
  _globals['_OPTIONSWITHHASH']._serialized_start=103
  _globals['_OPTIONSWITHHASH']._serialized_end=280
# @@protoc_insertion_point(module_scope)
