# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/util/elementary_types.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2truera/protobuf/public/util/elementary_types.proto\"\x1b\n\tFloatList\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1d\n\x0bIntegerList\x12\x0e\n\x06values\x18\x01 \x03(\x03\"(\n\nNestedList\x12\x1a\n\x06values\x18\x01 \x03(\x0b\x32\n.ValueList\"\x82\x01\n\tValueList\x12\x1a\n\x06\x66loats\x18\x01 \x01(\x0b\x32\n.FloatList\x12\x1c\n\x07strings\x18\x02 \x01(\x0b\x32\x0b.StringList\x12\x1e\n\x08integers\x18\x03 \x01(\x0b\x32\x0c.IntegerList\x12\x1b\n\x06nested\x18\x04 \x01(\x0b\x32\x0b.NestedListBd\n\x18\x63om.truera.protobuf.utilB\x14\x45lementaryTypesProtoP\x01Z0truera.com/protobuf/public/util/elementary_typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.util.elementary_types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.truera.protobuf.utilB\024ElementaryTypesProtoP\001Z0truera.com/protobuf/public/util/elementary_types'
  _globals['_FLOATLIST']._serialized_start=54
  _globals['_FLOATLIST']._serialized_end=81
  _globals['_STRINGLIST']._serialized_start=83
  _globals['_STRINGLIST']._serialized_end=111
  _globals['_INTEGERLIST']._serialized_start=113
  _globals['_INTEGERLIST']._serialized_end=142
  _globals['_NESTEDLIST']._serialized_start=144
  _globals['_NESTEDLIST']._serialized_end=184
  _globals['_VALUELIST']._serialized_start=187
  _globals['_VALUELIST']._serialized_end=317
# @@protoc_insertion_point(module_scope)
