
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-05T08:18:18-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f5c25cfd0471c02a861ec86afc4b7418520d358",
 "version": "3.0.2.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
