DefaultCommonOptions = {
    "key": None,
    "authUrl": None,
    "refreshUrl": None,
    "revokeUrl": None,
    "authBody": {},
    "authHeaders": {},
    "authTokenName": "pubq.authToken",
    "autoConnect": True,
    "autoReconnect": True,
    "autoAuthenticate": True,
    "autoRefreshToken": True,
    "refreshTokenInterval": 1000,
    "autoSubscribeOnConnect": True,
    "connectTimeout": 20000,
    "ackTimeout": 10000,
    "timestampRequests": False,
    "timestampParam": "t",
    "binaryType": "arraybuffer",
    "batchOnHandshake": False,
    "batchOnHandshakeDuration": 100,
    "batchInterval": 50,
    "protocolVersion": 2,
    "wsOptions": {},
    "cloneData": False
}
