#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class battery:
    fluent_name = ...
    child_names = ...
    enabled = ...
    solution_method = ...
    echem_model = ...
    zone_assignment = ...
    contact_resistance = ...
    ntgk_model_settings = ...
    ecm_model_settings = ...
    p2d_model_settings = ...
    eload_condition = ...
    echem_stop_criterion = ...
    cell_clustering = ...
    solution_option = ...
    life_model = ...
    swelling_model = ...
    thermal_abuse_model = ...
    pack_builder = ...
    rom_tool_kit = ...
    orthotropic_k = ...
    udf_hooks = ...
    command_names = ...

    def parameter_estimation_tool(self, ):
        """
        'parameter_estimation_tool' command.
        """

    def standalone_echem_model(self, ):
        """
        'standalone_echem_model' command.
        """

