#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class lti_rom_generation:
    fluent_name = ...
    child_names = ...
    lti_folder_name = ...
    user_config = ...
    min_order = ...
    max_order = ...
    rel_error = ...
    tolerance_0th_order = ...
    slope_method = ...
    command_names = ...

    def run_rom_generation(self, ):
        """
        Non-conformal Interface Matching.
        """

