#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class surface_child:
    fluent_name = ...
    child_names = ...
    name = ...
    report_type = ...
    field = ...
    surface_names = ...
    per_surface = ...
    average_over = ...
    retain_instantaneous_values = ...
    custom_vector = ...
    phase = ...
    physics = ...
    geometry = ...
    surfaces = ...
    command_names = ...

    def create_output_parameter(self, ):
        """
        'create_output_parameter' command.
        """

