#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class anisotropic_adaption:
    fluent_name = ...
    child_names = ...
    operations = ...
    iterations = ...
    fixed_zones = ...
    indicator = ...
    target = ...
    command_names = ...

    def adapt_mesh(self, ):
        """
        Adapt the mesh based on specified anisotropic adaption setup.
        """

