#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class unsteady_tracking:
    fluent_name = ...
    child_names = ...
    option = ...
    particle_creation_every_particle_step_enabled = ...
    dpm_time_step = ...
    n_time_steps = ...
    command_names = ...

    def clear_particles_from_domain(self, ):
        """
        Clear all particles currently in the domain.
        """

