#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class windows:
    fluent_name = ...
    child_names = ...
    axes = ...
    main = ...
    scale = ...
    text = ...
    video = ...
    xy = ...
    logo = ...
    ruler = ...
    logo_color = ...
    command_names = ...

    def aspect_ratio(self, width: Union[float, str], height: Union[float, str]):
        """
        Set the aspect ratio of the active window.
        
        Parameters
        ----------
            width : real
                'width' child.
            height : real
                'height' child.
        
        """

