__version__ = "0.0.2"
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00__init__.ipynb.

# %% auto 0
__all__ = ['loadmod']

# %% ../nbs/00__init__.ipynb 3
from itertools import chain
from types import ModuleType
from importlib import import_module

def loadmod(mod: ModuleType):
    if hasattr(mod, '__all__'): return mod.__all__
    if hasattr(mod, '__module__'): return loadmod(import_module(mod.__module__))
    raise AttributeError(f"module {mod} has no attribute '__all__'")

# %% ../nbs/00__init__.ipynb 4
from . import (cons, type, prot, enum, errs, solo, grds, util, zero, meta, base, mods, spec, duck)
from .cons import *
from .type import *
from .prot import *
from .enum import *
from .errs import *
from .solo import *
from .grds import *
from .util import *
# from quac.zero import *
# from quac.meta import *
from .base import *
# from quac.mods import *
# from quac.spec import *
from .duck import *
