# coding: utf-8

# flake8: noqa
"""
    Auth Service

    This API provides token-based authentication for user registration, login, and client credential management. It ensures secure communication by utilizing tokens for authentication. Users can register with unique usernames and passwords, authenticate using client credentials, retrieve client IDs and secrets, and regenerate client credentials as needed. The API supports various user roles, including 'user', 'admin', 'moderator', 'guest', and 'superadmin'.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from authservice.models.client_get200_response import ClientGet200Response
from authservice.models.client_get401_response import ClientGet401Response
from authservice.models.login_client_post200_response import LoginClientPost200Response
from authservice.models.login_client_post401_response import LoginClientPost401Response
from authservice.models.regenerate_client_credentials_post200_response import RegenerateClientCredentialsPost200Response
from authservice.models.register_post201_response import RegisterPost201Response
from authservice.models.register_post400_response import RegisterPost400Response
from authservice.models.register_post500_response import RegisterPost500Response
