# coding: utf-8

"""
    Deep3 Labs API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import deep3
from deep3.models.models_response_inner import ModelsResponseInner  # noqa: E501
from deep3.rest import ApiException

class TestModelsResponseInner(unittest.TestCase):
    """ModelsResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ModelsResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsResponseInner`
        """
        model = deep3.models.models_response_inner.ModelsResponseInner()  # noqa: E501
        if include_optional :
            return ModelsResponseInner(
                name = '', 
                chains = [
                    1.337
                    ]
            )
        else :
            return ModelsResponseInner(
                name = '',
                chains = [
                    1.337
                    ],
        )
        """

    def testModelsResponseInner(self):
        """Test ModelsResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
