
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-03T00:03:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "72c7b9d9b7073bf5f95420d40b4efc0df4fcfbe6",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
