#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class solution_plot:
    fluent_name = ...
    child_names = ...
    field = ...
    node_values = ...
    zones = ...
    surfaces = ...
    axes = ...
    curves = ...
    command_names = ...

    def plot(self, ):
        """
        Plot the solution.
        """

