#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class standalone_echem_model:
    fluent_name = ...
    child_names = ...
    enabled = ...
    life_model_enabled = ...
    report_time_step = ...
    total_run_num_cycles = ...
    total_run_time = ...
    ref_temp = ...
    load_type = ...
    external_p = ...
    total_deformation = ...
    external_stiff = ...
    ce_ec = ...
    diff_ec = ...
    rho_sei = ...
    m_sei = ...
    kappa_sei = ...
    k0_sei = ...
    ac_sei = ...
    u_sei = ...
    lithium_plating_enabled = ...
    rho_li = ...
    m_li = ...
    i0_lpl = ...
    ac_lpl = ...
    u_lpl = ...
    beta = ...
    multiplier = ...
    save_interval = ...
    restart_enabled = ...
    restart_filename = ...
    restart_profile = ...
    command_names = ...

    def run_echem_standalone(self, ):
        """
        Execute standalone echem model command.
        """

