
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-04T14:03:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "518a18ae8ad40c8a2f355bde7b7b4ca5a4bb9809",
 "version": "2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
