# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/aiq/distance.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)truera/protobuf/public/aiq/distance.proto\x12\ntruera.aiq*\xd7\x03\n\x0c\x44istanceType\x12\x19\n\x15UNKNOWN_DISTANCE_TYPE\x10\x00\x12#\n\x1f\x43\x41TEGORICAL_WASSERSTEIN_ORDERED\x10\x01\x12%\n!CATEGORICAL_WASSERSTEIN_UNORDERED\x10\x02\x12\x1c\n\x18TOTAL_VARIATION_DISTANCE\x10\x03\x12\'\n#CATEGORICAL_JENSEN_SHANNON_DISTANCE\x10\x04\x12\x13\n\x0f\x43HI_SQUARE_TEST\x10\x06\x12*\n&CATEGORICAL_POPULATION_STABILITY_INDEX\x10\x07\x12\x06\n\x02L1\x10\x08\x12\x06\n\x02L2\x10\t\x12\r\n\tLInfinity\x10\n\x12\x19\n\x15NUMERICAL_WASSERSTEIN\x10\x0b\x12\x16\n\x12\x44IFFERENCE_OF_MEAN\x10\x0c\x12%\n!NUMERICAL_JENSEN_SHANNON_DISTANCE\x10\r\x12\x13\n\x0f\x45NERGY_DISTANCE\x10\x0e\x12 \n\x1cKOLMOGOROV_SMIRNOV_STATISTIC\x10\x0f\x12(\n$NUMERICAL_POPULATION_STABILITY_INDEX\x10\x10\x42S\n\x17\x63om.truera.protobuf.aiqB\rDistanceProtoP\x01Z\'truera.com/protobuf/public/aiq/distanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.aiq.distance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.truera.protobuf.aiqB\rDistanceProtoP\001Z\'truera.com/protobuf/public/aiq/distance'
  _globals['_DISTANCETYPE']._serialized_start=58
  _globals['_DISTANCETYPE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
