
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-06T11:15:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d999108283f3576d1694c97a67dcd8f91c5e829f",
 "version": "3.2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
