#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class ecm_model_settings:
    fluent_name = ...
    child_names = ...
    initial_soc = ...
    ref_capacity = ...
    two_set_data = ...
    data_type = ...
    chen_rs = ...
    chen_r1 = ...
    chen_c1 = ...
    chen_r2 = ...
    chen_c2 = ...
    chen_voc = ...
    chen_rs_c = ...
    chen_r1_c = ...
    chen_c1_c = ...
    chen_r2_c = ...
    chen_c2_c = ...
    chen_voc_c = ...
    poly_rs = ...
    poly_r1 = ...
    poly_c1 = ...
    poly_r2 = ...
    poly_c2 = ...
    poly_voc = ...
    poly_rs_c = ...
    poly_r1_c = ...
    poly_c1_c = ...
    poly_r2_c = ...
    poly_c2_c = ...
    poly_voc_c = ...
    table_rs = ...
    table_r1 = ...
    table_c1 = ...
    table_r2 = ...
    table_c2 = ...
    table_r3 = ...
    table_c3 = ...
    table_voc = ...
    table_rs_c = ...
    table_r1_c = ...
    table_c1_c = ...
    table_r2_c = ...
    table_c2_c = ...
    table_r3_c = ...
    table_c3_c = ...
    table_voc_c = ...
    command_names = ...

    def read_all_data_table(self, enabled: bool, file_name_1: str):
        """
        Command to read all ECM data tables.
        
        Parameters
        ----------
            enabled : bool
                Read all ECM data tables.
            file_name_1 : str
                File name in reading ECM tables.
        
        """

    def write_all_data_table(self, enabled: bool, file_name: str):
        """
        Command to write all ECM data tables.
        
        Parameters
        ----------
            enabled : bool
                Write all ECM data tables.
            file_name : str
                File name in writing ECM tables.
        
        """

