#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class periodic_instancing_child:
    fluent_name = ...
    child_names = ...
    name = ...
    periodic_type = ...
    surfaces = ...
    translation = ...
    rotation = ...
    axis_origin = ...
    rotation_angle = ...
    repeats = ...
    command_names = ...

    def display(self, ):
        """
        Display periodic instancing.
        """

