#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class profile_data:
    fluent_name = ...
    child_names = ...
    profile = ...
    y_axis_function = ...
    x_axis_function = ...
    axes = ...
    curves = ...
    command_names = ...

    def plot(self, ):
        """
        Plot profile data.
        """

