#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class settings:
    fluent_name = ...
    child_names = ...
    degassing_verbosity = ...
    mass_flow = ...
    pressure_outlet = ...
    pressure_far_field = ...
    physical_velocity_porous_formulation = ...
    target_mass_flow_rate_settings = ...
    advanced = ...
    command_names = ...

    def detect_boundary_advection(self, ):
        """
        Detect and set boundary advection at solid walls.
        """

