#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class solar_load:
    fluent_name = ...
    child_names = ...
    solar_model = ...
    sun_direction_vector_definition = ...
    illumination_parameters = ...
    quad_tree_parameters = ...
    ground_reflectivity = ...
    scattering_fraction = ...
    solar_on_adjacent_fluid = ...
    solar_load_frequency = ...
    solar_calculator = ...
    apply_full_solar_irradiation = ...
    autoread_solar_data = ...
    autosave_solar_data = ...
    command_names = ...

    def solar_on_demand(self, ):
        """
        Calculate solar load on demand.
        """

