#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class solid_child:
    fluent_name = ...
    child_names = ...
    name = ...
    phase = ...
    general = ...
    reference_frame = ...
    mesh_motion = ...
    solid_motion = ...
    source_terms = ...
    fixed_values = ...
    material_orientation = ...
    disabled = ...
    internal = ...
    query_names = ...

    def adjacent_cell_zone(self, ):
        """
        Get adjacent cell zone for this face zone.
        """

    def shadow_face_zone(self, ):
        """
        Get shadow zone for this wall zone.
        """

