#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class user_defined_child:
    fluent_name = ...
    child_names = ...
    name = ...
    average_over = ...
    retain_instantaneous_values = ...
    function_name = ...
    input_params = ...
    command_names = ...

    def create_output_parameter(self, ):
        """
        'create_output_parameter' command.
        """

