#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class volumes_child:
    fluent_name = ...
    child_names = ...
    name = ...
    home_options = ...
    transparency_options = ...
    isovalue_options = ...
    clip_box_options = ...
    clip_sphere_options = ...
    compute_node_count = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

