#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class zone_assignment:
    fluent_name = ...
    child_names = ...
    active_zone = ...
    passive_zone = ...
    passive_zone_tab = ...
    virtual_connection = ...
    virtual_connection_file = ...
    positive_tab = ...
    negative_tab = ...
    command_names = ...

    def print_battery_connection(self, ):
        """
        Print battery connection information.
        """

