#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class mesh_child:
    fluent_name = ...
    child_names = ...
    name = ...
    options = ...
    edge_type = ...
    shrink_factor = ...
    surfaces_list = ...
    coloring = ...
    display_state_name = ...
    physics = ...
    geometry = ...
    surfaces = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

