#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class scene_child:
    fluent_name = ...
    child_names = ...
    name = ...
    title = ...
    temporary = ...
    graphics_objects = ...
    display_state_name = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

