#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class xy_plot_child:
    fluent_name = ...
    child_names = ...
    name = ...
    uid = ...
    options = ...
    plot_direction = ...
    x_axis_function = ...
    y_axis_function = ...
    surfaces_list = ...
    physics = ...
    geometry = ...
    surfaces = ...
    axes = ...
    curves = ...
    command_names = ...

    def display(self, ):
        """
        'display' command.
        """

