# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/qoi.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truera.protobuf.public import truera_custom_options_pb2 as truera_dot_protobuf_dot_public_dot_truera__custom__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n truera/protobuf/public/qoi.proto\x12\x06truera\x1a\x32truera/protobuf/public/truera_custom_options.proto*\x8e\x02\n\x12QuantityOfInterest\x12\x0f\n\x0bUNKNOWN_QOI\x10\x00\x12\x10\n\x0cLOGITS_SCORE\x10\x01\x12\x11\n\rPROBITS_SCORE\x10\x02\x12\x18\n\x14\x43LASSIFICATION_SCORE\x10\x03\x12\x14\n\x10REGRESSION_SCORE\x10\x04\x12\x0c\n\x08LOG_LOSS\x10\x05\x12*\n&MEAN_ABSOLUTE_ERROR_FOR_CLASSIFICATION\x10\x06\x12&\n\"MEAN_ABSOLUTE_ERROR_FOR_REGRESSION\x10\x07\x12\x08\n\x04RANK\x10\x08\x12\x11\n\rRANKING_SCORE\x10\t\x12\x13\n\x0fGENERATIVE_TEXT\x10\n*\xc2\x01\n\x18\x45xplanationAlgorithmType\x12!\n\x1d\x45XPLANATION_ALGORITHM_UNKNOWN\x10\x00\x12\x0e\n\nTRUERA_QII\x10\x01\x12\x0f\n\x0bKERNEL_SHAP\x10\x02\x12\x1c\n\x18TREE_SHAP_INTERVENTIONAL\x10\x03\x12\x1c\n\x18TREE_SHAP_PATH_DEPENDENT\x10\x04\x12\x18\n\x14INTEGRATED_GRADIENTS\x10\x05\x12\x0c\n\x08NLP_SHAP\x10\x06\x42N\n\x1c\x63om.truera.protobuf.externalB\x08QOIProtoP\x01Z\x1etruera.com/protobuf/public/qoi\x90\x82\x19\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.qoi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.truera.protobuf.externalB\010QOIProtoP\001Z\036truera.com/protobuf/public/qoi\220\202\031\001'
  _globals['_QUANTITYOFINTEREST']._serialized_start=97
  _globals['_QUANTITYOFINTEREST']._serialized_end=367
  _globals['_EXPLANATIONALGORITHMTYPE']._serialized_start=370
  _globals['_EXPLANATIONALGORITHMTYPE']._serialized_end=564
# @@protoc_insertion_point(module_scope)
