# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/tokenservice.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)truera/protobuf/public/tokenservice.proto\x12\rtruera.tokens\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n\x13GetUserTokenRequest\"\\\n\x1bGetUserTokenRequestResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12.\n\nexpires_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x85\x01\n\x0cTokenService\x12u\n\x0cGetUserToken\x12\".truera.tokens.GetUserTokenRequest\x1a*.truera.tokens.GetUserTokenRequestResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/GetUserTokenBU\n\x1c\x63om.truera.protobuf.externalB\nTokenProtoP\x01Z\'truera.com/protobuf/public/tokenserviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.tokenservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.truera.protobuf.externalB\nTokenProtoP\001Z\'truera.com/protobuf/public/tokenservice'
  _globals['_TOKENSERVICE'].methods_by_name['GetUserToken']._options = None
  _globals['_TOKENSERVICE'].methods_by_name['GetUserToken']._serialized_options = b'\202\323\344\223\002\017\022\r/GetUserToken'
  _globals['_GETUSERTOKENREQUEST']._serialized_start=123
  _globals['_GETUSERTOKENREQUEST']._serialized_end=144
  _globals['_GETUSERTOKENREQUESTRESPONSE']._serialized_start=146
  _globals['_GETUSERTOKENREQUESTRESPONSE']._serialized_end=238
  _globals['_TOKENSERVICE']._serialized_start=241
  _globals['_TOKENSERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
