import interscript
import regex as re
interscript.stdlib.define_map("alalc-div-Thaa-Latn-1997")
def _stage_main(s):
    s = re.compile("(?<=)ށް(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("ḫ", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")ން", re.MULTILINE).sub("n", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")ނ", re.MULTILINE).sub("ṁ", s)
    s = re.compile(""+interscript.stdlib.aliases["boundary"]+"(އ=?)(?=[ަާިީުޫެޭޮޯ])", re.MULTILINE).sub("", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ހ)", re.MULTILINE).sub("h", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ށ)", re.MULTILINE).sub("ś", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ނ)", re.MULTILINE).sub("n", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ރ)", re.MULTILINE).sub("r", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ބ)", re.MULTILINE).sub("b", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޅ)", re.MULTILINE).sub("ḷ", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ކ)", re.MULTILINE).sub("k", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ވ)", re.MULTILINE).sub("v", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=މ)", re.MULTILINE).sub("m", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ފ)", re.MULTILINE).sub("f", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ދ)", re.MULTILINE).sub("d", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ތ)", re.MULTILINE).sub("t", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ލ)", re.MULTILINE).sub("l", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ގ)", re.MULTILINE).sub("g", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޏ)", re.MULTILINE).sub("ñ", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ސ)", re.MULTILINE).sub("s", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޑ)", re.MULTILINE).sub("ḍ", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޖ)", re.MULTILINE).sub("j", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޗ)", re.MULTILINE).sub("c", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޒ)", re.MULTILINE).sub("z", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޓ)", re.MULTILINE).sub("ṭ", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޕ)", re.MULTILINE).sub("p", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?=ޔ)", re.MULTILINE).sub("y", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އް(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("h", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")އ(?=[ަާިީުޫެޭޮޯ])", re.MULTILINE).sub("ʼ", s)
    s = re.compile("ތްތ", re.MULTILINE).sub("t̤t", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_1044930410694324780)
    return s

interscript.stdlib.add_map_stage("alalc-div-Thaa-Latn-1997", "main", _stage_main)
_PTREE_1044930410694324780 = {1958:{None:"a"},1959:{None:"ā"},1960:{None:"i"},1961:{None:"ī"},1962:{None:"u"},1963:{None:"ū"},1964:{None:"e"},1965:{None:"ē"},1966:{None:"o"},1967:{None:"ō"},1968:{None:""},1920:{None:"h"},1921:{None:"ś"},1922:{None:"n"},1923:{None:"r"},1924:{None:"b"},1925:{None:"ḷ"},1926:{None:"k"},1927:{None:""},1928:{None:"v"},1929:{None:"m"},1930:{None:"f"},1931:{None:"d"},1932:{None:"t"},1933:{None:"l"},1934:{None:"g"},1935:{None:"ñ"},1936:{None:"s"},1937:{None:"ḍ"},1942:{None:"j"},1943:{None:"c"},1938:{None:"z"},1939:{None:"ṭ"},1941:{None:"p"},1940:{None:"y"},1944:{None:"th"},1945:{None:"ḥ"},1946:{None:"kh"},1947:{None:"dh"},1949:{None:"sh"},1950:{None:"ṣ"},1951:{None:"ḏ"},1952:{None:"t̤"},1953:{None:"ẓ"},1954:{None:"ʻ"},1955:{None:"gh"},1956:{None:"q"}}
