import interscript
import regex as re
interscript.stdlib.define_map("alalc-ben-Beng-Latn-1997")
interscript.stdlib.add_map_alias("alalc-ben-Beng-Latn-1997", "ben_special", "া")
interscript.stdlib.add_map_alias_re("alalc-ben-Beng-Latn-1997", "ben_special", "[ািীুূৃেৈোৌ্]")
def _stage_main(s):
    s = re.compile("ক(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("k", s)
    s = re.compile("খ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("গ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ঘ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("ঙ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("চ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("c", s)
    s = re.compile("ছ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("জ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("j", s)
    s = re.compile("ঝ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("ঞ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ট(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ঠ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("ড(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("ড়(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ṛ", s)
    s = re.compile("[ড়](?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ṛ", s)
    s = re.compile("ঢ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ঢ়(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ṛh", s)
    s = re.compile("ণ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ত(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("t", s)
    s = re.compile("ৎ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ṯ", s)
    s = re.compile("থ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("th", s)
    s = re.compile("দ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("d", s)
    s = re.compile("ধ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("ন(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("n", s)
    s = re.compile("প(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("p", s)
    s = re.compile("ফ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("ব(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("b", s)
    s = re.compile("ভ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("ম(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("m", s)
    s = re.compile("য(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("y", s)
    s = re.compile("য়(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ẏ", s)
    s = re.compile("য়(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ẏ", s)
    s = re.compile("র(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("r", s)
    s = re.compile("ল(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("l", s)
    s = re.compile("শ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("ś", s)
    s = re.compile("ষ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("sh", s)
    s = re.compile("স(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("s", s)
    s = re.compile("হ(?="+interscript.stdlib.get_alias_re("alalc-ben-Beng-Latn-1997", "ben_special")+")", re.MULTILINE).sub("h", s)
    s = re.compile("ବ(?=ব)", re.MULTILINE).sub("bba", s)
    s = re.compile("ঁ(?=[কখগঘঙচছজঝঞটঠডডঢঢণতৎথদধন])", re.MULTILINE).sub("m̐", s)
    s = re.compile("ଁ(?="+interscript.stdlib.aliases["boundary"]+")", re.MULTILINE).sub("m̐", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_1562369416640722342)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("alalc-ben-Beng-Latn-1997", "main", _stage_main)
_PTREE_1562369416640722342 = {2437:{None:"a"},2438:{None:"ā"},2439:{None:"i"},2440:{None:"ī"},2441:{None:"u"},2442:{None:"ū"},2447:{None:"e"},2448:{None:"ai"},2451:{None:"o"},2452:{None:"au"},2443:{None:"ṛ"},2528:{None:"ṝ"},2444:{None:"ḹ"},2453:{None:"ka"},2454:{None:"kha"},2455:{None:"ga"},2456:{None:"gha"},2457:{None:"ṅa"},2458:{None:"ca"},2459:{None:"cha"},2460:{None:"ja"},2461:{None:"jha"},2462:{None:"ña"},2463:{None:"ṭa"},2464:{None:"ṭha"},2465:{None:"ḍa",2492:{None:"ṛa"}},2524:{None:"ṛa"},2466:{None:"ḍha",2492:{None:"ṛha"}},2467:{None:"ṇa"},2468:{None:"ta"},2510:{None:"ṯa"},2469:{None:"tha"},2470:{None:"da"},2471:{None:"dha"},2472:{None:"na"},2474:{None:"pa"},2475:{None:"pha"},2476:{None:"ba"},2477:{None:"bha"},2478:{None:"ma"},2479:{None:"ya",2492:{None:"ẏa"}},2527:{None:"ẏa"},2480:{None:"ra"},2482:{None:"la"},2486:{None:"śa"},2487:{None:"sha"},2488:{None:"sa"},2489:{None:"ha"},2434:{None:"ṃ"},2435:{None:"ḥ"},2433:{None:"n̐"},2365:{None:"’"},2494:{None:"ā"},2495:{None:"i"},2496:{None:"ī"},2497:{None:"u"},2498:{None:"ū"},2499:{None:"ṛ"},2503:{None:"e"},2504:{None:"ai"},2507:{None:"o"},2508:{None:"au"},2509:{None:""},2534:{None:"0"},2535:{None:"1"},2536:{None:"2"},2537:{None:"3"},2538:{None:"4"},2539:{None:"5"},2540:{None:"6"},2541:{None:"7"},2542:{None:"8"},2543:{None:"9"}}
