import interscript
import regex as re
interscript.stdlib.define_map("bgnpcgn-ell-Grek-Latn-1962")
def _stage_main(s):
    s = re.compile("(?<=[ΑαΕεΗη])Υ", re.MULTILINE).sub("V", s)
    s = re.compile("(?<=[ΑαΕεΗη])υ", re.MULTILINE).sub("v", s)
    s = re.compile("(?<=[Οο])Υ", re.MULTILINE).sub("U", s)
    s = re.compile("(?<=[Οο])υ", re.MULTILINE).sub("u", s)
    s = re.compile("(?<=[Οο])ύ", re.MULTILINE).sub("ú", s)
    s = re.compile("Υ[Ιιί]", re.MULTILINE).sub("I", s)
    s = re.compile("υ[Ιιί]", re.MULTILINE).sub("i", s)
    s = re.compile("Υ[ί]", re.MULTILINE).sub("Í", s)
    s = re.compile("υ[ί]", re.MULTILINE).sub("í", s)
    s = re.compile("Γ(?=[ξΞχΧ])", re.MULTILINE).sub("N", s)
    s = re.compile("γ(?=[ξΞχΧ])", re.MULTILINE).sub("n", s)
    s = re.compile("Γ[Γγ]", re.MULTILINE).sub("Ng", s)
    s = re.compile("γγ", re.MULTILINE).sub("ng", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")Γ[Κκ]", re.MULTILINE).sub("G", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")γ[Κκ]", re.MULTILINE).sub("g", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")Γ[Κκ]", re.MULTILINE).sub("Ng", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")γ[Κκ]", re.MULTILINE).sub("ng", s)
    s = re.compile("Γ(?=[ΕεέΗηήΙιίΥυύ])", re.MULTILINE).sub("Y", s)
    s = re.compile("γ(?=[ΕεέΗηήΙιίΥυύ])", re.MULTILINE).sub("y", s)
    s = re.compile("Γ(?=[Oo][Ιιί])", re.MULTILINE).sub("Y", s)
    s = re.compile("γ(?=[Oo][Ιιί])", re.MULTILINE).sub("y", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")Ν[τΤ]", re.MULTILINE).sub("D", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")ν[τΤ]", re.MULTILINE).sub("d", s)
    s = re.compile("Ν[τΤ][ζΖ]", re.MULTILINE).sub("NTZ", s)
    s = re.compile("ν[τΤ][ζΖ]", re.MULTILINE).sub("ntz", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")Ν[τΤ]", re.MULTILINE).sub("Nd", s)
    s = re.compile("(?<!"+interscript.stdlib.aliases["boundary"]+")ν[τΤ]", re.MULTILINE).sub("nd", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")Μ[πΠ]", re.MULTILINE).sub("B", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["boundary"]+")μ[πΠ]", re.MULTILINE).sub("b", s)
    s = re.compile("Μ[πΠ]", re.MULTILINE).sub("Mb", s)
    s = re.compile("μ[πΠ]", re.MULTILINE).sub("mb", s)
    s = re.compile("(?<=[νΝ])Δ(?=[ρΡ])", re.MULTILINE).sub("d", s)
    s = re.compile("(?<=[νΝ])δ(?=[ρΡ])", re.MULTILINE).sub("d", s)
    s = re.compile("(?<=[ΑΆαά])Ε", re.MULTILINE).sub("Ë", s)
    s = re.compile("(?<=[ΑΆαά])ε", re.MULTILINE).sub("ë", s)
    s = re.compile("(?<=[ΑΆαά])έ", re.MULTILINE).sub("ë́", s)
    s = re.compile("(?<=[ΩΏωώ])Ο", re.MULTILINE).sub("Ö", s)
    s = re.compile("(?<=[ΩΏωώ])ο", re.MULTILINE).sub("ö", s)
    s = re.compile("(?<=[ΩΏωώ])ό", re.MULTILINE).sub("ö́", s)
    s = re.compile("(?<=[ΑΆαάΟΌοό])Η", re.MULTILINE).sub("Ï", s)
    s = re.compile("(?<=[ΑΆαάΟΌοό])η", re.MULTILINE).sub("ï", s)
    s = re.compile("(?<=[ΑΆαάΟΌοό])ή", re.MULTILINE).sub("ḯ", s)
    s = re.compile(";", re.MULTILINE).sub("?", s)
    s = re.compile(";", re.MULTILINE).sub("?", s)
    s = interscript.stdlib.parallel_regexp_gsub(s, *_PRE_4261318667079984371)
    return s

interscript.stdlib.add_map_stage("bgnpcgn-ell-Grek-Latn-1962", "main", _stage_main)
_PRE_4261318667079984371 = ["(?P<_0>ΕΪ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_1>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])ΕΪ)|(?P<_2>Εϊ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_3>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Εϊ)|(?P<_4>Έϊ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_5>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Έϊ)|(?P<_6>Έϊ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_7>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Έϊ)|(?P<_8>Αύ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_9>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Αύ)|(?P<_10>Εύ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_11>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Εύ)|(?P<_12>Ηύ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_13>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Ηύ)|(?P<_14>ΕΙ)|(?P<_15>Ει)|(?P<_16>Εί)|(?P<_17>ΕΪ)|(?P<_18>Εϊ)|(?P<_19>Έϊ)|(?P<_20>Έϊ)|(?P<_21>Αύ)|(?P<_22>Εύ)|(?P<_23>Ηύ)|(?P<_24>Θ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_25>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Θ)|(?P<_26>Χ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_27>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Χ)|(?P<_28>Ψ(?=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ]))|(?P<_29>(?<=[ΆΑΒΓΔΕΕΕΕΕΕΈΈΑΕΗΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΉΊΌΎΏΪΫ])Ψ)|(?P<_30>ει)|(?P<_31>εί)|(?P<_32>εϊ)|(?P<_33>έϊ)|(?P<_34>έι)|(?P<_35>αύ)|(?P<_36>εύ)|(?P<_37>ηύ)|(?P<_38>')|(?P<_39>Ά)|(?P<_40>Α)|(?P<_41>Β)|(?P<_42>Γ)|(?P<_43>Δ)|(?P<_44>Ε)|(?P<_45>Ζ)|(?P<_46>Η)|(?P<_47>Θ)|(?P<_48>Ι)|(?P<_49>Κ)|(?P<_50>Λ)|(?P<_51>Μ)|(?P<_52>Ν)|(?P<_53>Ξ)|(?P<_54>Ο)|(?P<_55>Π)|(?P<_56>Ρ)|(?P<_57>Σ)|(?P<_58>Τ)|(?P<_59>Υ)|(?P<_60>Φ)|(?P<_61>Χ)|(?P<_62>Ψ)|(?P<_63>Ω)|(?P<_64>Έ)|(?P<_65>Ή)|(?P<_66>Ί)|(?P<_67>Ό)|(?P<_68>Ύ)|(?P<_69>Ώ)|(?P<_70>Ϊ)|(?P<_71>Ϋ)|(?P<_72>ά)|(?P<_73>α)|(?P<_74>β)|(?P<_75>γ)|(?P<_76>δ)|(?P<_77>ε)|(?P<_78>ζ)|(?P<_79>η)|(?P<_80>θ)|(?P<_81>ι)|(?P<_82>κ)|(?P<_83>λ)|(?P<_84>μ)|(?P<_85>ν)|(?P<_86>ξ)|(?P<_87>ο)|(?P<_88>π)|(?P<_89>ρ)|(?P<_90>σ)|(?P<_91>ς)|(?P<_92>τ)|(?P<_93>υ)|(?P<_94>φ)|(?P<_95>χ)|(?P<_96>ψ)|(?P<_97>ω)|(?P<_98>έ)|(?P<_99>ή)|(?P<_100>ί)|(?P<_101>ό)|(?P<_102>ύ)|(?P<_103>ώ)|(?P<_104>ϊ)|(?P<_105>ϋ)|(?P<_106>ΐ)|(?P<_107>ΰ)|(?P<_108>·)|(?P<_109>·)", ["EÏ","EÏ","EÏ","EÏ","ÉÏ","ÉÏ","Éï","Éï","ÁV","ÁV","ÉV","ÉV","ÍV","ÍV","I","I","Í","Eï","Eï","Éï","Éï","Áv","Év","Ív","TH","TH","KH","KH","PS","PS","i","í","eï","éï","éï","áv","év","ív","","Á","A","V","G","Dh","E","Z","I","Th","I","K","L","M","N","X","O","P","R","S","T","I","F","Kh","Ps","O","É","Í","Í","Ó","Í","Ó","Ï","Ï","á","a","v","g","dh","e","z","i","th","i","k","l","m","n","x","o","p","r","s","s","t","i","f","kh","ps","o","é","í","í","ó","í","ó","ï","ï","ḯ","ḯ",";",";"]]
