import interscript
import regex as re
interscript.load_map("unicode")
interscript.load_map("var-kor-Hang-Hang-jamo")
interscript.stdlib.define_map("kp-kor-Hang-Latn-2002")
def _stage_main(s):
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")산((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("san"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")거리((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("gŏri"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")고개((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("gogae"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")대((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("dae"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")봉((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("bong"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")교((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("gyo"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")골((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("gol"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")각((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("gak"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")벌((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("bŏl"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")관((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("gwan"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")곶((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("got"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")강((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("gang"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")도((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("-do"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")시((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("-si"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")군((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("-gun"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")면((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("-myŏn"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")리((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("-ri"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")동((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("-dong"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")구((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("-gu"+"\\1", s)
    s = re.compile("(?<="+interscript.stdlib.aliases["any_character"]+""+interscript.stdlib.aliases["any_character"]+")구역((?:\\ |"+interscript.stdlib.aliases["line_end"]+"))", re.MULTILINE).sub("-guyŏk"+"\\1", s)
    s = re.compile("평양", re.MULTILINE).sub("Pyongyang", s)
    s = interscript.transliterate("var-kor-Hang-Hang-jamo", s, "main")
    s = re.compile(""+interscript.stdlib.aliases["line_start"]+"", re.MULTILINE).sub(" ", s)
    s = re.compile(""+interscript.stdlib.aliases["line_end"]+"", re.MULTILINE).sub(" ", s)
    s = re.compile("ᆩᄋ", re.MULTILINE).sub("ᆨᄁ", s)
    s = re.compile("ᆩ", re.MULTILINE).sub("ᆨ", s)
    s = re.compile("ᆪᄋ", re.MULTILINE).sub("ᆨᄉ", s)
    s = re.compile("ᆪ", re.MULTILINE).sub("ᆨ", s)
    s = re.compile("ᆬᄋ", re.MULTILINE).sub("ᆫᄌ", s)
    s = re.compile("ᆬ", re.MULTILINE).sub("ᆫ", s)
    s = re.compile("ᆭᄀ", re.MULTILINE).sub("ᆫᄏ", s)
    s = re.compile("ᆭᄃ", re.MULTILINE).sub("ᆫᄐ", s)
    s = re.compile("ᆭᄇ", re.MULTILINE).sub("ᆫᄑ", s)
    s = re.compile("ᆭᄌ", re.MULTILINE).sub("ᆫᄎ", s)
    s = re.compile("ᆭ", re.MULTILINE).sub("ᆫ", s)
    s = re.compile("ᆮ(?=[ᄀᄁᄂᄃᄄᄅᄆᄇᄈᄉᄊᄌᄍᄎᄏᄐᄑᄒ])", re.MULTILINE).sub("ᆺ", s)
    s = re.compile("ᆳᄋ", re.MULTILINE).sub("ᆯᄉ", s)
    s = re.compile("ᆳ", re.MULTILINE).sub("ᆯ", s)
    s = re.compile("ᆴᄋ", re.MULTILINE).sub("ᆯᄐ", s)
    s = re.compile("ᆴ", re.MULTILINE).sub("ᆯ", s)
    s = re.compile("ᆵᄋ", re.MULTILINE).sub("ᆯᄑ", s)
    s = re.compile("ᆵ(?=[ᄃᄄᄐ])", re.MULTILINE).sub("ᆯ", s)
    s = re.compile("ᆵ", re.MULTILINE).sub("ᄇ", s)
    s = re.compile("ᆶᄀ", re.MULTILINE).sub("ᆯᄏ", s)
    s = re.compile("ᆶᄃ", re.MULTILINE).sub("ᆯᄐ", s)
    s = re.compile("ᆶᄇ", re.MULTILINE).sub("ᆯᄑ", s)
    s = re.compile("ᆶᄌ", re.MULTILINE).sub("ᆯᄎ", s)
    s = re.compile("ᆶ", re.MULTILINE).sub("ᆯ", s)
    s = re.compile("ᆹᄋ", re.MULTILINE).sub("ᄇᄉ", s)
    s = re.compile("ᆹ", re.MULTILINE).sub("ᄇ", s)
    s = re.compile("ᆻᄋ", re.MULTILINE).sub("ᆺᄊ", s)
    s = re.compile("ᆻ", re.MULTILINE).sub("ᆺ", s)
    s = re.compile("ᆽᄋ", re.MULTILINE).sub("ᆺᄌ", s)
    s = re.compile("ᆽ", re.MULTILINE).sub("ᆺ", s)
    s = re.compile("ᆾᄋ", re.MULTILINE).sub("ᆺᄎ", s)
    s = re.compile("ᆾ", re.MULTILINE).sub("ᆺ", s)
    s = re.compile("ᆿᄋ", re.MULTILINE).sub("ᆨᄏ", s)
    s = re.compile("ᆿ", re.MULTILINE).sub("ᆨ", s)
    s = re.compile("ᇀᄋ", re.MULTILINE).sub("ᆺᄐ", s)
    s = re.compile("ᇀ", re.MULTILINE).sub("ᆺ", s)
    s = re.compile("ᇁᄋ", re.MULTILINE).sub("ᆸᄑ", s)
    s = re.compile("ᇁ", re.MULTILINE).sub("ᆸ", s)
    s = re.compile("ᇂᄀ", re.MULTILINE).sub("ᄏ", s)
    s = re.compile("ᇂᄃ", re.MULTILINE).sub("ᄐ", s)
    s = re.compile("ᇂᄇ", re.MULTILINE).sub("ᄑ", s)
    s = re.compile("ᇂᄌ", re.MULTILINE).sub("ᄎ", s)
    s = re.compile("ᇂ", re.MULTILINE).sub("", s)
    s = interscript.stdlib.parallel_regexp_gsub(s, *_PRE_2352977599164669950)
    s = re.compile(""+interscript.stdlib.aliases["line_start"]+"\\ ", re.MULTILINE).sub("", s)
    s = re.compile("\\ "+interscript.stdlib.aliases["line_end"]+"", re.MULTILINE).sub("", s)
    s = interscript.functions.title_case(s, {})
    return s

interscript.stdlib.add_map_stage("kp-kor-Hang-Latn-2002", "main", _stage_main)
_PRE_2352977599164669950 = ["(?P<_0>ᆨᄀ)|(?P<_1>ᆨᄂ)|(?P<_2>ᆨᄃ)|(?P<_3>ᆨᄅ)|(?P<_4>ᆨᄆ)|(?P<_5>ᆨᄇ)|(?P<_6>ᆨᄉ)|(?P<_7>ᆨᄋ)|(?P<_8>ᆨᄌ)|(?P<_9>ᆨᄎ)|(?P<_10>ᆨᄏ)|(?P<_11>ᆨᄐ)|(?P<_12>ᆨᄑ)|(?P<_13>ᆨᄒ)|(?P<_14>ᆨᄁ)|(?P<_15>ᆨᄄ)|(?P<_16>ᆨᄈ)|(?P<_17>ᆨᄊ)|(?P<_18>ᆨᄍ)|(?P<_19>ᆫᄀ)|(?P<_20>ᆫᄂ)|(?P<_21>ᆫᄃ)|(?P<_22>ᆫᄅ)|(?P<_23>ᆫᄆ)|(?P<_24>ᆫᄇ)|(?P<_25>ᆫᄉ)|(?P<_26>ᆫᄋ)|(?P<_27>ᆫᄌ)|(?P<_28>ᆫᄎ)|(?P<_29>ᆫᄏ)|(?P<_30>ᆫᄐ)|(?P<_31>ᆫᄑ)|(?P<_32>ᆫᄒ)|(?P<_33>ᆫᄁ)|(?P<_34>ᆫᄄ)|(?P<_35>ᆫᄈ)|(?P<_36>ᆫᄊ)|(?P<_37>ᆫᄍ)|(?P<_38>ᆯᄀ)|(?P<_39>ᆯᄂ)|(?P<_40>ᆯᄃ)|(?P<_41>ᆯᄅ)|(?P<_42>ᆯᄆ)|(?P<_43>ᆯᄇ)|(?P<_44>ᆯᄉ)|(?P<_45>ᆯᄋ)|(?P<_46>ᆯᄌ)|(?P<_47>ᆯᄎ)|(?P<_48>ᆯᄏ)|(?P<_49>ᆯᄐ)|(?P<_50>ᆯᄑ)|(?P<_51>ᆯᄒ)|(?P<_52>ᆯᄁ)|(?P<_53>ᆯᄄ)|(?P<_54>ᆯᄈ)|(?P<_55>ᆯᄊ)|(?P<_56>ᆯᄍ)|(?P<_57>ᆷᄀ)|(?P<_58>ᆷᄂ)|(?P<_59>ᆷᄃ)|(?P<_60>ᆷᄅ)|(?P<_61>ᆷᄆ)|(?P<_62>ᆷᄇ)|(?P<_63>ᆷᄉ)|(?P<_64>ᆷᄋ)|(?P<_65>ᆷᄌ)|(?P<_66>ᆷᄎ)|(?P<_67>ᆷᄏ)|(?P<_68>ᆷᄐ)|(?P<_69>ᆷᄑ)|(?P<_70>ᆷᄒ)|(?P<_71>ᆷᄁ)|(?P<_72>ᆷᄄ)|(?P<_73>ᆷᄈ)|(?P<_74>ᆷᄊ)|(?P<_75>ᆷᄍ)|(?P<_76>ᆸᄀ)|(?P<_77>ᆸᄂ)|(?P<_78>ᆸᄃ)|(?P<_79>ᆸᄅ)|(?P<_80>ᆸᄆ)|(?P<_81>ᆸᄇ)|(?P<_82>ᆸᄉ)|(?P<_83>ᆸᄋ)|(?P<_84>ᆸᄌ)|(?P<_85>ᆸᄎ)|(?P<_86>ᆸᄏ)|(?P<_87>ᆸᄐ)|(?P<_88>ᆸᄑ)|(?P<_89>ᆸᄒ)|(?P<_90>ᆸᄁ)|(?P<_91>ᆸᄄ)|(?P<_92>ᆸᄈ)|(?P<_93>ᆸᄊ)|(?P<_94>ᆸᄍ)|(?P<_95>ᆺᄀ)|(?P<_96>ᆺᄂ)|(?P<_97>ᆺᄃ)|(?P<_98>ᆺᄅ)|(?P<_99>ᆺᄆ)|(?P<_100>ᆺᄇ)|(?P<_101>ᆺᄉ)|(?P<_102>ᆺᄋ)|(?P<_103>ᆺᄌ)|(?P<_104>ᆺᄎ)|(?P<_105>ᆺᄏ)|(?P<_106>ᆺᄐ)|(?P<_107>ᆺᄑ)|(?P<_108>ᆺᄒ)|(?P<_109>ᆺᄁ)|(?P<_110>ᆺᄄ)|(?P<_111>ᆺᄈ)|(?P<_112>ᆺᄊ)|(?P<_113>ᆺᄍ)|(?P<_114>ᆼᄀ)|(?P<_115>ᆼᄂ)|(?P<_116>ᆼᄃ)|(?P<_117>ᆼᄅ)|(?P<_118>ᆼᄆ)|(?P<_119>ᆼᄇ)|(?P<_120>ᆼᄉ)|(?P<_121>ᆼᄋ)|(?P<_122>ᆼᄌ)|(?P<_123>ᆼᄎ)|(?P<_124>ᆼᄏ)|(?P<_125>ᆼᄐ)|(?P<_126>ᆼᄑ)|(?P<_127>ᆼᄒ)|(?P<_128>ᆼᄁ)|(?P<_129>ᆼᄄ)|(?P<_130>ᆼᄈ)|(?P<_131>ᆼᄊ)|(?P<_132>ᆼᄍ)|(?P<_133>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄀ)|(?P<_134>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄂ)|(?P<_135>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄃ)|(?P<_136>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄅ)|(?P<_137>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄆ)|(?P<_138>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄇ)|(?P<_139>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄉ)|(?P<_140>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄋ)|(?P<_141>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄌ)|(?P<_142>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄎ)|(?P<_143>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄏ)|(?P<_144>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄐ)|(?P<_145>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄑ)|(?P<_146>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄒ)|(?P<_147>(?<=(?:[\\-]|[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄁ)|(?P<_148>(?<=(?:[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄄ)|(?P<_149>(?<=(?:[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄈ)|(?P<_150>(?<=(?:[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄊ)|(?P<_151>(?<=(?:[A-Z]|[a-z]|[0-9]|[ᅡᅢᅣᅤᅥᅦᅧᅨᅩᅪᅫᅬᅭᅮᅯᅰᅱᅲᅳᅴᅵ]))ᄍ)|(?P<_152>ᆰᄀ)|(?P<_153>ᆰᄂ)|(?P<_154>ᆰᄃ)|(?P<_155>ᆰᄅ)|(?P<_156>ᆰᄆ)|(?P<_157>ᆰᄇ)|(?P<_158>ᆰᄉ)|(?P<_159>ᆰᄋ)|(?P<_160>ᆰᄌ)|(?P<_161>ᆰᄎ)|(?P<_162>ᆰᄏ)|(?P<_163>ᆰᄐ)|(?P<_164>ᆰᄑ)|(?P<_165>ᆰᄒ)|(?P<_166>ᆰᄁ)|(?P<_167>ᆰᄄ)|(?P<_168>ᆰᄈ)|(?P<_169>ᆰᄊ)|(?P<_170>ᆰᄍ)|(?P<_171>ᆱᄀ)|(?P<_172>ᆱᄂ)|(?P<_173>ᆱᄃ)|(?P<_174>ᆱᄅ)|(?P<_175>ᆱᄆ)|(?P<_176>ᆱᄇ)|(?P<_177>ᆱᄉ)|(?P<_178>ᆱᄋ)|(?P<_179>ᆱᄌ)|(?P<_180>ᆱᄎ)|(?P<_181>ᆱᄏ)|(?P<_182>ᆱᄐ)|(?P<_183>ᆱᄑ)|(?P<_184>ᆱᄒ)|(?P<_185>ᆱᄁ)|(?P<_186>ᆱᄄ)|(?P<_187>ᆱᄈ)|(?P<_188>ᆱᄊ)|(?P<_189>ᆱᄍ)|(?P<_190>ᆲᄀ)|(?P<_191>ᆲᄂ)|(?P<_192>ᆲᄃ)|(?P<_193>ᆲᄅ)|(?P<_194>ᆲᄆ)|(?P<_195>ᆲᄇ)|(?P<_196>ᆲᄉ)|(?P<_197>ᆲᄋ)|(?P<_198>ᆲᄌ)|(?P<_199>ᆲᄎ)|(?P<_200>ᆲᄏ)|(?P<_201>ᆲᄐ)|(?P<_202>ᆲᄑ)|(?P<_203>ᆲᄒ)|(?P<_204>ᆲᄁ)|(?P<_205>ᆲᄄ)|(?P<_206>ᆲᄈ)|(?P<_207>ᆲᄊ)|(?P<_208>ᆲᄍ)|(?P<_209>(?<=\\ )ᄀ)|(?P<_210>(?<=\\ )ᄂ)|(?P<_211>(?<=\\ )ᄃ)|(?P<_212>(?<=\\ )ᄅ)|(?P<_213>(?<=\\ )ᄆ)|(?P<_214>(?<=\\ )ᄇ)|(?P<_215>(?<=\\ )ᄉ)|(?P<_216>(?<=\\ )ᄋ)|(?P<_217>(?<=\\ )ᄌ)|(?P<_218>(?<=\\ )ᄎ)|(?P<_219>(?<=\\ )ᄏ)|(?P<_220>(?<=\\ )ᄐ)|(?P<_221>(?<=\\ )ᄑ)|(?P<_222>(?<=\\ )ᄒ)|(?P<_223>(?<=\\ )ᄁ)|(?P<_224>(?<=\\ )ᄭ)|(?P<_225>(?<=\\ )ᄄ)|(?P<_226>(?<=\\ )ᄯ)|(?P<_227>(?<=\\ )ᄈ)|(?P<_228>(?<=\\ )ᄲ)|(?P<_229>(?<=\\ )ᄊ)|(?P<_230>(?<=\\ )ᄍ)|(?P<_231>(?<=\\ )ᄶ)|(?P<_232>ᆨ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_233>ᆫ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_234>ᆮ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_235>ᆯ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_236>ᆷ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_237>ᆸ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_238>ᆺ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_239>ᆼ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_240>ᆽ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_241>ᆾ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_242>ᆿ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_243>ᇀ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_244>ᇁ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_245>ᆰ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_246>ᆲ(?!"+interscript.stdlib.get_alias_re("unicode", "unicode_hangul")+"))|(?P<_247>ᅡ)|(?P<_248>ᅣ)|(?P<_249>ᅥ)|(?P<_250>ᅧ)|(?P<_251>ᅩ)|(?P<_252>ᅭ)|(?P<_253>ᅮ)|(?P<_254>ᅲ)|(?P<_255>ᅳ)|(?P<_256>ᅵ)|(?P<_257>ᅢ)|(?P<_258>ᅤ)|(?P<_259>ᅦ)|(?P<_260>ᅨ)|(?P<_261>ᅬ)|(?P<_262>ᅱ)|(?P<_263>ᅴ)|(?P<_264>ᅪ)|(?P<_265>ᅯ)|(?P<_266>ᅫ)|(?P<_267>ᅰ)", ["kk","ngn","kt","ngn","ngm","kp","ks","g","kj","kch","kkh","kth","kp","kh","kkk","ktt","kpp","kss","kjj","n-g","nn","nd","ll","nm","nb","ns","n","nj","nch","nkh","nth","nph","nh","nkk","ntt","npp","nss","njj","lk","ll","lt","ll","lm","lb","ls","r","lj","lch","lkh","lth","lph","lh","lkk","ltt","lpp","lss","ljj","mg","mn","md","mr","mm","mb","ms","m","mj","mch","mkh","mth","mph","mh","mkk","mtt","mpp","mss","mjj","pk","mn","pt","mr","mm","pp","ps","b","pj","pch","pkh","pth","pph","ph","pkk","ptt","ppp","pss","pjj","tk","nn","tt","nr","nm","tp","ts","d","tj","tch","tkh","tth","tph","th","tkk","ttt","tpp","tss","tjj","ngg","ngn","ngd","ngn","ngm","ngb","ngs","ng","ngj","ngch","ngkh","ngth","ngph","ngh","ngkk","ngtt","ngpp","ngss","ngjj","g","n","d","r","m","b","s","","j","ch","kh","th","ph","h","kk","tt","pp","ss","jj","lg","ngn","kt","ngn","ngm","kp","ks","lg","kj","kch","lkh","kth","kph","lkh","lkk","ktt","kpp","kss","kjj","mg","mn","md","mr","lm","mb","ms","lm","mj","mch","mkh","mth","mph","mh","mkk","mtt","mpp","mss","mjj","pk","mn","pt","mr","mm","lb","ps","lb","pj","pch","pkh","pth","lph","lph","pkk","ptt","lpp","pss","pjj","k","n","t","r","m","p","s","","j","ch","kh","th","ph","h","kk","kk","tt","tt","pp","pp","ss","jj","jj","k","n","t","l","m","p","t","ng","t","t","k","t","p","k","p","a","ya","ŏ","yŏ","o","yo","u","yu","ü","i","ae","yae","e","ye","oe","wi","üi","wa","wo","wae","we"]]
