import interscript
import regex as re
interscript.stdlib.define_map("un-ori-Orya-Latn-1972")
interscript.stdlib.add_map_alias("un-ori-Orya-Latn-1972", "orya_chars_1", "୍")
interscript.stdlib.add_map_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1", "[୍ାିୀୁୂୃେୈୋୌ]")
def _stage_main(s):
    s = re.compile("କ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("k", s)
    s = re.compile("ଖ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("kh", s)
    s = re.compile("ଗ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("g", s)
    s = re.compile("ଘ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("gh", s)
    s = re.compile("ଙ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ṅ", s)
    s = re.compile("ଚ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ch", s)
    s = re.compile("ଛ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("chhh", s)
    s = re.compile("ଜ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("j", s)
    s = re.compile("ଝ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("jh", s)
    s = re.compile("ଞ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ñ", s)
    s = re.compile("ଟ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ṭ", s)
    s = re.compile("ଠ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ṭh", s)
    s = re.compile("ଡ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ḍ", s)
    s = re.compile("ଡ଼(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ṙ", s)
    s = re.compile("ଢ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ḍh", s)
    s = re.compile("ଢ଼(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ṙh", s)
    s = re.compile("ଣ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ṇ", s)
    s = re.compile("ତ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("t", s)
    s = re.compile("ଥ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("th", s)
    s = re.compile("ଦ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("d", s)
    s = re.compile("ଧ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("dh", s)
    s = re.compile("ନ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("n", s)
    s = re.compile("ପ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("p", s)
    s = re.compile("ଫ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ph", s)
    s = re.compile("ବ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("b", s)
    s = re.compile("ଭ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("bh", s)
    s = re.compile("ମ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("m", s)
    s = re.compile("ଯ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ỵ", s)
    s = re.compile("ୟ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("y", s)
    s = re.compile("ର(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("r", s)
    s = re.compile("ଲ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("l", s)
    s = re.compile("ଳ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ḷ", s)
    s = re.compile("ଶ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("sh", s)
    s = re.compile("ଷ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("ṣh", s)
    s = re.compile("ସ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("s", s)
    s = re.compile("ହ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("h", s)
    s = re.compile("କ୍ଷ(?="+interscript.stdlib.get_alias_re("un-ori-Orya-Latn-1972", "orya_chars_1")+")", re.MULTILINE).sub("kṣh", s)
    s = interscript.stdlib.parallel_replace_tree(s, _PTREE_1495106451622630642)
    s = interscript.functions.compose(s, {})
    return s

interscript.stdlib.add_map_stage("un-ori-Orya-Latn-1972", "main", _stage_main)
_PTREE_1495106451622630642 = {2821:{None:"a"},2822:{None:"ā"},2823:{None:"i"},2824:{None:"ī"},2825:{None:"u"},2826:{None:"ū"},2827:{None:"ṛ"},2912:{None:"ṝ"},2828:{None:"ḻ"},2831:{None:"e"},2832:{None:"ai"},2835:{None:"o"},2929:{None:"va"},2836:{None:"au"},2837:{None:"ka",2893:{2871:{None:"kṣha"}}},2838:{None:"kha"},2839:{None:"ga"},2840:{None:"gha"},2841:{None:"ṅa"},2842:{None:"cha"},2843:{None:"chha"},2844:{None:"ja"},2845:{None:"jha"},2846:{None:"ña"},2847:{None:"ṭa"},2848:{None:"ṭha"},2849:{None:"ḍa"},2908:{None:"ṙa"},2850:{None:"ḍha"},2909:{None:"ṙha"},2851:{None:"ṇa"},2852:{None:"ta"},2853:{None:"tha"},2854:{None:"da"},2855:{None:"dha"},2856:{None:"na"},2858:{None:"pa"},2859:{None:"pha"},2860:{None:"ba"},2861:{None:"bha"},2862:{None:"ma"},2863:{None:"ỵa"},2911:{None:"ya"},2864:{None:"ra"},2866:{None:"la"},2867:{None:"ḷa"},2870:{None:"sha"},2871:{None:"ṣha"},2872:{None:"sa"},2873:{None:"ha"},2817:{None:"m"},2819:{None:"ḥ"},2818:{None:"ṃ"},2878:{None:"ā"},2879:{None:"i"},2880:{None:"ī"},2881:{None:"u"},2882:{None:"ū"},2883:{None:"ṛ"},2887:{None:"e"},2888:{None:"ai"},2891:{None:"o"},2892:{None:"au"},2381:{None:""},2893:{None:""},2364:{None:""},2876:{None:""},2404:{None:"."},8205:{None:""},8204:{None:""},2918:{None:"0"},2919:{None:"1"},2920:{None:"2"},2921:{None:"3"},2922:{None:"4"},2923:{None:"5"},2924:{None:"6"},2925:{None:"7"},2926:{None:"8"},2927:{None:"9"}}
