# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyhdmap/proto/hdmap_lib/proto/geometry.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyhdmap.proto.hdmap_lib.proto import id_pb2 as pyhdmap_dot_proto_dot_hdmap__lib_dot_proto_dot_id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,pyhdmap/proto/hdmap_lib/proto/geometry.proto\x12\thdmap_lib\x1a&pyhdmap/proto/hdmap_lib/proto/id.proto\"-\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0c\n\x01z\x18\x03 \x01(\x01:\x01\x30\"\xd9\x02\n\x0eLineStringData\x12\x19\n\x02id\x18\x01 \x01(\x0b\x32\r.hdmap_lib.Id\x12.\n\x05\x63olor\x18\x02 \x01(\x0e\x32\x1f.hdmap_lib.LineStringData.Color\x12,\n\x04type\x18\x03 \x01(\x0e\x32\x1e.hdmap_lib.LineStringData.Type\x12\"\n\x06points\x18\x04 \x03(\x0b\x32\x12.hdmap_lib.Point3D\x12\x0e\n\x06length\x18\x05 \x01(\x01\"\x1e\n\x05\x43olor\x12\t\n\x05WHITE\x10\x01\x12\n\n\x06YELLOW\x10\x02\"z\n\x04Type\x12\x08\n\x04NONE\x10\x01\x12\t\n\x05SOLID\x10\x02\x12\n\n\x06\x42ROKEN\x10\x03\x12\x10\n\x0c\x44OUBLE_SOLID\x10\x04\x12\x11\n\rDOUBLE_BROKEN\x10\x05\x12\x10\n\x0c\x42ROKEN_SOLID\x10\x06\x12\x10\n\x0cSOLID_BROKEN\x10\x07\x12\x08\n\x04\x43URB\x10\x08\"B\n\nLineString\x12\x19\n\x02id\x18\x01 \x01(\x0b\x32\r.hdmap_lib.Id\x12\x19\n\nis_reverse\x18\x02 \x01(\x08:\x05\x66\x61lse\"-\n\x05\x43urve\x12$\n\x05lines\x18\x01 \x03(\x0b\x32\x15.hdmap_lib.LineString\"/\n\x07Polygon\x12$\n\x05lines\x18\x01 \x03(\x0b\x32\x15.hdmap_lib.LineString')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyhdmap.proto.hdmap_lib.proto.geometry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINT3D']._serialized_start=99
  _globals['_POINT3D']._serialized_end=144
  _globals['_LINESTRINGDATA']._serialized_start=147
  _globals['_LINESTRINGDATA']._serialized_end=492
  _globals['_LINESTRINGDATA_COLOR']._serialized_start=338
  _globals['_LINESTRINGDATA_COLOR']._serialized_end=368
  _globals['_LINESTRINGDATA_TYPE']._serialized_start=370
  _globals['_LINESTRINGDATA_TYPE']._serialized_end=492
  _globals['_LINESTRING']._serialized_start=494
  _globals['_LINESTRING']._serialized_end=560
  _globals['_CURVE']._serialized_start=562
  _globals['_CURVE']._serialized_end=607
  _globals['_POLYGON']._serialized_start=609
  _globals['_POLYGON']._serialized_end=656
# @@protoc_insertion_point(module_scope)
