from .calculator import *
from .tts import *
from .scr_shot import *
from .sq_root import *
from .arithmetic_average import *
from .owl import *
from .safe import *
from .write import *
from .DB_send import *
from .DB_read import *