# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyhdmap/proto/hdmap_lib/proto/signal.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyhdmap.proto.hdmap_lib.proto import geometry_pb2 as pyhdmap_dot_proto_dot_hdmap__lib_dot_proto_dot_geometry__pb2
from pyhdmap.proto.hdmap_lib.proto import id_pb2 as pyhdmap_dot_proto_dot_hdmap__lib_dot_proto_dot_id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*pyhdmap/proto/hdmap_lib/proto/signal.proto\x12\thdmap_lib\x1a,pyhdmap/proto/hdmap_lib/proto/geometry.proto\x1a&pyhdmap/proto/hdmap_lib/proto/id.proto\"\xd4\x04\n\x06Signal\x12\x19\n\x02id\x18\x01 \x01(\x0b\x32\r.hdmap_lib.Id\x12;\n\x10\x63ombination_type\x18\x02 \x01(\x0e\x32!.hdmap_lib.Signal.CombinationType\x12\x31\n\x0bsignal_type\x18\x03 \x01(\x0e\x32\x1c.hdmap_lib.Signal.SignalType\x12$\n\x08\x62oundary\x18\x04 \x01(\x0b\x32\x12.hdmap_lib.Polygon\x12\"\n\x06\x63\x65nter\x18\x05 \x01(\x0b\x32\x12.hdmap_lib.Point3D\"\x8a\x01\n\x0f\x43ombinationType\x12\x17\n\x13UNKNOWN_COMNINATION\x10\x01\x12\x14\n\x10MIX_2_HORIZONTAL\x10\x02\x12\x12\n\x0eMIX_2_VERTICAL\x10\x03\x12\x14\n\x10MIX_3_HORIZONTAL\x10\x04\x12\x12\n\x0eMIX_3_VERTICAL\x10\x05\x12\n\n\x06SINGLE\x10\x06\"\xe7\x01\n\nSignalType\x12\x12\n\x0eUNKNOWN_SIGNAL\x10\x01\x12\n\n\x06\x43IRCLE\x10\x02\x12\x0e\n\nARROW_LEFT\x10\x03\x12\x11\n\rARROW_FORWARD\x10\x04\x12\x0f\n\x0b\x41RROW_RIGHT\x10\x05\x12\x1a\n\x16\x41RROW_LEFT_AND_FORWARD\x10\x06\x12\x1b\n\x17\x41RROW_RIGHT_AND_FORWARD\x10\x07\x12\x10\n\x0c\x41RROW_U_TURN\x10\x08\x12\x19\n\x15\x41RROW_LEFT_AND_U_TURN\x10\t\x12\r\n\tCOUNTDOWN\x10\n\x12\x10\n\x0cWAITING_AREA\x10\x0b')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyhdmap.proto.hdmap_lib.proto.signal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIGNAL']._serialized_start=144
  _globals['_SIGNAL']._serialized_end=740
  _globals['_SIGNAL_COMBINATIONTYPE']._serialized_start=368
  _globals['_SIGNAL_COMBINATIONTYPE']._serialized_end=506
  _globals['_SIGNAL_SIGNALTYPE']._serialized_start=509
  _globals['_SIGNAL_SIGNALTYPE']._serialized_end=740
# @@protoc_insertion_point(module_scope)
