# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/background_data_split_info.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from truera.protobuf.public.data import filter_pb2 as truera_dot_protobuf_dot_public_dot_data_dot_filter__pb2
from truera.protobuf.public import truera_custom_options_pb2 as truera_dot_protobuf_dot_public_dot_truera__custom__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7truera/protobuf/public/background_data_split_info.proto\x12\x06truera\x1a(truera/protobuf/public/data/filter.proto\x1a\x32truera/protobuf/public/truera_custom_options.proto\"\x8a\x01\n\x17\x42\x61\x63kgroundDataSplitInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x03\x61ll\x18\x02 \x01(\x08H\x00\x12\x0f\n\x05index\x18\x03 \x01(\x05H\x00\x12:\n\x11\x66ilter_expression\x18\x04 \x01(\x0b\x32\x1d.truera.data.FilterExpressionH\x00\x42\x07\n\x05usageBR\n\x13\x63om.truera.protobufP\x01Z5truera.com/protobuf/public/background_data_split_info\x90\x82\x19\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.background_data_split_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.truera.protobufP\001Z5truera.com/protobuf/public/background_data_split_info\220\202\031\001'
  _globals['_BACKGROUNDDATASPLITINFO']._serialized_start=162
  _globals['_BACKGROUNDDATASPLITINFO']._serialized_end=300
# @@protoc_insertion_point(module_scope)
